Add redstone node
redstone-finance/redstone-oracles-monorepo pull request #10
Opened 2022-07-25 11:15 UTC by cehali

2022-07-25 19:37 UTC, cehali commented
Github actions for monorepo based on https://github.com/int128/typescript-actions-monorepo
Typescript tsconfig.json files based on https://dev.to/mxro/the-ultimate-guide-to-typescript-monorepos-5ap7

2022-07-29 23:07 UTC, hatskier requested changes

2022-07-29 23:07 UTC, hatskier commented on packages/protocol/src/data-package/SignedDataPackage.ts
> +  signerAddress: string;
Can we please create this extended interface with non-core data (`signerAddress`, `permawebTx`, `provider`, etc.) in the redstone-node code as it shouldn't be a part of the protocol?

2022-07-29 23:07 UTC, hatskier commented on packages/protocol/src/data-package/SignedDataPackage.ts
> +    const signerAddressAsBytes = this.recoverSignerPublicKey();
Let's not recoverSignerPublicKey in this function, it is not neccessary always for serialization to plain object, but significantly consumes CPU resources

2022-07-29 23:07 UTC, hatskier commented on packages/protocol/src/data-point/StringDataPoint.ts
> +  serializeToBroadcast() {
Shouldn't we remove it?

2022-07-31 13:14 UTC, cehali commented on packages/protocol/src/data-package/SignedDataPackage.ts
> +    const signerAddressAsBytes = this.recoverSignerPublicKey();
Let's talk about it tomorrow

2022-08-04 10:53 UTC, hatskier approved these changes

2022-08-04 10:53 UTC, merged