chore: remove summary in dry runs
redstone-finance/redstone-oracles-monorepo pull request #1071
Opened 2023-09-12 13:19 UTC by cehali

2023-09-13 07:12 UTC, cehali commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
Unfortunately, it made dry runs pass each time even when exit code was other than one

2023-09-13 07:12 UTC, cehali commented on packages/oracle-node/manifests/data-services/arbitrum.json
> +        "uniswap-v3-ethereum-on-chain-usdt-500"
It was different than in primary manifest

2023-09-13 07:12 UTC, cehali commented on packages/oracle-node/manifests/data-services/arbitrum.json
> -        "trader-joe-v2-avalanche-on-chain-wavax",
Slippage error

2023-09-13 07:13 UTC, cehali commented on packages/oracle-node/manifests/data-services/avalanche.json
> -      "source": ["avalanche-evm-fetcher"]
Discussed with Delta and removed with their approval

2023-09-13 07:14 UTC, cehali commented on packages/oracle-node/manifests/data-services/main.json
> -    },
It was a bad idea as we don't have `GLP_AVALANCHE` and `GLP_ARBITRUM` defined in configs. I think on dev GLP from avalanche will be enough

2023-09-13 07:37 UTC, rpiszczatowski commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
Instead of getting rid of the feature we wan do something like this:
```
run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log; test ${PIPESTATUS[0]} -ne 0
```

2023-09-13 07:40 UTC, koonopek commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
Maybe lets test it well and add in next PR?

2023-09-13 07:40 UTC, koonopek submitted a review, later dismissed

2023-09-13 07:47 UTC, rpiszczatowski requested changes
Please apply my suggestion.

2023-09-14 10:19 UTC, cehali commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> +          SKIPPED_SOURCES: '["binance", "binancecoinm", "binanceusdm", "bybit"]'
binance and bybit are not working in us

2023-09-14 10:19 UTC, cehali commented on .github/workflows/oracle-main-dry-run-test.yml
> +          SKIPPED_SOURCES: '["binance", "binancecoinm", "binanceusdm", "bybit", "kaiko", "kaiko-v2", "twelve-data", "twelve-data-etf-uk"]'
I skipped `kaiko` and `twelve-data` in dev data services, left only `twelve-data` in stocks manifest

2023-09-14 10:20 UTC, cehali commented on packages/oracle-node/manifests/data-services/arbitrum.json
> -        "oceanex",
`oceanex` is not responding

2023-09-14 10:21 UTC, cehali commented on packages/oracle-node/manifests/data-services/arbitrum.json
> -        "uniswap"
I will remove all legacy dexes using the graph in the next PR, this one was not responding entirely.

2023-09-14 10:21 UTC, cehali commented on packages/oracle-node/manifests/data-services/avalanche.json
> -    },
I removed it from manifest but I promised Delta that we will wait till Friday with deploying this change

2023-09-14 10:26 UTC, cehali commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
I don't see much advantage with this feature and it disabled our dry-runs for a long time. Additionally, I think whole logs are crucial when you want to fix not working test, you can go back and check what went wrong and then fix it without the necessity to run everything locally

2023-09-14 10:39 UTC, rpiszczatowski commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
- `I don't see much advantage` - I think @koonopek once said that he sees and I also see the advantage of seeing which fetcher failed. (You don't need to look at the summary if you don't want to ;) )
- `it disabled our dry-runs for a long time` - irrelevant, one way or another it will be enabled now
- `whole logs are crucial when you want to fix not working test` - agreed, but you have all the logs, this feature doesn't disable storing logs as the artifact.

2023-09-14 10:49 UTC, cehali commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
- `I don't see much advantage - I think @koonopek once said that he sees and I also see the advantage of seeing which fetcher failed. (You don't need to look at the summary if you don't want to ;) )` - I am sure about it, none looked to the logs because the test always passed. Are you sure `Request failed:` is the only reason the test could fail? It looks like it handles only one situation. Also, with a current check of sources fetched you will see exactly which source is missing, which indicates the fetcher directly
- `it disabled our dry-runs for a long time - irrelevant, one way or another it will be enabled now` - have you checked this with different situations like not enough tokens fetched, missing sources etc.? 

I think it is reckless to leave a feature which disabled our dry-runs when it is not crucial for our software but only nice to have.

2023-09-14 11:05 UTC, koonopek reviewed
GJ! left some minior things

2023-09-14 11:05 UTC, koonopek commented on packages/oracle-node/test/dry-run/helpers.ts
> +export const getMainManifestWithTokenWithSources = () => {
`Tokens`
            ^ s is missing i think

2023-09-14 11:05 UTC, koonopek commented on packages/oracle-node/test/dry-run/helpers.ts
> +    process.env.SKIPPED_TOKENS ?? "[]"
We are already have `knowNotWorkingDataFeeds` how it differs from `SKIPPED_TOKENS`

2023-09-14 11:06 UTC, koonopek commented on packages/oracle-node/test/dry-run/helpers.ts
> +        (s) => !skippedSources.includes(s)
You can just ignore if can't easly find easier way to do this

2023-09-14 11:22 UTC, rpiszczatowski commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
I think we do not understand each other. My proposal is to enable dry runs reporting errors as usual. The feature only adds an additional summary and does not affect testing process in any other way. This was my bash-related mistake to make tests always succeed, but once you applied the proposed change everything will work as you expect.

2023-09-14 11:23 UTC, rpiszczatowski commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
To explain additioanlly: if any other error will cause the tests to fail the summary will be empty but tests WILL still fail.

2023-09-14 11:56 UTC, cehali commented on packages/oracle-node/manifests/data-services/avalanche.json
> -        "pangolin-on-chain-wavax",
It doesn't pass slippage check

2023-09-14 11:58 UTC, cehali commented on packages/oracle-node/test/dry-run/dry-run-tests-configs.ts
> +    knowNotWorkingDataFeeds: ["PREMIA-TWAP-60"],
Because we don't use private key from dev nodes. In twap we can only use data packages which were created by the same account, meaning I as an node can only use data packages I created before.

2023-09-14 12:04 UTC, cehali commented on packages/oracle-node/test/dry-run/dry-run-test.spec.ts
>        expect(sourcesFetched.sort()).toEqual(sourcesFromManifest.sort());
I am not sure which was the previous comment but if you mean that we can use it in `checkNumberOfTokensBroadcasted` the answer is that we cannot. We use different things, here we use `sourcesMetadata` from spy on aggregator and there we use `dataPackages` from broadcaster. We cannot use `dataPackages` from the broadcaster because it has source metadata with every source even invalid ones. Adding all checks for sources here would be duplicate code from `PriceService` and potentially lead to problems. I think it is a quiet clean solution, maybe not straightforward.

2023-09-14 12:19 UTC, cehali commented on packages/oracle-node/test/dry-run/dry-run-test.spec.ts
> +    expect(allTokensBroadcasted).toBeGreaterThanOrEqual(requiredTokensCount);
Added here https://github.com/redstone-finance/redstone-oracles-monorepo/pull/1071/files#diff-ef251d2f22ebb8c2e7c25efb05ebfc2de71b578ee47e257a5537817873650a94R119

2023-09-14 13:15 UTC, rpiszczatowski commented on .github/workflows/oracle-arbitrum-dry-run-test.yml
> -        run: yarn test:arbitrum-dry-run 2>&1 | tee logs.log
Agreed ofline that for now we will leave it disabled. At some point I may re-enable the feature.

2023-09-14 13:16 UTC, rpiszczatowski approved these changes

2023-09-14 13:36 UTC, koonopek commented on packages/oracle-node/manifests/data-services/avalanche.json
> -        "pangolin-on-chain-wavax",
@rpiszczatowski fix, hasn't fixed that?

2023-09-14 13:38 UTC, koonopek commented on packages/oracle-node/test/dry-run/dry-run-test.spec.ts
> +    expect(allTokensBroadcasted).toBeGreaterThanOrEqual(requiredTokensCount);
Is it the same, why we have similiar code in diffrent places?

2023-09-14 13:39 UTC, koonopek commented on packages/oracle-node/test/dry-run/dry-run-test.spec.ts
>        expect(sourcesFetched.sort()).toEqual(sourcesFromManifest.sort());
I mean 
`expect(sourcesFetched.sort()).toEqual(sourcesFromManifest.sort());` is better then just comparing length, like here:
```    
const notWorkingDataFeedsCount =
      config.knowNotWorkingDataFeeds?.length ?? 0;
    const requiredTokensCount = tokens.length - notWorkingDataFeedsCount;
    expect(allTokensBroadcasted).toBeGreaterThanOrEqual(requiredTokensCount);
    ```

2023-09-14 13:40 UTC, koonopek commented on packages/oracle-node/test/dry-run/dry-run-tests-configs.ts
> +    knowNotWorkingDataFeeds: ["PREMIA-TWAP-60"],
1) Why do we need private key to verify, public key is enough.
2) We could mock part of veryfing signer

2023-09-14 13:42 UTC, koonopek commented on packages/oracle-node/test/dry-run/helpers.ts
> +    process.env.SKIPPED_TOKENS ?? "[]"
1) Can we remove it, and have single source of truth for  `knowNotWorkingDataFeeds`

2023-09-14 13:42 UTC, koonopek commented on packages/oracle-node/test/dry-run/helpers.ts
> +        (s) => !skippedSources.includes(s)
I don't think it is bad either

2023-09-14 13:44 UTC, koonopek requested changes
:)

2023-09-14 13:45 UTC, cehali commented on packages/oracle-node/test/dry-run/dry-run-test.spec.ts
> +    expect(allTokensBroadcasted).toBeGreaterThanOrEqual(requiredTokensCount);
What is the same?

2023-09-14 14:42 UTC, cehali commented on packages/oracle-node/test/dry-run/dry-run-test.spec.ts
>        expect(sourcesFetched.sort()).toEqual(sourcesFromManifest.sort());
Changed

2023-09-14 14:42 UTC, cehali commented on packages/oracle-node/test/dry-run/dry-run-tests-configs.ts
> +    knowNotWorkingDataFeeds: ["PREMIA-TWAP-60"],
Good point, refactored to mock ethereum address and now we can check twaps

2023-09-14 14:43 UTC, cehali commented on packages/oracle-node/test/dry-run/helpers.ts
> +    process.env.SKIPPED_TOKENS ?? "[]"
Removed

2023-09-14 14:55 UTC, koonopek commented on packages/oracle-node/test/dry-run/dry-run-tests-configs.ts
> +    ethereumAddress: "0x8BB8F32Df04c8b654987DAaeD53D6B6091e3B774",
HARDHAT_MOCK_ADDRESS?

2023-09-14 14:56 UTC, koonopek submitted a review, later dismissed
GJ!

2023-09-14 15:12 UTC, cehali commented on packages/oracle-node/manifests/data-services/arbitrum.json
> -        "camelot-usdt",
Removed it as it gives deviated value for a long time
<img width="1146" alt="image" src="https://github.com/redstone-finance/redstone-oracles-monorepo/assets/35804520/0a40c0fb-f10d-4725-af3b-fda1f0ee9525">

2023-09-14 23:59 UTC, hatskier commented on packages/oracle-node/manifests/data-services/arbitrum.json
> -        "camelot-usdt",
Let's use grafana for this type of analysis ;) It's much more powerful

2023-09-15 07:45 UTC, rpiszczatowski commented on packages/oracle-node/src/types.ts
> +  source?: string[] | undefined;
It can be deleted once my PR with eslint is merged.

2023-09-15 07:46 UTC, rpiszczatowski approved these changes

2023-09-15 08:15 UTC, cehali commented on packages/oracle-node/manifests/data-services/arbitrum.json
> -        "camelot-usdt",
nit-pick 😄 give me approve

2023-09-15 09:09 UTC, merged