chore: update configs and code for other connectors
redstone-finance/redstone-oracles-monorepo pull request #1083
Opened 2023-09-13 14:43 UTC by Lukasz2891

2023-09-14 12:37 UTC, rpiszczatowski commented on .gitignore
> +packages/**/yarn*
What is this?

2023-09-14 12:52 UTC, rpiszczatowski commented on packages/fuel-connector/src/prices/FuelPricesContractAdapter.ts
> +  }
You can tell `InvocationResult` what you expect from it as a value property.
```suggestion
  protected static extractNumbers(
    result: InvocationResult<U256Output[]>
  ): number[] {
    return result.value.map(num);
  }
```

2023-09-14 12:59 UTC, rpiszczatowski commented on packages/fuel-connector/test/prices/prices.spec.ts
> +    } catch (e: unknown) {
`: unknown` is redundant. `} catch (e) {` is the same.

2023-09-14 13:00 UTC, rpiszczatowski commented on packages/fuel-connector/test/prices/prices.spec.ts
> +      expect(e as Error).not.toBeNull();
Is this type assertion needed?

2023-09-14 13:06 UTC, rpiszczatowski commented on packages/starknet-connector/src/prices/StarknetPricesContractAdapter.ts
> +    return (response as Result[]).map(getNumberFromStarknetResult);
This is cool. Recursive type definition. `Result` can be an array of `Result`s.

2023-09-14 13:09 UTC, rpiszczatowski commented on packages/starknet-connector/tsconfig.build.json
> +}
new line at the end of file

2023-09-14 13:14 UTC, rpiszczatowski commented on packages/starknet-relayer/src/start-relayer.ts
> +void (async () => {
I think we agreed to use eslint annotation as a cleaner way of disabling those warnings.

Even though my personal preference would be probably to use `void` as shorter and terser, we should stick to comments.

2023-09-14 13:14 UTC, rpiszczatowski requested changes
Minor suggestions.

2023-09-14 14:06 UTC, Lukasz2891 commented on .gitignore
> +packages/**/yarn*
ignoring all yarn.locks and yarn.lock-error inside the particular package ("remove that file for `yarn.lock`")

2023-09-14 14:08 UTC, Lukasz2891 commented on packages/starknet-relayer/src/start-relayer.ts
> +void (async () => {
yes, it was changed before the discussion and just remained .

2023-09-15 07:41 UTC, cehali commented on packages/fuel-connector/tsconfig.json
> +}
Please add new line

2023-09-15 07:41 UTC, cehali commented on packages/fuel-connector/tsconfig.build.json
> +}
Please add new line

2023-09-15 07:41 UTC, cehali approved these changes

2023-09-15 08:09 UTC, rpiszczatowski commented on .gitignore
> +packages/**/yarn*
sorry for how I formulated a question. It should be: why do we ignore patterns of files other than the files created by tools we use in a normal development cycle? There shouldn't be any yarn* files created inside packages. If you have such files then:
1. you can delete them if not needed otherwise
2. you can add them to .git/info/exclude if those are your private stuff not relevant to anybody except you.

I consider adding too much stuff to .gitignore a harmful practice in general. (said somebody whose .gitignore is 116 lines long ;) ).

2023-09-15 08:11 UTC, rpiszczatowski approved these changes

2023-09-15 08:27 UTC, Lukasz2891 commented on .gitignore
> +packages/**/yarn*
But they are created in a development cycle, but maybe my own is abnormal :p I'll delete the line or will use 'exclude' :)

2023-09-15 08:29 UTC, Lukasz2891 commented on packages/fuel-connector/tsconfig.json
> +}
I'll do it soon :)

2023-09-15 08:29 UTC, Lukasz2891 commented on packages/fuel-connector/tsconfig.build.json
> +}
Will be added soon ;)

2023-09-15 08:29 UTC, merged