feat: Oracle node telemetry
redstone-finance/redstone-oracles-monorepo pull request #1093
Opened 2023-09-14 18:05 UTC by wrybakiewicz

UPDATE:
- fixed problem with lack of .git in our dockerfile by removing git last commit usage replaced by env variable

- add node performance data & docker image version telemetry (sent to Influxdb and to be displayed in grafana)
- add telemetry in CI (to special influxdb redstone-test bucket, we empty it every hour so there is not much trash data from CI) - so we can test if telemetry doesn't brake anything in node
- DOCKER_IMAGE_TAG is set during image build
- added batch sending (after node queries series finish, every 10s)
- 
After merging I will add env variables TELEMETRY_URL  and TELEMETRY_AUTHORIZATION_TOKEN  to our terraform for all nodes.

2023-09-14 23:45 UTC, hatskier reviewed
Good job! Added 2 ideas for improvements

2023-09-14 23:45 UTC, hatskier commented on packages/oracle-node/src/utils/performance-tracker.ts
> +  axios
Can you add tests to be sure that node works even if the `post` promise fails. We had problems with this in past, because this is default Node.js behaviour

2023-09-14 23:45 UTC, hatskier commented on .github/workflows/long-arbitrum-dry-run-test.yml
> +          DOCKER_IMAGE_TAG: "ci"
What do you think about getting this value without env variable, but using some mechanism like this: https://github.com/redstone-finance/redstone-oracles-monorepo/blob/50df3a08ebf3131d3c395160268f68995198e5f5/packages/oracle-node/src/NodeRunner.ts#L156

It would help us to have a single source of truth

2023-09-15 13:40 UTC, koonopek commented on .github/workflows/long-arbitrum-dry-run-test.yml
> +          DOCKER_IMAGE_TAG: "ci"
And in CI we could simply override this

2023-09-15 13:50 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +  if (!isTelemetryEnabled) {
1) we use `logger` for logging
2) I don't think that this log is fully. It can be printed once when node starts. Rest is redundant

2023-09-15 13:50 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +    config.telemetryUrl !== "" && config.telemetryAuthorizationToken;
Shouldn't be `||` instead of `&&`?

2023-09-15 13:50 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +    const measurementName = "nodePerformance";
Can be top level const

2023-09-15 13:50 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +async function sendMetric(
Shouldnt we batch telemetry logs?

2023-09-15 13:50 UTC, koonopek reviewed
GJ!

2023-09-20 13:10 UTC, hatskier requested changes

2023-09-20 13:10 UTC, hatskier commented on packages/oracle-node/src/utils/performance-tracker.ts
> +export async function sendNodeTelemetry() {
IMHO it's not very clear from the naming that `sendNodeTelemetry` sends the actual request, but `sendNodePerformanceMetric` does not. Can we rename use the word queue instead of send in this functions and remove `await telemetrySendService.sendMetricsBatch();` from the `sendNodeTelemetry` and just call it where it's needed in the NodeRunner? WDYT?

2023-09-20 17:59 UTC, hatskier approved these changes
LGTM!

2023-09-21 07:58 UTC, koonopek commented on packages/oracle-node/src/telemetry/TelemetrySendService.ts
> +  static getInstance(): TelemetrySendService {
[For future] In JS modules are singleton so to create singleton it is enough to do export `export const telemetrySendService = new TelemetrySendService()` and just import it

2023-09-21 08:03 UTC, koonopek requested changes

2023-09-21 08:03 UTC, koonopek commented on packages/oracle-node/src/NodeRunner.ts
> +    await queueNodeTelemetry();
[IMPORTANT] I think we shouldn't block here, we want node to still working properly even if telemetry server is down

2023-09-21 08:03 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +export async function queueNodeTelemetry() {
This shouldn't be async I think

2023-09-21 08:03 UTC, koonopek commented on packages/oracle-node/test/integration/NodeRunner.spec.ts
> +      expect(axios.post).toHaveBeenCalledTimes(3);
This test is flaky, we should check paths, but we can leave it for now

2023-09-21 08:04 UTC, koonopek commented on packages/oracle-node/src/NodeRunner.ts
> +    await queueNodeTelemetry();
this should be pointing to one line below (212)

2023-09-21 08:13 UTC, wrybakiewicz commented on packages/oracle-node/src/utils/performance-tracker.ts
> +export async function queueNodeTelemetry() {
there is fetching git commit that is async :/

2023-09-21 08:42 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +export async function queueNodeTelemetry() {
true, sorry didnt notice

2023-09-21 08:45 UTC, koonopek commented on packages/oracle-node/src/NodeRunner.ts
> +      .catch(() => logger.info("Failed to send telemetry"));
This log is redundant, cause we are already printing failure in `sendMetricsBatch`.
What do you think about:
```ts
await queueNodeTelemetry();
this.telemetrySendService.sendMetricsBatch(); // it shouldn't throw because it is in try catch
```

2023-09-21 08:48 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +export async function queueNodeTelemetry() {
Also can we wrap this in try-catch whole body, this function should never fail cause it is not crucial from node standpoint

2023-09-21 08:49 UTC, koonopek commented on packages/oracle-node/src/utils/performance-tracker.ts
> +function queueNodePerformanceMetric(label: string, executionTime: number) {
Also can we wrap this in try-catch whole body, this function should never fail cause it is not crucial from node standpoint

2023-09-21 11:00 UTC, koonopek submitted a review, later dismissed

2023-09-27 07:13 UTC, koonopek approved these changes
GJ 🥇

2023-09-27 07:13 UTC, koonopek commented on .github/workflows/deploy-images-to-ecr-public.yml
> +          docker build -t "$IMAGE:$TAG" -f packages/oracle-node/Dockerfile --build-arg DOCKER_IMAGE_TAG=$TAG .
<3

2023-09-27 08:12 UTC, merged