feat: add tokens for Mento
redstone-finance/redstone-oracles-monorepo pull request #1128
Opened 2023-09-20 07:59 UTC by cehali

2023-09-20 08:52 UTC, rpiszczatowski submitted a review, later dismissed
+1

2023-09-20 11:41 UTC, hatskier commented on packages/oracle-node/manifests/data-services/primary.json
> +      "source": ["ecb", "kaiko", "kaiko-v2", "twelve-data", "yf-unofficial"]
Let's not use `yf-unofficial` please on prod nodes

2023-09-20 11:41 UTC, hatskier commented on packages/oracle-node/manifests/data-services/primary.json
> +        "yf-unofficial"
Let's not use yf-unofficial please on prod nodes

2023-09-20 11:41 UTC, hatskier commented on packages/oracle-node/manifests/data-services/primary.json
> +    "cEUR": {
I would change cEUR to CELO/EUR

2023-09-20 11:41 UTC, hatskier commented on packages/oracle-node/manifests/data-services/primary.json
> +    "cBRL": {
I would change cBRL to CELO/BRL

2023-09-20 17:42 UTC, hatskier commented on packages/oracle-node/manifests/data-services/main.json
> +    "cEUR": {
Don't we want to change it as well?

2023-09-20 17:42 UTC, hatskier commented on packages/oracle-node/manifests/data-services/primary.json
> +        "binance-api-fetcher",
Can we please remove the word fetcher to be consistent and to make it more readable for app.redstone.finance users (especially ones who will check it after our Mento proposal)?

2023-09-20 17:42 UTC, hatskier commented on packages/oracle-node/manifests/data-services/primary.json
> +    "BRL": {
The number of sources is really impressive now, good job!

2023-09-20 18:35 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    return (await axios.get(url)).data as AxiosResponse<unknown>;
Technically it is better to do it like this:
```suggestion
    return (await axios.get<unknown>(url)).data;
```
without explicit type assertions.

2023-09-20 18:59 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    const [extractedValue] = jp.query(response, jsonpath) as unknown[];
Maybe instead of `unknown[]` we can use `Decimal.Value[]` which is compatible with how we want to use this return value. This way you could remove type assertion below in `Decimal` construction.

2023-09-20 19:03 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +  ): Decimal {
Is concept of decimals relevant here? I see no handling of it.

2023-09-20 19:08 UTC, rpiszczatowski requested changes
minor changes required.

2023-09-21 06:58 UTC, cehali commented on packages/oracle-node/manifests/data-services/main.json
> +    "cEUR": {
Yes, probably issue when resolving confilcts

2023-09-21 07:02 UTC, cehali commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +  ): Decimal {
I am not sure if I understand correctly but the casting to decimal value is used to "validate" value from response. Decimals.js will check if the value is a proper numberlike. Also, decimal value is used in `makeAdditionalCalculations`, maybe there aren't big calculations but I wanted to be consistent with other fetchers

2023-09-21 07:45 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +  ): Decimal {
Sorry, the question was about decimals like in WETH has 18 decimals and USDC 6, not the decimals.js library.
So the question would be: Does this API operate on ETH or WEI level, etc.?

2023-09-21 08:38 UTC, koonopek commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    return new Decimal(extractedValue as string);
[can be omitted] Why casting to string instead of Decimal.Value

2023-09-21 08:38 UTC, koonopek commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +  private makeAdditionalCalculations(
[can be omitted] Intresting function name :D

2023-09-21 08:38 UTC, koonopek commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +export class ApiFetcher extends MultiRequestFetcher {
Nice!

2023-09-21 08:38 UTC, koonopek commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    const [extractedValue] = jp.query(response, jsonpath) as Decimal.Value[];
[Important] Should we also very if values is not undefined?

2023-09-21 08:38 UTC, koonopek commented on packages/oracle-node/test/fetchers/api-fetcher.spec.ts
> +import axios from "axios";
We should have propably test for each ApiFetcher from api-fetchers-config. To not break something when we will be doing changes to ApiFetcher

2023-09-21 08:41 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    return new Decimal(extractedValue as string);
No casting is required. Casting is generally bad. We should try to avoid it if possible.
This is an argument with `[can be omitted]` part :)

2023-09-21 08:44 UTC, rpiszczatowski commented on packages/oracle-node/test/fetchers/api-fetcher.spec.ts
> +import axios from "axios";
Agree. Maybe we can mock a single success response for each of the fetchers and one test for 'expected' failures like `undefined` response.

2023-09-21 09:04 UTC, rpiszczatowski reviewed
.

2023-09-21 14:44 UTC, cehali commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +  ): Decimal {
Currently all values are returned on ETH level

2023-09-21 14:44 UTC, cehali commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    return new Decimal(extractedValue as string);
Fixed

2023-09-21 14:44 UTC, cehali commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +  private makeAdditionalCalculations(
Changed

2023-09-21 14:44 UTC, cehali commented on packages/oracle-node/test/fetchers/api-fetcher.spec.ts
> +import axios from "axios";
Added

2023-09-21 14:51 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    if (typeof extractedValue === "undefined") {
```suggestion
    if (xtractedValue === undefined) {
```
Is simpler, but does the same, right?

2023-09-21 15:01 UTC, rpiszczatowski commented on packages/oracle-node/test/fetchers/api-fetcher.spec.ts
> +        value: 0.20691159205641568,
[nice to have]

I assume this value is `1 / (4.8818 * 0.99)`.
I prefer to use values that make clear what to expect.
You could e.g. introduce the variables `brlPrice = 4.8818` and `usdtPrice=0.99` then use them in mock definition and then in expected value like `(1/(brlPrice*usdtPrice))`. For such a simple logic I find the described approach valuable as it makes clear what the fetcher should calculate

2023-09-21 15:02 UTC, rpiszczatowski submitted a review, later dismissed
Nice

2023-09-22 05:34 UTC, koonopek approved these changes

2023-09-22 05:34 UTC, koonopek commented on packages/oracle-node/test/fetchers/api-fetcher.spec.ts
> +  test("coinbase api", async () => {
Great!

2023-09-22 07:13 UTC, cehali commented on packages/oracle-node/src/fetchers/api-fetcher/ApiFetcher.ts
> +    if (typeof extractedValue === "undefined") {
![image](https://github.com/redstone-finance/redstone-oracles-monorepo/assets/35804520/98f0d412-9b0f-426b-8a95-169bf2541595)

2023-09-22 09:54 UTC, hatskier approved these changes
Good job!

2023-09-22 09:54 UTC, hatskier commented on packages/oracle-node/src/fetchers/api-fetcher/api-fetcher-configs.json
> +  "kucoin": {
Great idea to create a fetcher like this one!

2023-09-22 14:04 UTC, hatskier approved these changes

2023-09-22 14:07 UTC, merged