v0.3.3-alpha.0
redstone-finance/redstone-oracles-monorepo pull request #1135
Opened 2023-09-20 13:42 UTC by koonopek

* Testing if publishing is working correctly (with alpha version) - works
* Had to add in every package.json publishConfig: access: public, because packages starting from `@org-name` are by default private

2023-09-20 15:02 UTC, rpiszczatowski commented on packages/starknet-connector/package.json
> +  "gitHead": "c7b70dfbd7450063c8aabb891b2fc46e75df440a"
Should we really have 'gitHead' property in our repo.
I haven't found lots of documentation on it, but according to this: https://github.com/lerna/lerna/issues/1880 'gitHead' should be a transient property only set for publishing time.

2023-09-20 15:03 UTC, rpiszczatowski commented on packages/starknet-connector/package.json
> +    "access": "public"
Do we really want to publish starknet-connector, starknet-relayer and ton-connector?

2023-09-20 15:04 UTC, rpiszczatowski commented on packages/fuel-connector/package.json
> +  "gitHead": "c7b70dfbd7450063c8aabb891b2fc46e75df440a"
Do we want to publish this connector?

2023-09-20 15:05 UTC, rpiszczatowski commented on packages/eth-contracts/package.json
> +  "version": "0.3.2-alpha.0",
Really 0.3.2? Other packages have 0.3.3.

2023-09-20 15:05 UTC, rpiszczatowski requested changes
Couple of questions.

2023-09-21 08:08 UTC, koonopek commented on packages/starknet-connector/package.json
> +    "access": "public"
Why not? @Lukasz2891

2023-09-21 08:08 UTC, koonopek commented on packages/fuel-connector/package.json
> +  "gitHead": "c7b70dfbd7450063c8aabb891b2fc46e75df440a"
Why not? @Lukasz2891

2023-09-21 08:12 UTC, koonopek commented on packages/starknet-connector/package.json
> +  "gitHead": "c7b70dfbd7450063c8aabb891b2fc46e75df440a"
So it wasn't cleared by lerna :(

2023-09-21 08:12 UTC, koonopek commented on packages/starknet-connector/package.json
> +    "access": "public"
Also it is already published. I haven't configured what should be published in this PR it was done on first PR on lerna

2023-09-21 08:15 UTC, koonopek commented on packages/eth-contracts/package.json
> +  "version": "0.3.2-alpha.0",
fixed! Good catch

2023-09-21 08:16 UTC, koonopek commented on packages/starknet-connector/package.json
> +  "gitHead": "c7b70dfbd7450063c8aabb891b2fc46e75df440a"
Removed

2023-09-21 09:02 UTC, rpiszczatowski approved these changes

2023-09-21 11:02 UTC, merged