feat: test update prices on chain on single node price change
redstone-finance/redstone-oracles-monorepo pull request #1191
Opened 2023-10-03 13:43 UTC by rpiszczatowski

2023-10-05 07:57 UTC, koonopek requested changes

2023-10-05 07:57 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +  ): boolean {
Nice!

2023-10-05 07:57 UTC, koonopek commented on packages/integration/src/framework/cache-layer-manager.ts
> +import redstoneSDK, { DataPackagesRequestParams } from "@redstone-finance/sdk";
If importing as a namespace (which is great), maybe lets stick to using it.

2023-10-05 07:57 UTC, koonopek commented on packages/integration/src/framework/relayer-manager.ts
> +  initialPricesCacheInstances?: CacheLayerInstance[]
I think this function is doing too much already (and this param is really weired, you have to read code to understand taht), what do you think about just calling after `deployMockAdapter`
  ```
    const currentPrices = await fetchDataPackages(initialPricesCacheInstances);
    await updateValuesInAdapterContract(contract, currentPrices);
  ```
Otherwise functions like this will grow and grow, by adding next params like this.

2023-10-05 07:57 UTC, koonopek commented on packages/integration/src/relayer-conditions/relayer-one-rpc-down.ts
> +  const adapterContract = await deployMockAdapter(undefined, [
We don't need here inital prcies, also rpcUrl: undefiend looks pretty smelly

2023-10-05 07:57 UTC, koonopek commented on packages/integration/src/relayer-conditions/relayer-value-and-time-condition.ts
> +  const adapterContract = await deployMockAdapter(undefined, [
Same

2023-10-05 07:57 UTC, koonopek commented on packages/integration/src/relayer-conditions/relayer-value-deviation-condition.ts
> +  const adapterContract = await deployMockAdapter(undefined, [
Same

2023-10-05 07:57 UTC, koonopek commented on packages/integration/src/relayer-conditions/simple-price-propagation-classic.ts
> +  await verifyPricesOnChain(adapterContract, priceFeedContract, {
We are breaking the rule, that one test, tests only one thing.
Also name of the test doesnt say anything about that it is also testing something else then only simple-rpice-rpopagation

2023-10-05 07:57 UTC, koonopek commented on packages/integration/relayerManifestSample.json
> +    "deviationPercentage": 0.1,
Okey, I see now why we need inital prices, every where, however this changed how tests were behaving because most of the tests expected that this is set to 0. And for example now tests which were testing cron conditions or time condtion can be giving false positvies (passing because of value deviation, where time or cron could stop working)

2023-10-05 07:57 UTC, koonopek commented on packages/integration/relayerManifestSample.json
> +    "deviationPercentage": 0.1,
You can just pass conditions like this in `propagation-classic` instead of editing it globally
```
  startRelayer(relayerInstance, {
    cacheServiceInstances: [cacheLayerInstance],
    adapterContractAddress,
    intervalInMs: 5_000,
    updateTriggers: {
      timeSinceLastUpdateInMilliseconds: 60_000,
      deviationPercentage: 10,
    },
    isFallback: false,
  });
```

2023-10-05 09:05 UTC, cehali commented on packages/integration/src/framework/relayer-manager.ts
> +  initialPricesCacheInstances?: CacheLayerInstance[]
I agree, we could use `updateValuesInAdapterContract` as separate function used after deploying mock adapter

2023-10-05 09:12 UTC, cehali commented on packages/integration/relayerManifestSample.json
> +    "deviationPercentage": 0.1,
I started to wonder if we have a check for `deviationPercentage` equal to 0. I see something like that: 
`js 
const shouldUpdatePrices = maxDeviation >= minDeviationPercentage!;
`
Does this mean that we upload every time the relayer runs its iteration?

2023-10-05 09:39 UTC, rpiszczatowski commented on packages/integration/src/framework/relayer-manager.ts
> +  initialPricesCacheInstances?: CacheLayerInstance[]
I thought about the proposed solution. I decided to do what I did because it is actually obligatory to set initial prices whenever we have deviation conditions defined (which is currently 6/8 uses).
I'll create a separate method with a nicer interface that will combine deploying with setting initial prices.

2023-10-05 09:42 UTC, rpiszczatowski commented on packages/integration/relayerManifestSample.json
> +    "deviationPercentage": 0.1,
Understood. I'll revert globally enabling deviation conditions and stick to setting it only when required.

2023-10-05 10:12 UTC, rpiszczatowski commented on packages/integration/src/relayer-conditions/simple-price-propagation-classic.ts
> +  await verifyPricesOnChain(adapterContract, priceFeedContract, {
I'll rename the test as simple price propagation was the initial example test. Now, its functionality is being tested along the way by all classic tests.

2023-10-06 08:43 UTC, koonopek commented on .github/workflows/monorepo-integration-tests.yml
> +      command: yarn ts-node src/relayer-conditions/relayer-not-all-prices-change.ts
I think that it should be relayer-not-all-nodes-deviates or something about that, this test is not testing if one price deviates then the other should be updated too

2023-10-06 08:45 UTC, koonopek commented on packages/integration/relayerManifestSample.json
> +    "deviationPercentage": 0.1,
I think it is still set globally, at least github is saying so:
<img width="820" alt="image" src="https://github.com/redstone-finance/redstone-oracles-monorepo/assets/24699136/60af51c0-7a79-48e9-9a4f-777d35656c59">
I can't diff from my last review cause you forced pushed and it shows, changes from other commits too

2023-10-06 10:42 UTC, rpiszczatowski commented on packages/integration/relayerManifestSample.json
> +    "deviationPercentage": 0.1,
I think you look at the wrong version. I've reverted the original change and only specified the deviation trigger in one relevant test.

Also, I force-pushed because I had conflicts and I really don't like merges :)

2023-10-06 10:47 UTC, rpiszczatowski commented on packages/integration/relayerManifestSample.json
> +    "deviationPercentage": 0.1,
> I started to wonder if we have a check for `deviationPercentage` equal to 0. I see something like that:
> 
> ```js
> const shouldUpdatePrices = maxDeviation >= minDeviationPercentage!;
> ```
> 
> Does this mean that we upload every time the relayer runs its iteration?

I think we handle it properly. While reading the manifest file we have this code:
```
  if (deviationPercentage) {
    updateConditions.push("value-deviation");
  }
```
And then we only check conditions contained in the `updateConditions` list.

2023-10-06 12:16 UTC, koonopek commented on packages/sdk/src/index.ts
> -    throw new Error(
Weird wasn't it introduced lately by you?

2023-10-06 12:58 UTC, merged