chore: restore web3FunctionLogs entries for gelato
redstone-finance/redstone-oracles-monorepo pull request #1201
Opened 2023-10-04 14:07 UTC by Lukasz2891

2023-10-04 17:16 UTC, rpiszczatowski submitted a review, later dismissed

2023-10-05 09:16 UTC, cehali approved these changes

2023-10-05 19:15 UTC, koonopek requested changes

2023-10-05 19:15 UTC, koonopek commented on packages/sdk/src/index.ts
> +    console.error(errMessage); // Do not remove - to have the full message visible as the Gelato web3FunctionLogs log entry.
putting console log in sdk?

2023-10-05 19:16 UTC, koonopek commented on packages/sdk/src/index.ts
> +    console.error(errMessage); // Do not remove - to have the full message visible as the Gelato web3FunctionLogs log entry.
sdk is meant to be reusable

2023-10-06 08:38 UTC, Lukasz2891 commented on packages/sdk/src/index.ts
> +    console.error(errMessage); // Do not remove - to have the full message visible as the Gelato web3FunctionLogs log entry.
agree fully - on the other hand, putting error message to the output doesn't seem to be a misuse of the sdk's hermetization :)

2023-10-06 08:49 UTC, koonopek approved these changes

2023-10-06 10:35 UTC, rpiszczatowski approved these changes

2023-10-06 12:14 UTC, koonopek approved these changes

2023-10-06 13:26 UTC, merged