feat: add CoinMarketCap fetcher
redstone-finance/redstone-oracles-monorepo pull request #124
Opened 2022-11-10 15:32 UTC by cehali

2022-11-11 13:26 UTC, hatskier requested changes

2022-11-11 13:26 UTC, hatskier commented on packages/oracle-node/src/fetchers/coinmarketcap/CoinMarketCapFetcher.ts
> +  "https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?id=";
Let's have a pure URL here: https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest

2022-11-11 13:26 UTC, hatskier commented on packages/oracle-node/src/fetchers/coinmarketcap/CoinMarketCapFetcher.ts
> +    const response = await axios.get(urlWithIDs, {
Let's specify ids here using axios request params
```js
const response = await axios.get(urlWithIDs, {
    params: {
       id: ids.join(","),
    },
    headers: {...
});
```

2022-11-11 13:26 UTC, hatskier commented on packages/oracle-node/src/fetchers/coinmarketcap/CoinMarketCapFetcher.ts
> +    const urlWithIDs = `${url}${ids.join(",")}`;
It looks too magical 😄

2022-11-21 17:18 UTC, hatskier requested changes

2022-11-21 17:18 UTC, hatskier commented on packages/oracle-node/src/fetchers/coinmarketcap/CoinMarketCapFetcher.ts
> +      const price = tokenData[id].quote.USD.price;
What do you think about adding try..catch block here? Or just adding `?` operators (smth like `tokenData[id]?.quote?.USD?.price`) to not throw an exception for the whole fetcher when only one symbols is not included in the response

2022-11-21 17:18 UTC, hatskier commented on packages/oracle-node/src/fetchers/coinmarketcap/example-response.json
> +}
How has the packages/oracle-node/src/fetchers/coinmarketcap/symbol-to-id.json file was generated? It is very big and there are no scripts for its generation in this PR

2022-11-22 08:02 UTC, cehali commented on packages/oracle-node/src/fetchers/coinmarketcap/CoinMarketCapFetcher.ts
> +      const price = tokenData[id].quote.USD.price;
Added handling for this case

2022-11-22 15:12 UTC, hatskier approved these changes

2022-11-22 15:12 UTC, hatskier commented on packages/oracle-node/src/fetchers/coinmarketcap/CoinMarketCapFetcher.ts
> +    const pricesObj: { [symbol: string]: number } = {};
Can you replace `symbol` with `id` here?

2022-11-23 10:04 UTC, merged