feat: add handling exceptions
redstone-finance/redstone-oracles-monorepo pull request #157
Opened 2022-11-25 14:01 UTC by cehali

2022-11-25 14:02 UTC, cehali commented
Test `beforeExit` is probably impossible right now: https://github.com/facebook/jest/issues/10927

2022-11-25 21:06 UTC, hatskier requested changes

2022-11-25 21:06 UTC, hatskier commented on packages/oracle-node/src/utils/handle-exceptions.ts
> +export const handleExceptions = async (
Can you move it to some common module in monorepo and also reuse in the cache service code?

2022-11-25 21:06 UTC, hatskier commented on packages/oracle-node/src/utils/handle-exceptions.ts
> +export const handleExceptions = async (
Also, I am not sure we should run Promises again (it can be even quite dangerous), the whole point of this task was just not to break the whole process execution :)

2022-12-15 07:52 UTC, cehali commented
Closing for now, will come back later to this

2022-12-15 07:52 UTC, closed without merging