* feat: add dia-fetcher
redstone-finance/redstone-oracles-monorepo pull request #176
Opened 2022-12-02 14:05 UTC by Lukasz2891

2022-12-02 16:18 UTC, hatskier requested changes

2022-12-02 16:18 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/DiaFetcher.ts
> +  private async quotationResponse(id: string): Promise<any> {
Please use the verbs for the function names (e.g. `getQuotationResponse` instead of `quotationResponse`)

2022-12-02 16:18 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/DiaFetcher.ts
> +    return await Promise.all(
I would use `Promise.allSettled` instead of `Promise.all` to not throw exception for all symbols if only a subset of requests fails

2022-12-02 16:18 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/dia-quotation-AAVE.json
> +{
Can you move data from `dia-quotation-XXX.json` to `example-response.json` to be consistent with other fetchers?

2022-12-02 16:18 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/dia-quotation-XX11.json
> +{"errorcode":404,"errormessage":"no quotation available"}
Newline symbol is missing

2022-12-02 16:18 UTC, hatskier commented on packages/oracle-node/test/fetchers/dia.spec.ts
> +    tokens.forEach(token => mockFetcherResponseOnce(exampleResponsePathFormat.replace("{id}", token)));
I would create a separate test for each token. In general, please try to use more standard `for` loops instead of `forEach` to be consistent with the rest of the oracle-node code

2022-12-02 16:47 UTC, Lukasz2891 commented on packages/oracle-node/test/fetchers/dia.spec.ts
> +    tokens.forEach(token => mockFetcherResponseOnce(exampleResponsePathFormat.replace("{id}", token)));
But the single-token invocation never happens :)

2022-12-03 12:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/DiaFetcher.ts
> +      const quotation = response.value.data as Quotation;
I think reading `data` prop from the `response.value` will fail in the case when response.value is undefined (e.g. when respone.status is "rejected")

2022-12-03 12:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/DiaFetcher.ts
> +      if (quotation == undefined) {
It's a better practice to use `===` instead of `==` if you want to compare with exact value (without type conversion) https://stackoverflow.com/a/359509/12205723

2022-12-03 12:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/DiaFetcher.ts
> +        continue;
What do you think about simplifying this code to smth like?

```js
for (const response of responses) {
  if (quotation !== undefined) {
    result[quotation.Symbol] = quotation.Price;
  }
}
```

2022-12-03 12:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/example-response-AAVE.json
> +{
In future we'll add much more symbols to the DIA fetcher, so let's prevent too many mixed files in the dia folder. I see 2 options how to achieve this:
1. Create a folder named `example-response` and put AAVE.json, ETH.json, ... files there
2. Create a single file example-response.json with the symbol->response mapping, like
```js
{
  "AAVE": { "Symbol": "AAVE", "Name": "Aave Token", .... },
  "ETH": { ... },
  ...
}
```

2022-12-03 12:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/example-response-XX11.json
> +{"errorcode":404,"errormessage":"no quotation available"}
Can you please doublecheck if you also have a JSON formatting configured?

2022-12-03 12:40 UTC, hatskier commented on packages/oracle-node/test/fetchers/_helpers.ts
> +export function mockFetcherResponseOnce(pathToResponseFile: string) {
Just curious, what was the problem with the `mockFetcherResponse` function?

2022-12-03 12:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/DiaFetcher.ts
> +    let result: PricesObj = {};
This `let` can be changed to `const`

2022-12-08 12:41 UTC, hatskier commented on packages/oracle-node/src/fetchers/dia/DiaFetcher.ts
> +        continue;
Let's communicate here please ;)

2022-12-08 12:43 UTC, hatskier commented on packages/oracle-node/test/fetchers/_helpers.ts
> +export function mockFetcherResponseOnce(pathToResponseFile: string) {
Yep, let's do it in a separate task, but later. Can you please create an issue for it on GitHub?

2022-12-08 12:43 UTC, hatskier approved these changes

2022-12-08 13:55 UTC, merged