[WiP] feat: Implement payload endpoint
redstone-finance/redstone-oracles-monorepo pull request #189
Opened 2022-12-07 15:14 UTC by Lukasz2891

2022-12-07 15:15 UTC, Lukasz2891 commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  private makePayload(
Static? Utils?

2022-12-09 13:40 UTC, cehali commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +        RedstonePayloadFactory.makePayload(cachedDataPackagesResponse).toBytes()
Using `await` and `then` is not good practice. It is a mix of two different principles. In most cases it is better to use `await`

` js
    const cachedDataPackagesResponse = await this.getDataPackages(query)
      readableStream(RedstonePayloadFactory.makePayload(cachedDataPackagesResponse).toBytes()
      ).pipe(res);
    });
`

2022-12-09 13:44 UTC, cehali commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +      ).pipe(res);
I don't think we need to use `pipe` here. We can just return the result of `toBytes()` function

2022-12-09 13:48 UTC, cehali commented on packages/cache-service/src/utils/RedstonePayloadFactory.ts
> +export class RedstonePayloadFactory {
It doesn't need to be a class if it has only one static function. It could be folder with one or more exported functions

2022-12-09 13:52 UTC, cehali commented on packages/cache-service/src/utils/RedstonePayloadFactory.ts
> +    }
```js
const cachedDataPackages = Object.values(cachedDataPackagesResponse).flatMap(packages => packages);
```

2022-12-09 13:54 UTC, cehali commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +      readableStream(
Why you want to use stream here?

2022-12-09 13:57 UTC, cehali commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    expect(testResponse.body.length).toBe(1662);
Please move those numbers to separate variables with proper names.

2022-12-09 13:58 UTC, cehali commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    expect(payload.signedDataPackages.length).toBe(8); // 4*2
Maybe add a test that will check some value in the response, not only lengths?

2022-12-09 13:59 UTC, cehali requested changes
Details in comments

2022-12-10 08:16 UTC, Lukasz2891 commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +      ).pipe(res);
It doesn’t work. The response is automaticaly transformed to a json except StreamableFile. I’ve spent on it some time. The other way is to use custom Intercepror but that solutions seems to be simplier.

2022-12-10 08:20 UTC, Lukasz2891 commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    expect(payload.signedDataPackages.length).toBe(8); // 4*2
It’d need to have the mocks upgraded. In that case all of mocks consist of the same data, so we can check it, but it doesn’t have a value. There is one check below (with the length of datapackages field). The most important thing is to have a parsable stream returned, for me.

2022-12-10 08:49 UTC, Lukasz2891 commented on packages/cache-service/src/utils/RedstonePayloadFactory.ts
> +    }
I love of using high level functions but I though we don’t want ;)

2022-12-12 10:21 UTC, cehali commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +      ).pipe(res);
Ok, I see. I have to talk with Alex about it, what are the exceptions regarding this. Maybe we could use the `toBytesHex` function on the `makePayload` result and send JSON with a string value as a result.

2022-12-12 13:39 UTC, cehali commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +      ).pipe(res);
I talked about it with Alex and we could do both. Either create a separate endpoint or the same with some parameter that distinguishes if the return value should be a string with the result of `toBytesHex` function or `readableStream` with the result of the `toBytes` function.

2022-12-12 15:18 UTC, Lukasz2891 commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +      ).pipe(res);
A separate endpoint will be better because of different content-types. But the naming... Do you accept ```payload``` (with bytes/```octet-stream```) and ```payloadHex``` (with hex/```text/html```) or you prefer ```payloadBytes``` instead?

2022-12-13 09:45 UTC, cehali commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  @Get("payloadHex")
I think for route name better would be kebab-case: `payload-hex`

2022-12-13 09:46 UTC, cehali approved these changes
Approved with 2 minor changes

2022-12-14 00:11 UTC, hatskier requested changes

2022-12-14 00:11 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  async getPayloadHex(@Query() query: GetLatestDataPackagesQuery) {
What do you think about using query param to specify the expected format of the payload (e.g. `?format=hex` or `?format=raw`)?

2022-12-14 00:11 UTC, hatskier commented on packages/cache-service/src/utils/make-redstone-payload.ts
> +export function makePayload(
I would move this function to the redstone-sdk package

2022-12-14 00:11 UTC, hatskier commented on packages/cache-service/src/utils/streams.ts
> +  stream.push(array);
Can you please add a comment about what happening here? It's not clear at first sight?

2022-12-14 00:11 UTC, hatskier commented on packages/cache-service/src/utils/make-redstone-payload.ts
> +export function makePayload(
Probably there is already a similar one there, so you can refactor it using the fancy `flatMap` method :)

2022-12-14 00:11 UTC, hatskier commented on packages/cache-service/src/utils/make-redstone-payload.ts
> +export function makePayload(
Actually, what do you think about using the `flat` method instead? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

2022-12-14 07:50 UTC, Lukasz2891 commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  async getPayloadHex(@Query() query: GetLatestDataPackagesQuery) {
I’ve written it above - the reason were different response types. Less of ’’’ifs’’’

2022-12-15 01:47 UTC, hatskier requested changes

2022-12-15 01:47 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  private sendResponse(
Let's change the name of this function to smth like `sendPayloadResponse`

2022-12-15 01:47 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +export enum ResponseFormat {
Let's use `type ResponseFormat = "raw" | "hex"` instead

2022-12-15 01:47 UTC, hatskier commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    expect(payload.signedDataPackages.length).toBe(8); // 4*2
Frankly, I see a value in checking the response value, as it will allow us to catch potential problems with payload generation

2022-12-15 01:47 UTC, hatskier commented on packages/cache-service/src/utils/make-redstone-payload.ts
> +export function makePayload(
Ok

2022-12-15 09:17 UTC, Lukasz2891 commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  private sendResponse(
That's more ```sendStreamableResponse``` but I don't know if we'd like to reuse it.

2022-12-15 09:21 UTC, Lukasz2891 commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +export enum ResponseFormat {
but then we cannot use ResponseFormat.raw but we need to write just "raw" :)

2022-12-15 14:19 UTC, hatskier approved these changes

2022-12-15 14:19 UTC, merged