Band oracle fetcher damian
redstone-finance/redstone-oracles-monorepo pull request #195
Opened 2022-12-08 13:57 UTC by wuluxBOSS

Added band oracle fetcher.
It was last (3rd) point from my 1st task.
Waiting for review from hatskier.

2022-12-09 14:02 UTC, cehali commented on packages/oracle-node/src/fetchers/band/BandFetcher.ts
> +    );
You can build this request a little bit different

```js
    const response = await axios.get(BAND_ORACLE_API_URL, {
      params: {
        symbols: requestCurriences,
      },
    });
    return response.data
```

2022-12-09 14:03 UTC, cehali commented on packages/oracle-node/src/fetchers/band/BandFetcher.ts
> +    const symbolToPrice: { [symbol: string]: number } = {};
Rename to `priceObj` just to be consistent with other fetchers 😄

2022-12-09 14:03 UTC, cehali commented on packages/oracle-node/test/fetchers/band.spec.ts
> +    // given
Please remove those comments, they are obsolete now 😄

2022-12-09 14:04 UTC, cehali requested changes
Details in comments

2022-12-12 02:34 UTC, hatskier requested changes

2022-12-12 02:34 UTC, hatskier commented on packages/oracle-node/src/fetchers/band/BandFetcher.ts
> +    const pricesObj: { [symbol: string]: number } = {};
What do you think about using `PricesObj` type here?

2022-12-12 02:34 UTC, hatskier commented on packages/oracle-node/src/fetchers/band/BandFetcher.ts
> +    super("BandFetcher");
Please use `super("band");` to be consistent with other fetchers

2022-12-12 10:27 UTC, cehali commented on packages/oracle-node/src/fetchers/band/BandFetcher.ts
> +    const pricesObj: { [symbol: string]: number } = {};
I believe Alex meant the `PricesObj` interface which could be used instead of `{ [symbol: string]: number }`

2022-12-12 16:51 UTC, hatskier commented on packages/oracle-node/src/fetchers/band/BandFetcher.ts
> +    const pricesObj: { [symbol: string]: number } = {};
Yep, I mean smth like `const pricesObj: PricesObj = {};`

2022-12-13 23:57 UTC, hatskier commented on packages/oracle-node/manifests/single-source/band.json
> +  "defaultSource": ["band_oracle_fetcher"],
Have you tested the node with this manifest? ;)

2022-12-15 01:51 UTC, hatskier approved these changes

2022-12-15 07:54 UTC, cehali commented
Please resolve conflicts and squash and merge

2022-12-15 07:54 UTC, cehali approved these changes

2022-12-15 12:23 UTC, merged