chore: Replace Promise.all with Promise.allSettled by using MultiRequ…
redstone-finance/redstone-oracles-monorepo pull request #197
Opened 2022-12-08 16:50 UTC by Lukasz2891

…estFetcher

2022-12-08 16:53 UTC, Lukasz2891 commented
I'll create a task for implementing unit tests for particular parts of the MultiRequestFetcher and their implementations.

2022-12-14 00:25 UTC, hatskier requested changes

2022-12-14 00:25 UTC, hatskier commented on packages/oracle-node/src/fetchers/MultiRequestFetcher.ts
> +  protected abstract getRequestFactory(): RequestFactory;
What is the added value to have the factory and the processor instance here comparing to just having 2 new abstract functions in this class called `makeRequest` and `processResponse`/

2022-12-14 00:25 UTC, hatskier commented on packages/oracle-node/src/fetchers/MultiRequestFetcher.ts
> +  protected abstract getRequestFactory(): RequestFactory;
I like the idea of this refactoring, but let's please try to not create additional abstractions if they are not needed

2022-12-14 00:25 UTC, hatskier commented on packages/oracle-node/src/fetchers/MultiRequestFetcher.ts
> +        response.value.data === undefined
Are you sure that each redsponse.value should have the `data` field? It looks a bit axios-specific

2022-12-14 00:25 UTC, hatskier commented on packages/oracle-node/src/fetchers/MultiRequestFetcher.ts
> +import { BaseFetcher } from "./BaseFetcher";
Just another question. Have you tested this new code version with the main manifest? If not, ca you please doublecheck if everything works as expected before the merge?

2022-12-15 09:45 UTC, Lukasz2891 commented on packages/oracle-node/src/fetchers/MultiRequestFetcher.ts
> +  protected abstract getRequestFactory(): RequestFactory;
sometimes I need more variables to create the request. The interfaces in a great way hide that. I like my solution :(

2022-12-15 09:46 UTC, Lukasz2891 commented on packages/oracle-node/src/fetchers/MultiRequestFetcher.ts
> +import { BaseFetcher } from "./BaseFetcher";
Why it couldn't work? Could you help me in that?

2022-12-15 13:55 UTC, Lukasz2891 commented on packages/oracle-node/src/fetchers/MultiRequestFetcher.ts
> +import { BaseFetcher } from "./BaseFetcher";
Now it seems to work properly.

2022-12-15 14:12 UTC, hatskier approved these changes

2022-12-20 08:03 UTC, merged