feat: replace redstone-api with local DB
redstone-finance/redstone-oracles-monorepo pull request #202
Opened 2022-12-09 13:14 UTC by cehali

2022-12-14 00:56 UTC, hatskier requested changes

2022-12-14 00:56 UTC, hatskier commented on packages/oracle-node/manifests/dev/on-demand.json
> +{
Why have you added this manifest?

2022-12-14 00:56 UTC, hatskier commented on packages/oracle-node/src/NodeRunner.ts
> -    await localDB.savePrices(prices);
Frankly, I liked the previous version more, as it was more readable in terms of what happens with prices (liek where they are saved)

2022-12-14 00:56 UTC, hatskier commented on packages/oracle-node/src/db/local-db/index.ts
> +export const setupLocalDb = () => {
Can you add a comment that this function should be called once in order to make this module usable?

2022-12-14 07:40 UTC, cehali commented on packages/oracle-node/manifests/dev/on-demand.json
> +{
Because we fetched the ETH price from `redstone-api` before in order to calculate the sum of transactions received from Coinbase in USD. If we want to get rid of `redstone-api` we need to fetch ETH in an "on-demand" type of node ourselves and store it in the local db.

2022-12-15 01:12 UTC, hatskier commented on packages/oracle-node/manifests/dev/on-demand.json
> +{
Makes sense

2022-12-15 01:13 UTC, hatskier approved these changes

2022-12-15 07:51 UTC, merged