feat: streamr listener allowed evm addresses config
redstone-finance/redstone-oracles-monorepo pull request #214
Opened 2022-12-13 17:25 UTC by Lukasz2891

2022-12-14 00:35 UTC, hatskier requested changes

2022-12-14 00:35 UTC, hatskier commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +  private readonly allowedNodeEnvAddresses: string[];
What is the added value of this private field if we can get this value from the config directly?

2022-12-14 00:35 UTC, hatskier commented on packages/cache-service/.env.example
> +ALLOWED_STREAMR_NODE_EVM_ADDRESSES=
We would like to filter based on dataServiceIds, not on the nodes, to make the configuration simpler. There is no value in listening on only a subset of nodes from a data service

2022-12-14 00:35 UTC, hatskier commented on packages/cache-service/src/config.ts
> +if (config.enableStreamrListening) {
It looks a bit inconsistent to me, that the `allowedStreamrNodeEnvAddresses` field is required in the `CacheServiceConfigRequiredFields` type, but we set it only if  `config.enableStreamrListening` is `true`. I would remove this condition and would replace the code below with something like:
```js
const envValue = getEnv("ALLOWED_STREAMR_NODE_EVM_ADDRESSES", false) || "[]";
config.allowedStreamrNodeEnvAddresses = JSON.parse(envValue);
```

2022-12-14 00:35 UTC, hatskier commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +    let nodeEvmAddresses = Object.values(oracleRegistryState.nodes).map(
Please change this `let` to `const`

2022-12-14 00:35 UTC, hatskier commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +    return this.allowedNodeEnvAddresses.map((obj) => obj.toLowerCase());
Why `obj` if it's a string?

2022-12-14 00:35 UTC, hatskier commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +    nodeEvmAddresses = nodeEvmAddresses.filter((obj) =>
Why `obj`?

2022-12-14 07:40 UTC, Lukasz2891 commented on packages/cache-service/.env.example
> +ALLOWED_STREAMR_NODE_EVM_ADDRESSES=
I don’t like to have mixed external and internal dependencies outside the Constructor. Generally, I was refectoring in my life a lot lot of classes and having it mixed in diffrerent parts of code leads to something not nice. 

But also I maybe don’t feel the importance of performance and memory efficiency in js with so small amount of data.

2022-12-14 07:41 UTC, Lukasz2891 commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +  private readonly allowedNodeEnvAddresses: string[];
I don’t like to have mixed external and internal dependencies outside the Constructor. Generally, I was refectoring in my life a lot lot of classes and having it mixed in diffrerent parts of code leads to something not nice.

But also I maybe don’t feel the importance of performance and memory efficiency in js with so small amount of data.

2022-12-14 10:07 UTC, Lukasz2891 commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +    let nodeEvmAddresses = Object.values(oracleRegistryState.nodes).map(
it's modified (filtered) below

2022-12-14 11:31 UTC, Lukasz2891 commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +import { RedstoneOraclesState } from "redstone-oracles-smartweave-contracts/dist/src/contracts/redstone-oracle-registry/types";
hmmm ;/

2022-12-15 01:01 UTC, hatskier requested changes

2022-12-15 09:09 UTC, Lukasz2891 commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +    if (allowedDataServiceIds.length == 0) {
still forgetting about it, especially for numbers, sorry, that's the last time ;p ;)

2022-12-15 09:12 UTC, Lukasz2891 commented on packages/cache-service/src/streamr-listener/streamr-listener.service.ts
> +  getAllowedDataServiceIds(): string[] {
the body of the function -> right
But I wanted to have a function to have it mockable in tests. I can't do it for a variable - also changing values in process env didn't work. Can we leave the function returning only ```config.allowedStreamrDataServiceIds```?
Or do you have another tip for mocking the config here, working for tests separately?

2022-12-15 14:24 UTC, hatskier approved these changes

2022-12-15 14:37 UTC, merged