Node schedule based scheduling
redstone-finance/redstone-oracles-monorepo pull request #227
Opened 2022-12-18 15:09 UTC by rucinpk

2022-12-20 11:49 UTC, cehali commented on packages/oracle-node/src/utils/timestamps.ts
> +  return Math.floor(timestamp / 10000) * 10000;
Two questions here. Why do we want to round the timestamp to the nearest 10 seconds? Shouldn't it be somehow connected to the interval in the manifest?
Why should we round with `floor` and not `ceil` or `round`?

2022-12-20 12:00 UTC, rucinpk commented on packages/oracle-node/src/utils/timestamps.ts
> +  return Math.floor(timestamp / 10000) * 10000;
1. We want to make Arweave querying easier. I think it is not connected to the interval in the manifest. 
2. It could be either floor or ceil. I don't see advantages of using one instead of another.

2022-12-20 16:41 UTC, hatskier requested changes

2022-12-20 16:41 UTC, hatskier commented on packages/oracle-node/src/utils/timestamps.ts
> +  return Math.floor(timestamp / 10000) * 10000;
2. It should be floor. Rounding is used here to handle the potential delay between iteration starting and timestamp measurement (e.g. we can start at timestamp X, but at the moment of evaluating `Date.now()` it can become `X + 1` or `X + 2`

2022-12-20 16:41 UTC, hatskier commented on packages/oracle-node/src/types.ts
> +  roundedTimestamp: number;
We don't need this field (`roundedTimestamp`)

2022-12-20 16:41 UTC, hatskier commented on packages/oracle-node/src/NodeRunnerOld.ts
>      const fetchTimestamp = Date.now();
Let's please use `const fetchTimestamp = roundTimestamp(Date.now());`

2022-12-20 16:41 UTC, hatskier commented on packages/oracle-node/src/NodeRunnerOld.ts
>      const fetchTimestamp = Date.now();
We don't need to have fetchTimestamp and roundedTimestamp separately

2022-12-20 16:41 UTC, hatskier commented on packages/oracle-node/src/utils/timestamps.ts
> +  return Math.floor(timestamp / 10000) * 10000;
1. IMO rounding to the nearest 1 second (not 10 seconds) should be enough

2022-12-21 11:11 UTC, hatskier requested changes

2023-01-02 23:37 UTC, hatskier approved these changes

2023-01-03 13:47 UTC, merged