feat: prepare single button deployment on digitalocean
redstone-finance/redstone-oracles-monorepo pull request #260
Opened 2022-12-28 08:48 UTC by Lukasz2891

2022-12-29 09:01 UTC, cehali commented on .do/app/README.md
> +Select the Environment Variables tab on the left pane.
`pane` -> `panel`

2022-12-29 09:02 UTC, cehali commented on .do/app/README.md
> +Then into the MONGO_DB-field's value put the database connection string you've copied from your MongoDB cluster.
Maybe `MONGO_DB-field's` -> `MONGO_DB_URL field`

2022-12-29 09:06 UTC, cehali commented on .do/mongodb/README.md
> +The connection string contains the placeholder value . If you don’t know the password for your cluster’s admin user, you can reset the password in the cluster’s Users and Databases tab.
`value .` -> `value.`

2022-12-29 09:10 UTC, cehali commented on packages/cache-service/DO.Dockerfile
> +    ALLOWED_STREAMR_DATA_SERVICE_IDS=${ALLOWED_STREAMR_DATA_SERVICE_IDS}
Maybe it will work with each value as a separate `ENV` variable
```
ENV ENABLE_STREAMR_LISTENING=${ENABLE_STREAMR_LISTENING}
ENV ENABLE_DIRECT_POSTING_ROUTES=${ENABLE_DIRECT_POSTING_ROUTES}
ENV API_KEY_FOR_ACCESS_TO_ADMIN_ROUTES=${API_KEY_FOR_ACCESS_TO_ADMIN_ROUTES}
ENV MONGO_DB_URL=${MONGO_DB_URL}
ENV ALLOWED_STREAMR_DATA_SERVICE_IDS=${ALLOWED_STREAMR_DATA_SERVICE_IDS}
```

2022-12-29 09:11 UTC, cehali commented on packages/cache-service/README.md
> +You need to have the MongoDB setup performed as a clusted or as an external service. [Check here](https://github.com/redstone-finance/redstone-oracles-monorepo/tree/main/.do/mongodb/) to see how to s
`clusted` -> `cluster`

2022-12-29 09:12 UTC, cehali commented on packages/cache-service/README.md
> +* [Here](https://github.com/redstone-finance/redstone-oracles-monorepo/tree/main/.do/app/) you can find a small tutorial how to do it.
`tutorial` -> `tutorial on`

2022-12-29 09:14 UTC, cehali requested changes
I think we can change the folder name `.do`  to `.digital-ocean` in order to make it more readable.
The same situation with the name of the file `DO.Dockerfile`.

2022-12-29 11:49 UTC, Lukasz2891 commented on .do/app/README.md
> +Select the Environment Variables tab on the left pane.
https://www.computerhope.com/jargon/p/pane.htm

2022-12-29 11:58 UTC, Lukasz2891 commented
> I think we can change the folder name `.do` to `.digital-ocean` in order to make it more readable. The same situation with the name of the file `DO.Dockerfile`.

Digital Ocean require to have the file ```deploy.template.yaml``` in the ```.do``` directory but other files can be moved. I'll try to move the whole directory to the cache-service package.

2022-12-29 12:09 UTC, Lukasz2891 commented
> 

![Screenshot 2022-12-29 at 13 07 55](https://user-images.githubusercontent.com/7481970/209949198-13755b17-ba9d-48ea-b407-e566f4620c16.png)

2022-12-30 12:38 UTC, cehali approved these changes

2023-01-02 09:31 UTC, merged