feat: kaiko fetcher
redstone-finance/redstone-oracles-monorepo pull request #268
Opened 2022-12-30 12:09 UTC by rucinpk

2022-12-30 13:00 UTC, cehali commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +const axios = require("axios");
Always use `import` if possible:

```js
import axios from "axios";
```

2022-12-30 13:12 UTC, cehali commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +    interval: "1m",
I am wondering if interval `1m` is not providing us with old data. I am afraid that it could give us data with a granularity of 1 minute and with our node interval of 10 seconds this would lead to stale prices. Could you double-check this? Maybe we need to pass here interval `1s` in order to get the freshest data

2022-12-30 13:13 UTC, cehali commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +  },
Please split it into two separate objects. One would be `KAIKO_REQUEST_HEADERS` and other would be `KAIKO_REQUEST_PARAMS`

2022-12-30 13:18 UTC, cehali commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +      `${KAIKO_PRICES_URL}/${id.toLowerCase()}/usd`,
Please put the URL string building in a separate variable, just for better readability.

2022-12-30 13:20 UTC, cehali commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +    pricesObj[data.query.base_asset.toUpperCase()] = Number(data.data[0].price);
Please move `data.query.base_asset.toUpperCase()` and `Number(data.data[0].price)` to separate variables with descriptive names

2022-12-30 13:25 UTC, cehali commented on packages/oracle-node/src/fetchers/kaiko/example-responses/AAVE.json
> +{
If those response files don't have significant differences (I don't see them at first sight) please leave only one of them.

2022-12-30 14:36 UTC, cehali commented on packages/oracle-node/test/fetchers/kaiko.spec.ts
> +    // Given
Those comments are unnecessary

2022-12-30 14:42 UTC, cehali commented on packages/oracle-node/test/fetchers/kaiko.spec.ts
> +  "../../src/fetchers/kaiko/example-responses/{id}.json";
I would do this differently. Leave one file with an example response, it is good to know how the response looks like. In `mock` function, you can use `mockFetcherResponseWithFunction` to which you can pass the function which returns mocked response (only necessary fields) for the proper token.

2022-12-30 14:42 UTC, cehali requested changes
Details in comments

2023-01-02 09:00 UTC, rucinpk commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +    interval: "1m",
1s is too small interval for kaiko - oftentimes if I pass 1s to API it doesn't give any results

2023-01-02 09:19 UTC, rucinpk commented on packages/oracle-node/test/fetchers/kaiko.spec.ts
> +  "../../src/fetchers/kaiko/example-responses/{id}.json";
I think the current solution is cleaner - we separate data from code. With solution you mention we would hardcode every response for all tokens.

2023-01-02 23:24 UTC, hatskier commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +export class KaikoFetcher extends MultiRequestFetcher {
Have you checked if it's possible to request multiple assets in a single API request?

2023-01-03 07:32 UTC, cehali commented on packages/oracle-node/test/fetchers/kaiko.spec.ts
> +  "../../src/fetchers/kaiko/example-responses/{id}.json";
In both solutions, you separate data from code. Also in your solution, you hardcode every response as well. The only difference is that you will have a small file close to the test itself and not files far away from the test.

2023-01-03 13:54 UTC, rucinpk commented on packages/oracle-node/src/fetchers/kaiko/KaikoFetcher.ts
> +export class KaikoFetcher extends MultiRequestFetcher {
Yes - it's not possible to request multiple assets in a single API request with available API versions.

2023-01-03 13:56 UTC, rucinpk commented on packages/oracle-node/test/fetchers/kaiko.spec.ts
> +  "../../src/fetchers/kaiko/example-responses/{id}.json";
I think I don't get this - for now file is data, and with solution you are proposing the code would be data? With `mockFetcherResponseWithFunction` it would require a handler or different `if` for every asset

2023-01-04 09:24 UTC, cehali commented on packages/oracle-node/test/fetchers/kaiko.spec.ts
> +  "../../src/fetchers/kaiko/example-responses/{id}.json";
I meant something like this: https://github.com/redstone-finance/redstone-oracles-monorepo/pull/279

2023-01-04 09:52 UTC, rucinpk commented on packages/oracle-node/test/fetchers/kaiko.spec.ts
> +  "../../src/fetchers/kaiko/example-responses/{id}.json";
refactored

2023-01-04 11:48 UTC, cehali approved these changes

2023-01-04 11:53 UTC, cehali requested changes
One more thing, we need to add manifest and update manifests for tokens which we want to fetch and update manifests for data services

2023-01-04 16:15 UTC, rucinpk commented
Unfortunately - interval for fetching from kaiko needs to be 1m. If interval is set to less than 1 minute then API returns null price oftentimes. We still always get latest value from kaiko even if interval is set to 1m.

2023-01-05 11:24 UTC, cehali approved these changes
LGTM

2023-01-05 13:18 UTC, merged