feat: add min valid sources for single data feed
redstone-finance/redstone-oracles-monorepo pull request #320
Opened 2023-01-16 13:38 UTC by cehali

2023-01-23 13:11 UTC, hatskier commented on packages/oracle-node/src/fetchers/PricesService.ts
> +      (sourcesFetchedCount / allSourcesCount) * 100;
I think this function can fail in manifests with only default sources, because if the division by 0

2023-01-23 13:13 UTC, cehali commented on packages/oracle-node/src/fetchers/PricesService.ts
> +      (sourcesFetchedCount / allSourcesCount) * 100;
<img width="504" alt="image" src="https://user-images.githubusercontent.com/35804520/214048417-37a25499-5370-4373-93d5-1f501efea41f.png">

2023-01-28 21:16 UTC, hatskier requested changes

2023-01-28 21:16 UTC, hatskier commented on packages/oracle-node/tools/manifest/add-parameter-to-all-manifests.ts
> +  const parameter = {};
Can you please add a comment regarding the usage of this script? AFAIU the user should update the `parameter` object before running it

2023-01-28 21:16 UTC, hatskier commented on packages/oracle-node/src/fetchers/PricesService.ts
> +      const requiredSourcesCount = Math.ceil(
I would remove some additional logic for calculating the `requiredSourcesCount` value here. Let's just log valid sources count, and `minValidSourcesPercentage` here

2023-02-04 22:14 UTC, hatskier approved these changes

2023-02-04 22:16 UTC, hatskier approved these changes

2023-02-04 22:16 UTC, hatskier commented on packages/oracle-node/src/manifest/ManifestHelper.ts
> +      manifest?.minValidSourcesPercentage ?? DEFAULT_MIN_VALID_SOURCE_PERCENTAGE
Since we have mechanism of getting default `minValidSourcesPercentage`, maybe we can remove all these changes in manifests?

2023-02-06 08:32 UTC, merged