feat: adjust mongo pipeline query for payload
redstone-finance/redstone-oracles-monorepo pull request #322
Opened 2023-01-18 09:50 UTC by cehali

2023-01-29 21:37 UTC, hatskier requested changes

2023-01-29 21:37 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +    if (!!dataFeeds) {
Can you please reuse the `getAllLatestDataWithCache` function instead of modifying `getAllLatestDataPackagesFromDB`? It will simplify the code and will help to improve DB performance thanks to mem caching

2023-01-30 09:40 UTC, cehali commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +    if (!!dataFeeds) {
Changed

2023-01-30 11:14 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +  private filterDataPackages(
Can we please reuse `parseDataPackagesResponse` from redstone-sdk here?

2023-02-04 23:07 UTC, hatskier approved these changes

2023-02-04 23:08 UTC, merged