feat: added historical prices querying from chainlink
redstone-finance/redstone-oracles-monorepo pull request #332
Opened 2023-01-23 13:43 UTC by rucinpk

2023-01-29 19:36 UTC, hatskier requested changes

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/package.json
> +    "query-historical-prices": "ts-node scripts/query-historical-prices.ts"
Please remove this script, as we have a lot of different scripts in the tools folder and adding shortcuts for all of them here would make the package.json file huge :)

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/scripts/query-historical-prices.ts
> +import { contracts, abi } from "../src/fetchers/chainlink/constants";
Please move this script to the tools folder, you can create a chainlink subfolder inside

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/scripts/query-historical-prices.ts
> +  for (let i = latestPhaseId; i > 0; i--) {
Please name variables using a bit more letters (not just `i`), because it will help with the code readability

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/scripts/query-historical-prices.ts
> +      let promises = range(roundID, roundID + BigInt("100"), BigInt(1)).map(
What do you think about replacing the custom `range` function with a [simple shorter javascript implementation](https://stackoverflow.com/questions/3895478/does-javascript-have-a-method-like-range-to-generate-a-range-within-the-supp) on numbers (instead of BigInts) and converting a number to BigInt later (in the map function param)

Range in javascript with normal numbers

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/scripts/query-historical-prices.ts
> +        (round: any) => contract.getRoundData(round)
Please avoid using `any` types. They devalue our usage of typescript

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/scripts/query-historical-prices.ts
> +            prices.push({
Doesn't it make the result array unsorted? Since promises passed to the Promise.all function may resolve in random order

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/scripts/query-historical-prices.ts
> +  console.log("Saving results to file");
I would reuse functions from [tools/common/fs-utils.ts module](https://github.com/redstone-finance/redstone-oracles-monorepo/blob/f6ebf697d61ae89977ee1f4dc0b29effbed62ea8/packages/oracle-node/tools/common/fs-utils.ts)

2023-01-29 19:36 UTC, hatskier commented on packages/oracle-node/scripts/query-historical-prices.ts
> +  let prices = await getAllPrices(priceFeed, phaseId);
Please use `const` instead of `let`

2023-02-01 20:31 UTC, rucinpk commented on packages/oracle-node/scripts/query-historical-prices.ts
> +            prices.push({
Yes, that array is unsorted, but array can be sorted by timestamp later on.

2023-02-05 02:31 UTC, hatskier requested changes

2023-02-05 02:31 UTC, hatskier commented on packages/oracle-node/tools/chainlink/query-historical-prices.ts
> +  return BigInt(
I would split this into 2 instructions, e.g.
```js
const latestRoundData = await priceFeedContract.latestRoundData();
return BigInt(latestRoundData.roundId.toHexString());
```

2023-02-05 02:31 UTC, hatskier commented on packages/oracle-node/tools/chainlink/query-historical-prices.ts
> +async function query() {
Please add longer names to functions to make it easier to read the code later

2023-02-05 02:31 UTC, hatskier commented on packages/oracle-node/tools/chainlink/query-historical-prices.ts
> +  while (true) {
This function is quite long. Consider splitting it into 2 functions

2023-02-05 02:31 UTC, hatskier commented on packages/oracle-node/tools/chainlink/query-historical-prices.ts
> +        if (numErrors > 10) {
Those numbers (like this 10) are usually created as constants in the beginning of the file and used in the code as constants

2023-02-05 02:31 UTC, hatskier commented on packages/oracle-node/tools/chainlink/query-historical-prices.ts
> +        if (numErrors > 10) {
Also, why 10?

2023-02-06 13:16 UTC, hatskier approved these changes

2023-02-06 22:44 UTC, merged