feat: added balancer fetcher
redstone-finance/redstone-oracles-monorepo pull request #337
Opened 2023-01-26 13:23 UTC by rucinpk

2023-01-26 14:43 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +  async findUnsupportedTokens(ids: string[]) {
There is no need for async here

2023-01-26 14:43 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    if (this.pool === null || this.pool === undefined) {
When can this pool be null or undefined?

2023-01-26 14:43 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    let pool = await balancer.pools.find(this.poolId);
Please use `const` instead of `let`, unless it's required

2023-02-01 20:38 UTC, rucinpk commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    if (this.pool === null || this.pool === undefined) {
Just right after the construction of an object. We can't initialize it in the constructor.

2023-02-04 21:59 UTC, hatskier requested changes

2023-02-04 21:59 UTC, hatskier commented on packages/oracle-node/src/fetchers/BaseFetcher.ts
> +    let response = await this.fetchData(ids, opts, timestamp);
Please remove the `timestamp` argument from the `fetchData` function. Let's specify it in constructor and save in a private variable for HistoricalFetchers

2023-02-04 21:59 UTC, hatskier commented on packages/oracle-node/src/fetchers/BaseFetcher.ts
> +      response = await this.fetchData(ids, opts, Number(timestamp!.toString()));
What is the reason for this strange conversion?

2023-02-04 21:59 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/historical/BalancerFetcherHistorical.ts
> +  protected async calculatePrice(pairedTokenPrice: number): Promise<number> {
IMO `calculatePrice` should not be `async`. It should only contain logic of price calculation based

2023-02-04 21:59 UTC, hatskier commented on packages/oracle-node/src/fetchers/BaseFetcher.ts
>    }
Please remove changes from the BaseFetcher

2023-02-04 21:59 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/historical/BalancerFetcherHistorical.ts
> +  protected async calculatePrice(pairedTokenPrice: number): Promise<number> {
Also, I think you should not override the logic of price calculation in the historical fetcher. You should only override the way the required data is fetched

2023-02-04 21:59 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +  constructor(poolId: string) {
Please rewrite this fetcher so it supports more than one pool. You can take a look at how Uniswap or Sushiswap fetchers are implemented. It will also help to remove unnecessary code of validating supported pairs

2023-02-06 20:34 UTC, rucinpk commented on packages/oracle-node/src/fetchers/balancer/historical/BalancerFetcherHistorical.ts
> +  protected async calculatePrice(pairedTokenPrice: number): Promise<number> {
yes, but for the historical implementation, we did not support some tokens in the past.

2023-02-07 09:21 UTC, cehali commented on packages/oracle-node/src/fetchers/DexFetcher.ts
> +    protected readonly symbolToPairIdObj: SymbolToPairId
What is the reason for the change from protected to private?

2023-02-07 09:50 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    const pricesObj: { [symbol: string]: number } = {};
```js
const pricesObj: PricesObj = {};
```

2023-02-07 09:51 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +  async extractPrices(response: any): Promise<PricesObj> {
Here you know that response would be `spotPrices` with type `SpotPrice[]`. Please change `response` to it.

2023-02-07 09:52 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    return { id: this.getSymbol(pool!), price };
Add if statement `if (pool)`. We don't want to calculate price if pool doesn't exists. Also we don't want to push prices which could be NaN to `spotPrices` array.

2023-02-07 09:53 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +      spotPrices.push({ id, price });
Here you can check if return of `calculatePrice` exists and then push it to  `spotPrices` array.

2023-02-07 09:58 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +  protected balancer: BalancerSDK;
Why all members are protected. Most of the time it could be private which is more strict than protected. You should use protected only when subclass is going to use function or variable.

2023-02-08 21:40 UTC, hatskier requested changes

2023-02-08 21:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +  protected async getPairedTokenPrice() {
This function doesn't need to by async

2023-02-08 21:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    return null;
Let's just throw an error if pool is not found

2023-02-08 21:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +      const priceResult = await this.calculatePrice(pairId, pairedTokenPrice);
Let's not use async calls inside a loop. Execution in a loop causes that requests that can be sent in parallel are executed sequentially. Take a look at the [MultiRequestFetcher.ts](https://github.com/redstone-finance/redstone-oracles-monorepo/blob/069abc182f27959d84e3c33e0d57c7a93bdbbe9d/packages/oracle-node/src/fetchers/MultiRequestFetcher.ts)

2023-02-08 21:40 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +      const price = pairedTokenPrice / Number(spotPrice);
IMHO this line `const price = pairedTokenPrice / Number(spotPrice);` should be moved to the `extractPrices` function. The `fetchData` function should focus only on fetching data (and should be async), while the `extractPrices` can do different manipulations, shouldn't be async and should contain the main logic of parsing response (or responses) into the result prices

2023-02-09 08:19 UTC, rucinpk commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +  protected async getPairedTokenPrice() {
it needs to be async, because child classes f.e. `BalancerHistoricalFetcher`needs this function to be async

2023-02-10 23:21 UTC, hatskier requested changes

2023-02-10 23:21 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +  ): Promise<SpotPrice | null> {
Let's remove `| null` from this type

2023-02-10 23:21 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +      if (!priceResult) {
You can remove this condition because `!priceResult` will never be true

2023-02-10 23:21 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    const spotPrices = await Promise.all(spotPricesPromises);
What do you think about using Promise.allSettled here?

2023-02-20 15:12 UTC, cehali approved these changes

2023-02-20 15:15 UTC, merged