Feat/add uniswap sushiswap historical[WIP]
redstone-finance/redstone-oracles-monorepo pull request #341
Opened 2023-01-31 12:33 UTC by rucinpk

2023-02-04 21:15 UTC, hatskier requested changes

2023-02-04 21:15 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3/historical/UniswapV3FetcherHistorical.ts
> +  constructor(timestamp: number) {
Why did you decide to use `timestamp` in the Uniswap V3 fetcher constructor, but `blockNumber` in the Sushiswap fetcher constructor?

2023-02-04 21:15 UTC, hatskier commented on packages/oracle-node/tools/balancer/get-historical-balances-with-graph.ts
> +    let results: any[] = [];
Please don't use `any` types in typescript files

2023-02-04 21:15 UTC, hatskier commented on packages/oracle-node/tools/balancer/get-historical-balances-with-graph.ts
> +    let results: any[] = [];
And use `const` where possible

2023-02-04 21:15 UTC, hatskier commented on packages/oracle-node/tools/balancer/get-historical-balances-with-graph.ts
> +  let balancerPrices: any = [];
Please specify types

2023-02-04 21:15 UTC, hatskier commented on packages/oracle-node/tools/balancer/get-historical-balances-with-graph.ts
> +  let filePrices = readPrices("chainlink-prices-with-block.json");
Please use `constz

2023-02-04 21:15 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3/get-historical-prices.ts
> +Promise.all = function promiseAllIterative(values: any): any {
What is the purpose of this function?

2023-02-05 19:43 UTC, rucinpk commented on packages/oracle-node/tools/uniswap-v3/get-historical-prices.ts
> +Promise.all = function promiseAllIterative(values: any): any {
The purpose of overriding `Promise.all` is to be able to know what timestamp was used to call the promise after resolve

2023-02-05 19:53 UTC, rucinpk commented on packages/oracle-node/src/fetchers/uniswap-v3/historical/UniswapV3FetcherHistorical.ts
> +  constructor(timestamp: number) {
I already got data with `blockNumbers` for SushiSwap

2023-02-07 10:01 UTC, cehali commented
Now you can merge it to main as branch `add-uniswap-v3-fetcher` is already merged to main

2023-02-07 10:09 UTC, cehali commented on packages/oracle-node/src/fetchers/DexFetcher.ts
> +    protected readonly symbolToPairIdObj: SymbolToPairId
What is the reason for the change from protected to private?

2023-02-07 10:24 UTC, cehali commented on packages/oracle-node/tools/uniswap-v3/get-historical-prices.ts
> +Promise.all = function promiseAllIterative(values: any): any {
I think that using here `Promise.all` and overwriting it leads to code which is hard to understand. Because of the fact that this is a tool which won't be used very often and `Promise.all` doesn't meet requirements I would go with a simple for loop and fetching data for each iteration. This will increase execution time but improve readability and remove duplicates.

2023-02-07 14:20 UTC, rucinpk commented on packages/oracle-node/tools/uniswap-v3/get-historical-prices.ts
> +Promise.all = function promiseAllIterative(values: any): any {
I agree that it makes code unreadable and it does not look good. But thanks to it, it is possible to query quite long historical data. I also tested iterative approach - it it is impossible to query reasonable amount of historical blocks.

2023-02-07 14:47 UTC, rucinpk commented on packages/oracle-node/src/fetchers/DexFetcher.ts
> +    protected readonly symbolToPairIdObj: SymbolToPairId
Protected is needed to be able to use those properties in historical fetcher during Graph query construction

2023-02-09 00:40 UTC, hatskier requested changes

2023-02-09 00:40 UTC, hatskier commented on packages/oracle-node/prices.csv
> +,timestamp,chainlinkPrice,uniswapPrice,sushiswapEth,sushiswapDai,ohmDaiBased,ohmWethBased,DaiWethBased
Can you move this file from the root folder?

2023-02-09 00:40 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3/get-historical-prices.ts
> +      .then((results) => {
It's not a good practice to mix async/await syntax with `.then` chaining. You can replace this code with smth like
```js
const results = await Promise.all(promises);
results.forEach((result => ...);
```

2023-03-01 01:13 UTC, hatskier approved these changes

2023-03-01 01:41 UTC, merged