feat: add price feed model
redstone-finance/redstone-oracles-monorepo pull request #345
Opened 2023-02-03 14:12 UTC by cehali

2023-02-03 15:24 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +      return;
I think we should call `return` in the `storeDataFeedsFromDataPackage`, not here ;)

2023-02-03 15:26 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  function getChalinlikLikeContractAddresses(bytes32 dataFeedId) public view returns (address) {
Let's change the name of this function to `getDataFeedContractAddress`

2023-02-03 15:52 UTC, hatskier requested changes

2023-02-03 15:52 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  uint256 private lastBlockTimestamp;
Let's rename it to the `lastUpdateTimestamp`, because last block timestamp sounds like the timestamp of the last block

2023-02-03 15:52 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    if (block.timestamp <= lastBlockTimestamp) {
This function should not check if the `block.timestamp > lastBlockTimestamp `. It should check if the timestamp from data packages is `> lastBlockTimestamp`.

To do this we need few updates in this contract:
1. The `storeDataFeedsFromDataPackage` function should additionally receive `timestampFromPayload` as an argument
2. We should validate if `timestampFromPayload > lastBlockTimestamp`
3. We should override the [`validateTimestamp`](https://github.com/redstone-finance/redstone-oracles-monorepo/blob/main/packages/evm-connector/contracts/core/RedstoneConsumerBase.sol#L39) function so it additionally checks if the `timestampFromPayload === receivedTimestampMilliseconds `. But we also don't want to remove the default timestamp validation logic

2023-02-03 15:52 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +      return;
I would change this function so it returns boolean value if the proposed round is valid

2023-02-03 15:52 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +    return this.latestRoundData();
What do you think about always reverting this function? It would help to avoid its incorrect usage

2023-02-03 15:52 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +    return "RedStone price feed";
Let's return this value from storage

2023-02-03 15:52 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +    owner = _owner;
Let's add a string argument `description` in the constructor. IMO it will help with readability of the contracts in blockchain explorers

2023-02-03 15:52 UTC, hatskier commented on packages/contract-prices-updater/src/start-updater.ts
> +        dataFeeds: ["BTC", "ETH"],
Let's remove dataFeeds param here, as it will significantly reduce gas costs for the bigger number of data feeds

2023-02-03 15:52 UTC, hatskier commented on packages/contract-prices-updater/src/start-updater.ts
> +      await wrappedContract.storeDataFeedsFromDataPackage(lastRound);
Shouldn't we have `lastRound + 1` here?

2023-02-03 15:52 UTC, hatskier commented on packages/contract-prices-updater/src/start-updater.ts
> +    const lastRound = await priceFeedsManagerContract.getLastRound();
We still need to think about synchronising several bots, because current solution doesn't solve the problem that if we run 3 bots the number of txs will grow 3 times. Maybe we should have some off-chain mechanism for evaluating the next round. E.g. getting roundNumber based on timestamp and just skipping if someone already updated data for it.

Let's think about it and discuss on a call later

2023-02-04 12:15 UTC, cehali commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  function getChalinlikLikeContractAddresses(bytes32 dataFeedId) public view returns (address) {
I think `getPriceFeedContractAddress` would be more consistent with PriceFeed contract

2023-02-04 12:23 UTC, cehali commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +    return "RedStone price feed";
I am not a Solidity expert, but if we want to return a string, it needs to be a memory.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/35804520/216767321-9d147934-3da1-4f29-8a3a-0d3ba2ae2ef0.png">

2023-02-04 12:24 UTC, cehali commented on packages/contract-prices-updater/src/start-updater.ts
> +      await wrappedContract.storeDataFeedsFromDataPackage(lastRound);
Sh*t, I was testing bad scenarios and left it there

2023-02-04 20:13 UTC, hatskier requested changes

2023-02-04 20:13 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  function validateRound(uint256 proposedRound) private view returns (bool) {
Let's rename this function to `isProposedRoundValid`

2023-02-04 20:13 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    uint256[] memory values = getOracleNumericValuesFromTxMsg(dataFeedsIds);
Let's add a comment here that the `getOracleNumericValuesFromTxMsg` function will call the `validateTimestampFromPayload` function for each data package from the redstone payload

2023-02-04 20:13 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    if (block.timestamp < receivedTimestampSeconds) {
Can't we just call `RedstoneDefaultsLib.validateTimestamp(receivedTimestampMilliseconds);` here?

2023-02-04 20:13 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  uint256 private lastUpdateTimestamp;
Let's rename to `lastUpdateTimestampMilliseconds`

2023-02-04 20:13 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +      revert TimestampFromPayloadAndFromDataPackageAreNotTheSame(
This error naming is a bit misleading, because timestamp from payload is from data package, because data package is included in the payload. Let' change the error name to `ProposedTimestampDoesNotMatchTimestampFromPayload`

2023-02-05 13:13 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +    address _owner,
Please add underscores at the end of naming to follow official convention.
You can read more about the style guidelines here:
- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/GUIDELINES.md
- https://docs.soliditylang.org/en/latest/style-guide.html#avoiding-naming-collisions

2023-02-05 13:14 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +  function getRoundData(uint80 _roundId)
Please add underscore in the end
https://docs.soliditylang.org/en/latest/style-guide.html#avoiding-naming-collisions

2023-02-06 09:13 UTC, cehali commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    uint256[] memory values = getOracleNumericValuesFromTxMsg(dataFeedsIds);
You mean `validateTimestamp`?

2023-02-06 12:01 UTC, jakub-wojciechowski commented on packages/contract-prices-updater/src/start-updater.ts
> +    const lastRound = await priceFeedsManagerContract.getLastRound();
Is it possible that if we run two parallel, both will try to update with the same roundId but with slightly different timestamp?

2023-02-06 12:07 UTC, jakub-wojciechowski commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    if (!validateRound(proposedRound)) return;
Do we protect somehow against posting older price-feeds that still fit into validation window, that could trigger a higher roundId?

2023-02-06 12:08 UTC, cehali commented on packages/contract-prices-updater/src/start-updater.ts
> +    const lastRound = await priceFeedsManagerContract.getLastRound();
Yes, we want to mitigate by fetching `lastUpdateTimestampMilliseconds` from the contract and checking if the current timestamp is older than `lastUpdateTimestampMilliseconds` by 2 minutes.

2023-02-06 12:10 UTC, jakub-wojciechowski commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +contract PriceFeedsManager is AvalancheDataServiceConsumerBase {
We should also think about a policy of updating PriceManager (e.g. additional provider / change validation logic) while having the same PriceFeeds

2023-02-06 12:29 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    if (!validateRound(proposedRound)) return;
Yes, we do it using the `validateTimestampFromPayload` function

2023-02-06 16:26 UTC, hatskier requested changes

2023-02-06 16:26 UTC, hatskier commented on packages/evm-connector/src/WrapperBuilder.ts
> +    dataPackagesRequestParams: Omit<
Why do we need dataPackagesRequestParams here? I thought it would be sufficient to have only `dataPackages`

2023-02-06 16:26 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataPackagesWrapper.ts
> +    return `${version}#${this.dataPackagesRequestParams.dataServiceId}`;
I would change it to `${version}#data-packages-wrapper`

2023-02-06 16:26 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataPackagesWrapper.ts
> +      this.runDryRunVerification({ ...params, redstonePayload });
IMHO we don't need dry-runs in this wrapper

2023-02-06 16:35 UTC, hatskier commented on packages/on-chain-relayer/src/start-relayer.ts
> +        console.log("Cannot update prices yet");
I would replace "cannot" with "should not", because the contract doesn't prevent updating prices even in each block

2023-02-06 16:42 UTC, hatskier commented on packages/on-chain-relayer/src/start-relayer.ts
> +      const isTwoMinutesSinceLastUpdate =
Also, I would propose to set it to 115 or 110 seconds to prevent potential delays

2023-02-07 07:57 UTC, cehali commented on packages/evm-connector/src/WrapperBuilder.ts
> +    dataPackagesRequestParams: Omit<
If we don't want to do dry run and have name of the `dataServiceId` then we don't need `dataPackagesRequestParams` 😄

2023-02-07 10:11 UTC, hatskier approved these changes

2023-02-07 10:12 UTC, merged