feat: improved LP tokens price calculation
redstone-finance/redstone-oracles-monorepo pull request #353
Opened 2023-02-07 19:03 UTC by rucinpk

Implemented fair LP token pricing

2023-02-08 15:30 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/extract-price.ts
> +import bn from "bignumber.js";
Please use big number built in `ethers.js` -https://docs.ethers.org/v5/api/utils/bignumber/

2023-02-08 15:47 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/extract-price.ts
> +
Generally, variables should be initialized as close as possible to the place they will be used. Please move it somewhere closer, somewhere inside  `if (tokenPrices)`

2023-02-08 15:53 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/extract-price.ts
> +
I would improve the naming here because it gets difficult to read.

``` js
const reservesMultiplied = reservesSerialized[firstToken].mul(reservesSerialized[secondToken];
const pricesMultiplied = firstTokenPrice.mul(secondTokenPrice);
const reservesMultipliedSqrt = sqrt(reservesMultiplied);
const pricesMultipliedSqrt = sqrt(pricesMultiplied);
const reservesPricesMulitplied = sqrt(reservesMultiplied).mul( sqrt(pricesMultiplied)).mul(2);
const lpTokenPrice = reservesPricesMulitplied.div(totalSupply);
```

2023-02-08 15:56 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/extract-price.ts
>  import { mooTokensContractsDetails } from "./contracts-details/moo-joe";
Please add it somewhere at the top of the file or just after updates from where we take the formula for calculating LP tokens price

2023-02-08 15:57 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/extract-price.ts
>  const extractPriceForLpTokens = async (
I wonder if the same formula could be used in other tokens from AvalancheEVMFetcher f.g. in functions `extractPriceForYieldYakOrMoo` or `extractPriceForYieldYakOrMoo`

2023-02-09 13:14 UTC, rucinpk commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/extract-price.ts
>  const extractPriceForLpTokens = async (
it can't be implemented, it's only relevant to LP tokens

2023-02-10 10:54 UTC, cehali commented on packages/oracle-node/src/utils/math.ts
> +import { ethers, BigNumber } from "ethers";
I forgot last time, please write few test to be sure that it works

2023-02-21 11:33 UTC, cehali commented on packages/oracle-node/src/utils/math.ts
> +import { ethers, BigNumber } from "ethers";
If you import `BigNumber` you don't need `ethers`

2023-02-21 11:33 UTC, cehali commented on packages/oracle-node/test/utils/math.spec.ts
> +    const number = BigNumber.from(999999999).mul(BigNumber.from(999999999));
Extract `BigNumber.from(999999999)` to separate variable

2023-02-21 11:36 UTC, cehali commented on packages/oracle-node/test/utils/math.spec.ts
> +  test("Should properly floor square big integers", async () => {
That's not good. We could miscalculate prices because of this. This could mean that your previous implementation with `bignumber.js` could be better because it seems more accurate. Please investigate it and change the implementation in `math.ts`.

2023-02-21 11:36 UTC, cehali requested changes
Details in comments

2023-02-27 20:04 UTC, rucinpk commented on packages/oracle-node/test/utils/math.spec.ts
> +  test("Should properly floor square big integers", async () => {
No I don't think we can - BigNumber is integer so there is no way to make float squaring here. BigNumber prices are denominated in Wei so there is not reason to make floor division anyway.

2023-02-28 07:51 UTC, cehali commented on packages/oracle-node/test/utils/math.spec.ts
> +  test("Should properly floor square big integers", async () => {
Yes, you are right. I forgot that we already serialize all values before square rooting.

2023-02-28 07:51 UTC, cehali approved these changes
LGTM

2023-03-01 01:14 UTC, hatskier approved these changes

2023-03-01 01:15 UTC, merged