feat: added timestamp delay
redstone-finance/redstone-oracles-monorepo pull request #370
Opened 2023-02-13 18:42 UTC by rucinpk

2023-02-15 14:16 UTC, hatskier submitted a review, later dismissed

2023-02-15 14:16 UTC, hatskier commented on packages/sdk/src/index.ts
> +      maxTimestampDelay &&
We should run this check only on data packages after calling the `slice` method (`.slice(0, reqParams.uniqueSignersCount)`).

To give an example: Assume we have 5 nodes, but require only 3 of them. Then assume 1 of the nodes stopped working and provides outdated packages. If we check all 5 data packages from all nodes then users won't be able to use 3 valid nodes. That's why we need to check only 3 newest data packages if they contain non-outdated timestamps

2023-02-15 14:16 UTC, hatskier commented on packages/sdk/test/index.test.ts
> +import axios from "axios";
Why did you add this line?

2023-02-21 12:31 UTC, cehali commented on packages/sdk/src/index.ts
> +const SECOND_IN_MILLISECONDS = 1000;
Unused variable?

2023-02-21 12:38 UTC, cehali commented on packages/sdk/src/index.ts
> +      })
I would simplify it: 
``` js
const maxTimestampDelay = reqParams?.maxTimestampDelay ?? currentTimestamp;
const outdatedDataPackages = dataFeedPackages.filter((dataFeedPackage) => currentTimestamp - maxTimestampDelay >= dataFeedPackage.timestampMilliseconds);
const isAnyPackageOutdated = outdatedDataPackages.length > 0
if (isAnyPackageOutdated) {
const outdatedDataPackagesTimestamps = outdatedDataPackages.map(({ timestampMilliseconds }) => timestampMilliseconds);
throw new Error(
        `At least one datapackage is outdated. Current timestamp: ${currentTimestamp}. Outdated datapackages timestamps: ${outdatedDataPackagesTimestamps}`
      );
}
```

2023-02-21 12:41 UTC, cehali commented on packages/sdk/test/index.test.ts
> +    ).rejects.toThrow("At least one datapackage is outdated");
Please check if the error string is properly parsed. I think `outdatedDataPackagesTimestamps` could require `JSON.stringify`

2023-02-28 07:55 UTC, cehali approved these changes
LGTM

2023-03-01 01:24 UTC, hatskier requested changes

2023-03-01 01:24 UTC, hatskier commented on packages/sdk/test/index.test.ts
> +      /At least one datapackage is outdated. Current timestamp: [0-9]*. Outdated datapackages timestamps: \[1654353400000,1654353400000\]/
You can mock Date.now using Jest to make the tests deterministic and avoid workarounds like this "Current timestamp: [0-9]*"

2023-03-01 01:24 UTC, hatskier commented on packages/sdk/src/index.ts
> +    const maxTimestampDelay = reqParams?.maxTimestampDelay ?? currentTimestamp;
The `parseDataPackagesResponse` function became too big. I would propose to move the timestamp delay validation to a separate function.

2023-03-07 12:13 UTC, hatskier approved these changes

2023-03-07 12:16 UTC, merged