Add on chain fetchers dexes
redstone-finance/redstone-oracles-monorepo pull request #391
Opened 2023-02-23 16:34 UTC by cehali

2023-03-02 23:58 UTC, hatskier requested changes

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/aggregators/lwap-aggregator/get-liquidities.ts
> +      liquidity: liquidity.source[theOnlySource],
Wouldn't it be easier to use `Object.values(liquidity.source)[0]`?

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/PricesService.ts
> +            isLiquidityAndSymbol(priceToCheck.symbol, price.symbol)
IMO it's quite easy to make a mistake while using this function. What do you think about calling it `isLiquidityForAsset({asset: string, maybeLiquiditySymbol: string})`?

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/PricesService.ts
> +            isLiquidityAndSymbol(priceToCheck.symbol, price.symbol)
Also, do we really need to filter only liquidity prices here since we do the filtering again in the `getTickLiquidities` function?

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +const PROMISE_STATUS_FULFILLED = "fulfilled";
Let's move it to some more general place (e.g. utils), as it may be reused in other places where we use Promise.allSettled

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +    for (const assetId of assetsIds) {
Shouldn't we again have the `try .. catch` block  inside this loop?

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +    const response: Responses<T> = {};
I would rename `response` to `poolDetailsPerAssetId` or `responsePerAsset`

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +      if (status === PROMISE_STATUS_FULFILLED && responseWithStatus.value) {
Should we log some message if status is not fulfilled?

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +        const { dataFeedId } = getDataFromLiquidityDataFeedId(assetId);
I would rename `getDataFromLiquidityDataFeedId` to `parseLiquidityDataFeedId`

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +  async extractPoolDetailsPerAssetId(
Why is it async? If not, I would say the `extractPrices` method is the better place for this function

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/liquidity/utils.ts
> +  const regex = /(.*)_(.*)_(.*)$/;
Shouldn't it be `/(.*)_(.*)_liquidity$/`?

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/liquidity/utils.ts
> +export const isLiquidity = (name: string) => name.includes("_liquidity");
We can make this function a bit stricter by using regex here as well

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/liquidity/utils.ts
> +export const isLiquidityAndSymbol = (name: string, tokenName: string) =>
We can improve this function by using the regex here

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +      if (status === PROMISE_STATUS_FULFILLED && responseWithStatus.value) {
Why can't we reuse the MultiRequestFetcher here instead of the BaseFetcher?

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswapV2Like/UniswapV2LikeFetcher.ts
> +    const promises = spotAssetIds.map(async (assetId) => {
I think we should use MultiRequestFetcher instead

2023-03-02 23:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswapV2Like/UniswapV2LikeFetcher.ts
> +  serializeReserveDecimals(reserve: BigNumber, decimals: number) {
Please add return type to this function

2023-03-03 07:55 UTC, cehali commented on packages/oracle-node/src/fetchers/PricesService.ts
> +            isLiquidityAndSymbol(priceToCheck.symbol, price.symbol)
Good catch

2023-03-03 12:51 UTC, cehali commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +  async extractPoolDetailsPerAssetId(
Changed when moving to `MultiRequestFetcher`

2023-03-03 12:51 UTC, cehali commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +    const response: Responses<T> = {};
Changed when moving to `MultiRequestFetcher`

2023-03-03 12:51 UTC, cehali commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +      if (status === PROMISE_STATUS_FULFILLED && responseWithStatus.value) {
Changed when moving to `MultiRequestFetcher`

2023-03-03 12:51 UTC, cehali commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +      if (status === PROMISE_STATUS_FULFILLED && responseWithStatus.value) {
Changed when moving to `MultiRequestFetcher`

2023-03-03 12:52 UTC, cehali commented on packages/oracle-node/src/fetchers/liquidity/utils.ts
> +export const isLiquidityAndSymbol = (name: string, tokenName: string) =>
Removed after changes

2023-03-03 22:58 UTC, hatskier commented on packages/oracle-node/src/fetchers/balancer/BalancerFetcher.ts
> +    const priceResult = this.calculatePrice(id, pairedTokenPrice);
It looks a bit unclear why we calculate the price in the `makeRequest` method

2023-03-03 23:03 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswapV2Like/UniswapV2LikeFetcher.ts
> +      reserve0: _reserve0 as BigNumber,
Why should we add this type annotation `as BigNumber`? Isn't is returned as a BigNumber from the contract already?

2023-03-06 10:10 UTC, cehali commented on packages/oracle-node/src/fetchers/uniswapV2Like/UniswapV2LikeFetcher.ts
> +      reserve0: _reserve0 as BigNumber,
No, it is returned as `any`
<img width="577" alt="image" src="https://user-images.githubusercontent.com/35804520/223080269-249eeb30-db95-49eb-855c-7bf232169724.png">

2023-03-06 11:55 UTC, hatskier approved these changes

2023-03-06 11:55 UTC, merged