388 create an on chain relayer for eth on starknet
redstone-finance/redstone-oracles-monorepo pull request #394
Opened 2023-02-24 12:41 UTC by Lukasz2891

2023-02-28 10:00 UTC, cehali commented on packages/cairo-connector/data/test.hex
> +0x455448000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000025869aed8601867a4e578000000020000001883135efe31173469737a3d603f053c7555f7eea526
Please add new line

2023-02-28 10:02 UTC, cehali commented on packages/cairo-connector/data/test.json
> +"statusCode":500,"message":"Internal server error"
Why does `test.json` look like an error? Maybe rename a file?

2023-02-28 10:51 UTC, cehali commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    assert_owner();
I am wondering if it is the same as in the solidity contract. We want to PriceFeed be updated only by PriceManager and PriceManager function to update prices can be called by anyone

2023-02-28 10:52 UTC, cehali commented on packages/cairo-connector/src/contracts/price_feed.cairo
> +    let (package_ts, round_id) = IPriceManager.read_timestamp_and_round(
Good idea to get those values and add them to return. We should do the same in solidity contract

2023-02-28 10:54 UTC, Lukasz2891 commented on packages/cairo-connector/data/test.json
> +"statusCode":500,"message":"Internal server error"
sample data files are not needed anymore

2023-02-28 10:55 UTC, Lukasz2891 commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    assert_owner();
I've asked Alex about that (calling manager from price feed) - so we can change it, but Idk if it's important for now ;)

2023-03-12 17:41 UTC, hatskier requested changes

2023-03-12 17:41 UTC, hatskier commented on packages/starknet-relayer/src/starknet/StarknetDataProvider.ts
> +    let payloadData = [];
`let` can be changed to `const` here since you don't change the variable directly and only set values for indexes

2023-03-12 17:41 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_feed.cairo
> +    with_attr error_message("Method not allowed. Use latest_round_data instead.") {
Hahaha, a very interesting way to always throw an error

2023-03-12 17:41 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_feed.cairo
> +    let (block_ts) = IPriceManager.get_block_timestamp(contract_address=contract_address);
Shouldn't we use `read_timestamp_and_round` here instead of `get_block_timestamp `  and `get_block_number`?

2023-03-12 17:41 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +func get_block_timestamp{
Can this function be removed?

2023-03-12 17:41 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +func get_block_number{
Can this function be removed?

2023-03-12 17:41 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    assert_owner();
As we discussed on the call, current model is better. PriceManager can store values and PriceFeed contracts will query from its PriceManager's storage. This model is even more secure, because of its permissionless nature

2023-03-12 17:41 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    assert_owner();
I would allow everyone to update the prices (not only the owner)

2023-03-12 17:41 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    let (values, ts) = get_aggregated_values(
How is this `ts` value is calculated? Is it the minimum timestamp each package's timestamp?

2023-03-12 17:41 UTC, hatskier commented on packages/data-generator/Makefile
> +#PAYLOAD_URL=https://d33trozg86ya9x.cloudfront.net/data-packages/payload?data-packages/payload?unique-signers-count=1&data-service-id=redstone-rapid-demo&data-feed-id=BTC,ETH,BNB,AR,AVAX,CELO&format=
Should we remove the commented version?

2023-03-12 17:41 UTC, hatskier commented on packages/data-generator/.gitignore
> +data/
Why should we create a separate package for the data generation? Also, the name `data-generator` is too generic. I would call it payload generator and would probably move it to the redstone-protocol package (e.g. to the scripts folder)

2023-03-13 09:32 UTC, Lukasz2891 commented on packages/starknet-relayer/src/start-relayer.ts
> +(() => {
generally - there are 2 logics here ;)
1) on-chain relayers
2) chains 

The second one should be extracted to have it reused also in the showroom purposes.

2023-03-13 09:42 UTC, Lukasz2891 commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    let (values, ts) = get_aggregated_values(
it's just ```payload.data_packages.ptr[0].timestamp```

should we use `min` here?

2023-03-13 09:54 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_feed.cairo
> +    let (block_ts) = IPriceManager.get_block_timestamp(contract_address=contract_address);
Oh right. Then I think we should have a function for extracting all details about the latest update (including round id, data package timestamp, block timestamp, block number, and round number)

2023-03-13 09:55 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    let (values, ts) = get_aggregated_values(
Yes, for sure. Otherwise it's possible to provide many outdated packages but put the newest one into the 0th index

2023-03-13 09:56 UTC, Lukasz2891 commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +func get_block_timestamp{
it can be removed ;) so it should be moved to the feed.

2023-03-13 10:07 UTC, Lukasz2891 commented on packages/starknet-relayer/src/starknet/StarknetDataProvider.ts
> +    for (let i = 2; i < Array.from(payloadHex).length - 1; i++) {
It's not needed ;)

2023-03-13 22:55 UTC, hatskier requested changes

2023-03-13 22:55 UTC, hatskier commented on packages/cairo-connector/src/contracts/price_feed.cairo
> +    let (block_ts) = get_block_timestamp();
Shouldn't we return the block number and the blok timestamp of the latest price update?

2023-03-14 08:47 UTC, Lukasz2891 commented on packages/cairo-connector/src/contracts/price_manager.cairo
> +    let (values, ts) = get_aggregated_values(
still we verify the packages, so outdated means here "not earlier than 15 minutes before the block-timestamp" :) but ok ;p

2023-03-14 08:49 UTC, Lukasz2891 commented on packages/cairo-connector/src/contracts/price_feed.cairo
> +    let (block_ts) = get_block_timestamp();
hm, that means we should move the `get_block_timestamp` back to the manager ;)

2023-03-18 18:30 UTC, hatskier approved these changes
LGTM!

2023-03-20 08:57 UTC, merged