feat: add on chain fetchers dexes with uniswap v3
redstone-finance/redstone-oracles-monorepo pull request #400
Opened 2023-03-02 16:45 UTC by rucinpk

2023-03-07 19:11 UTC, hatskier requested changes
- Can pool address be changed? If not, can we hardcode its address?
- We should fetch liquidity data from Uniswap V3 in exactly the same moment when we fetch price. We can utilise multi-call contracts for it. Don't use Promise.all
- What identifies the pool (token1, token2 and fee)? Can the fee value be other than 3000, 5000 and 10000? We should create fetchers for each existing pool
- Liquidity should be calculated in USD. Also, we should deeply understand how the liquidity is calculated? We should also think how to calculate liquidity calculated in a similar way to Uniswap V2
- Let's remove jsbi
- Let's remove awaits where they are not necessary
- Let's add *.abi.json instead of *.json for abis
- Let's check ig ethes.formatUnits or ethers.parseUnits can replace `fromReadableAmount` and JSBI
- Let's name constants so their names tell about their puropse (not just TEN for 10 ;))

2023-03-13 23:38 UTC, hatskier requested changes

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/types.ts
> +import { BigNumber } from "ethers";
I would move the uniswap-v3-on-chain folder to evm-chains/ethereum/

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/uniswap-v3-fetchers-config.json
> +  "uniswap-v3-on-chain-OHM": {
Shouldn't we also include fee in the fetcher name and create fetchers for each available fee?

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/test/fetchers/mocks/UniswapV3FactoryMock.json
> +{
Should we add `abi.json` to the filename?

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/test/fetchers/mocks/UniswapV3PoolMock.json
> +  "abi": [
Should we add `abi.json` to the filename?

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/test/fetchers/mocks/UniswapV3QuoterMock.json
> +{
Should we add `abi.json` to the filename?

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3-on-chain/get-pool-configs.ts
> +const FEE_AMOUNTS = [10000, 3000, 500, 100];
How do you know if other fees are not possible? Can you add a comment with explanation to this place in the code, ideally with the link to the source

2023-03-13 23:38 UTC, hatskier commented on yarn.lock
> +jsbi@^4.3.0:
Let's remove jsbi dependency

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3-on-chain/get-pool-configs.ts
> +const POOL_PoolConfigs_FILE_PATH = "uniswap-v3-fetchers-config.json";
Let's have a consistent name for this file, e.g. POOL_CONFIGS_FILE_PATH

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3-on-chain/get-pool-configs.ts
> +const TOKEN_ADDRESSES = [
Let's add comments with symbols to the addresses

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3-on-chain/get-pool-configs.ts
> +  for (let tokenIndex = 0; tokenIndex < TOKEN_ADDRESSES.length; tokenIndex++) {
Can't we iterate over addresses and compare them instead of indexes?
e.g.
```js
for (const tokenAddress1 of TOKEN_ADDRESSES) {
     for (const tokenAddress2 of TOKEN_ADDRESSES) {
         if (tokenAddress1 !== tokenAddress2) {...}
     }
}

```

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3-on-chain/get-pool-configs.ts
> +        const { poolAddress, foundFee } = await findPool(
Do we have a guarantee that each given pair of symbols always will have only one pool (with one fee)?

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/tools/uniswap-v3-on-chain/get-pool-configs.ts
> +  for (const fee of FEE_AMOUNTS) {
Shouldn't we return all found pools? Not only the first one that we found?

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/test/fetchers/uniswap-v3-on-chain.spec.ts
> +  test("should properly fetch liquidity", async () => {
I am not sure if we should allow to fetch liquidity since we don't deeply understand the meaning of this value in Uni V3

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +const DOLLAR_IN_CENTS_EXPONENT = 2;
Why 2?

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    if (isLiquidity(id)) {
This condition will never be met. `DexOnChainFetcher` is implemented in the way that the `makeRequest` function will always receive `spotAssetId`. Liquidity ids will be filtered out

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +  calculateLiquidity(assetId: string, response: QuoterOutAmount): number {
Please add the `override` keyword to improve readability

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +  calculateSpotPrice(assetId: string, quoterResponse: QuoterOutAmount) {
Please add the `override` keyword to improve readability

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const [amountOutResult, liquidity] = await Promise.all([
It doesn't guarantee that the blockchain calls will be made for the same blockchain state. To be sure, we should use multicall. But it's for future.
For now, we can simply remove the liquidity fetching in Uni v3 and override the `calculateLiquidity` to always throw an error

2023-03-13 23:38 UTC, hatskier commented on packages/oracle-node/src/fetchers/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const outAssetDecimalsExp = BigNumber.from(10).pow(
@cehali can you please review the spot price calculation algorithm when you have a free minute?

2023-03-20 12:19 UTC, rucinpk commented on packages/oracle-node/test/fetchers/mocks/UniswapV3FactoryMock.json
> +{
In other mock files in the project do not have `abi.json` in their filename and are named with just `.json`

2023-03-21 08:51 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/all-uniswap-v3-fetchers.ts
> +const provider = new ethers.providers.JsonRpcProvider(config.ethMainRpcUrl);
You could consider using `StaticJsonRpcProvider` here https://docs.ethers.org/v5/api/providers/jsonrpc-provider/#StaticJsonRpcProvider

2023-03-21 09:01 UTC, cehali commented on packages/oracle-node/test/fetchers/mocks/UniswapV3FactoryMock.json
> +{
I am wondering why we need Mocked abis. They are only interfaces and they should be the same as the one deployed. I used to mock bytecodes but now I know it was bad idea and we should use https://ethereum-waffle.readthedocs.io/en/latest/mock-contract.html?highlight=mock

2023-03-21 09:05 UTC, cehali commented on packages/oracle-node/test/fetchers/uniswap-v3-on-chain.spec.ts
> +    await quoterContract.mock.quoteExactInputSingle.returns(
Good idea, we will switch other tests to mock functions that return 0 right after deployment.

2023-03-21 09:05 UTC, cehali commented on packages/oracle-node/test/fetchers/uniswap-v3-on-chain.spec.ts
> +    await poolContract.mock.liquidity.returns(123456789);
If we don't know how to calculate liquidity I don't think this is neccessary

2023-03-21 09:27 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const outAssetLastPrice = getLastPrice(quoterResponse.outAssetId)!.value;
`outAssetLastPrice` could be undefined here. We should throw an error if so.

2023-03-21 09:46 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +        amountIn: ethers.utils
Does this parameter take into account decimals? Or is it like `I want to change 1 OHM for ETH`? If the second option is correct I believe we could use here a fixed number and not `token0Decimals`.

2023-03-22 12:20 UTC, rucinpk commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +        amountIn: ethers.utils
Yes, the calculation must take into account the number of decimals for both token0 and token1.

2023-06-05 15:39 UTC, hatskier commented on packages/oracle-node/manifests/single-source/uniswap-v3-on-chain-WETH-10000.json
> +  "defaultSource": ["uniswap-v3-on-chain-WETH-10000"],
Can we call it uniswap-v3-on-chain-weth-10000 to be consistent with other fetchers' names?

2023-06-05 15:39 UTC, hatskier commented on packages/oracle-node/manifests/single-source/uniswap-v3-on-chain-WETH-10000.json
> +      "source": ["uniswap"]
Why only uniswap? Also, I think w should use ETH price for WETH.
Also, I think we should add `skipSigning` option here for WETH (or ETH) token

2023-06-05 15:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const liquidity = BigNumber.from(
We can use he heura with slippage -> liquidity conversion

2023-06-05 15:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const priceRatio = new Decimal(1.0001)
What's this value 1.0001? Can we move it to a constant?

2023-06-05 15:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const decimalsDifferenceMultiplier = new Decimal(10).toPower(
Can we use a constant (TEN_AS_BASE or smth similar), which we already have?

2023-06-05 15:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    this.logger.error(
Why do we log with the `error` level here?

2023-06-05 15:46 UTC, rpiszczatowski commented on packages/oracle-node/manifests/single-source/uniswap-v3-on-chain-WETH-10000.json
> +      "source": ["uniswap"]
This was only to prove that the feature works. I'll add more realistic example with swETH. Athough I still don't know how e.g. uniswap-v2-on-chain-weth.json works without ETH price being pulled from somewhere.

2023-06-05 15:47 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const priceRatio = new Decimal(1.0001)
this is uniswap protocol-specific constant. I don't belive it has a name. I'll check it though.

2023-06-05 15:48 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    this.logger.error(
This is for testing purposes. I'll get rid of log messages before merge.

2023-06-05 17:33 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    this.logger.error(
Can you get rid now, so we don't need to re-approve?

2023-06-05 17:34 UTC, hatskier commented on packages/oracle-node/manifests/single-source/uniswap-v3-on-chain-WETH-10000.json
> +      "source": ["uniswap"]
I would say we can add ETH price with few free sources here so that the oracle-node can be properly launched with this manifest

2023-06-05 18:30 UTC, rpiszczatowski commented on packages/oracle-node/manifests/single-source/uniswap-v3-on-chain-WETH-10000.json
> +  "defaultSource": ["uniswap-v3-on-chain-WETH-10000"],
Sure. The name was added by original author of this PR.

2023-06-06 12:22 UTC, merged