feat: improve price feeds contracts
redstone-finance/redstone-oracles-monorepo pull request #408
Opened 2023-03-06 13:37 UTC by cehali

2023-03-06 13:50 UTC, hatskier requested changes

2023-03-06 13:50 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> -  PriceFeedsRegistry public priceFeedRegistry;
Can we remove the pricefeed registry contract now?

2023-03-06 13:50 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    bytes32[] calldata dataFeedsIds
If we now provide the `dataFeedsIds` argument, it looks like we easily can update only part of data feeds. So, a potential attacker can e.g. update only one data feed (updating lastUpdateTime), which will result in outdated values for all other data feeds.

I think we need to require in this function updating all the data feeds managed by the PriceFeedsManager.

2023-03-06 16:14 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    bytes32[] calldata dataFeedsIdsToUpdate
Why do we still need to pass this argument?

2023-03-06 16:14 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  function validateDataFeedsToUpdate(bytes32[] calldata dataFeedsIdsToUpdate) private view {
I would remove this function

2023-03-06 16:17 UTC, hatskier requested changes

2023-03-06 16:17 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  error InvalidDataFeedsIdsToUpdate(bytes32[] dataFeedsIdsToUpdate);
Since we use custom errors here, can we also use them in PriceFeed.sol instead of `revert("Use latestRoundData to get data feed price");`

2023-03-06 16:44 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  function addDataFeedId(bytes32 newDataFeedId) public onlyOwner {
Let's add a check for duplicates here

2023-03-06 16:45 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    return dataFeedsValues[dataFeedId];
Let's add a requirement that the value can't be 0

2023-03-06 16:45 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    return (dataFeedsValues[dataFeedId], lastRound, lastUpdateTimestampMilliseconds);
Let's add a requirement that the value can't be 0

2023-03-06 16:45 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +      values[i] = dataFeedsValues[dataFeedsIds[i]];
Let's add a requirement that the value can't be 0

2023-03-06 16:46 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    for (uint256 i = 0; i < dataFeedsIds.length; i++) {
Looks like there is a bug in this function ;)

2023-03-06 16:47 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +    returns (bytes32[] memory, uint256[] memory)
Why do we return `bytes32[] memory`?

2023-03-06 16:52 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +      uint256,
Let's add names to these returned values please

2023-03-06 16:59 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  function addDataFeedId(bytes32 newDataFeedId) public onlyOwner {
I have another concern about this function.
Because right after its execution the contract can end up in a weird state. E.g.:
- We deployed the contract with the following feeds `[bytes32("BTC"), bytes32("ETH")]`
- We called the `updateDataFeedValues` function few times
- Then we call `addDataFeedId(bytes32("AVAX"))`
- And then any user can call `getValueForDataFeedAndLastRoundParams(bytes32("AVAX"))` and receive a response with 0 value and valid `lastUpdateTimestampMilliseconds` and `lastRound`

2023-03-06 16:59 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeedsManager.sol
> +  function addDataFeedId(bytes32 newDataFeedId) public onlyOwner {
But if we require non-zero values everywhere this issue will not occur

2023-03-06 18:44 UTC, jakub-wojciechowski commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +    revert UseLatestRoundToGetDataFeedPrice();
Hmmm, to be compatible with the interface we can check if the roundId == latest Round, and revert only if they differ

2023-03-06 21:24 UTC, hatskier commented on packages/evm-connector/contracts/price-feeds/PriceFeed.sol
> +    revert UseLatestRoundToGetDataFeedPrice();
IMHO, it would create unclear behaviour. If this function can not be implemented properly, partial implementation may be misleading for devs. E.g. someone can rely on it, because it worked with the latest roundId, but then it stops working for any other value

2023-03-07 20:08 UTC, cehali commented on packages/evm-connector/contracts/price-feeds/DefaultsLib.sol
> +library DefaultsLib {
Changed name to `CustomErrors`

2023-03-07 20:29 UTC, merged