feat: minor updates to on-chain after price feed update
redstone-finance/redstone-oracles-monorepo pull request #422
Opened 2023-03-08 10:06 UTC by cehali

2023-03-08 16:45 UTC, jakub-wojciechowski commented on packages/oracle-node/manifests/data-services/rapid.json
> -    },
Why are we removing FRAX & VST in this commit?

2023-03-08 17:16 UTC, cehali commented on packages/oracle-node/manifests/data-services/rapid.json
> -    },
Because `PriceFeedManager` contract is `MainDemoConsumerBase` just to make it easier to integrate with other tokens. This is why I believe there is no point in keeping it in the rapid manifest.

2023-03-08 19:00 UTC, hatskier requested changes

2023-03-09 07:41 UTC, jakub-wojciechowski commented on packages/on-chain-relayer/contracts/price-feeds/PriceFeedsManager.sol
>  contract PriceFeedsManager is MainDemoConsumerBase, Ownable {
There is still the most important part... naming :)
I've started thinking about docs and I don't like the name Manger.
Conceptually, it's more like an adapter allowing to use traditional on-chain interfaces with our contracts. 
WDYT?

2023-03-09 09:24 UTC, cehali commented on packages/on-chain-relayer/src/core/update-conditions/should-update.ts
> +export const shouldUpdate = (lastUpdateTimestamp: number) => {
Yes, we later can change it to some context

2023-03-09 10:40 UTC, cehali commented on packages/oracle-node/manifests/data-services/rapid.json
> -    },
I readded them

2023-03-09 13:05 UTC, cehali commented on packages/on-chain-relayer/src/core/contract-interactions/update-prices.ts
> +  const dataPackages = await requestDataPackages(
I added solution with passing min timestamp from package

2023-03-09 13:06 UTC, cehali commented on packages/on-chain-relayer/contracts/price-feeds/PriceFeedsManager.sol
>  contract PriceFeedsManager is MainDemoConsumerBase, Ownable {
I changed name to PriceFeedsAdapter

2023-03-09 14:23 UTC, hatskier approved these changes

2023-03-09 14:23 UTC, hatskier commented on packages/on-chain-relayer/src/core/contract-interactions/update-prices.ts
> +      "Cannot update prices, data packages prices are equal or older than in price feed"
I would change this message to "Cannot update prices, proposed prices are not newer"

2023-03-09 14:23 UTC, hatskier commented on packages/on-chain-relayer/test/contracts/PriceFeedsAdapter.test.ts
> +  it("should revert if proposed timestamp is bigger the same as received", async () => {
This test description is misleading

2023-03-09 14:23 UTC, hatskier commented on packages/on-chain-relayer/tsconfig.json
> +    {
Shouldn't we also have evm-connector here in references?

2023-03-09 14:49 UTC, merged