feat: added deribit fetcher
redstone-finance/redstone-oracles-monorepo pull request #429
Opened 2023-03-09 14:18 UTC by rucinpk

2023-03-09 18:03 UTC, hatskier requested changes

2023-03-09 18:03 UTC, hatskier commented on packages/oracle-node/src/fetchers/dvol/DeribitFetcher.ts
> +export class DeribitFetcher extends MultiRequestFetcher {
Let's wait with merging this PR as it uses `MultiRequestFetcher`, which was significantly refactored in another PR

2023-03-13 09:43 UTC, cehali commented on packages/oracle-node/src/fetchers/dvol/DeribitFetcher.ts
> +export class DeribitFetcher extends MultiRequestFetcher {
It is already merged 😃

2023-03-13 10:36 UTC, hatskier requested changes
Can you please add ETHDVOL and

2023-03-13 10:36 UTC, hatskier commented on packages/oracle-node/manifests/single-source/deribit.json
> +{
Can you please add deribit metadata (e.g. logo) to config and add `ETHDVOL` and `BTCDVOL` to the main manifest

2023-03-14 14:17 UTC, hatskier requested changes

2023-03-14 14:17 UTC, hatskier commented on packages/oracle-node/src/fetchers/deribit/DeribitFetcher.ts
> +  makeRequest(id: string): Promise<AxiosResponse<DeribitResult>> {
Please add override here

2023-03-14 14:17 UTC, hatskier commented on packages/oracle-node/src/fetchers/deribit/DeribitFetcher.ts
> +  buildDeribitApiUrl = (id: string): string => {
Let's get rid of this function and not use this synthax with arrows in class methods

2023-03-15 10:39 UTC, hatskier requested changes

2023-03-15 10:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/deribit/DeribitFetcher.ts
> +  "https://test.deribit.com/api/v2/public/get_index_price?index_name=";
I would propose to remove `index_name` from the url here and put it later in params. IMO it will improve the readability

2023-03-15 10:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/deribit/DeribitFetcher.ts
> +      DERIBIT_CONFIG
I would replace it with
```js
return axios.get(DERIBIT_PRICES_URL, {
   headers: DERIBIT_REQUEST_HEADERS,
   params: { index_name:  `${id.toLowerCase()}_usdc`}
});
```

2023-03-15 12:35 UTC, hatskier approved these changes

2023-03-15 12:35 UTC, merged