chore: replaced yf-unofficial
redstone-finance/redstone-oracles-monorepo pull request #457
Opened 2023-03-16 21:45 UTC by rucinpk

2023-03-18 17:55 UTC, hatskier requested changes
Please don't apply fixes. Let's do it on a pair programming session

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/config/sources.json
> -  "ecb": {
Let's not remove ecb

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/tools/config/predefined-configs/sources.json
> -  "ecb": {
Let's not remove ecb

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +for (const key in symbolToId) {
Let's move it to a separate function

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +interface TwelveDataResult {}
Why do we need this type? It looks like `any`

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +    const item = getRequiredPropValue(symbolToId, id);
Please don't use the word `item` for variables

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +    acc: { priceSymbols: string[]; exchangeRateSymbols: string[] },
Do we really need this argument?

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +    if (item) {
Do we need this condition? Since we used `getRequiredPropValue` function

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +  buildList(endpoint: string, symbols: string[]) {
The name of this function is misleading. It prepared url postfix, does not build any list

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +  prepareRequestIds(requestedDataFeedIds: string[]): string[] {
I would simplify this function to return `["exchange_rate", "price"]` and would add the rest of logic to the makeRequest function

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +    for (const id in responses) {
We can use Object.values(responses) here

2023-03-18 17:55 UTC, hatskier commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +      const symbol = getRequiredPropValue(symbolToId, dataFeedId);
The name is misleading, as it is an object, not just a symbol

2023-04-19 16:35 UTC, hatskier approved these changes

2023-04-20 10:19 UTC, cehali commented on packages/oracle-node/manifests/dev/main-wide-support.json
>      "ZC=F": {
Do we want to leave the whole `yf-unoffical` fetcher for only one token?

2023-04-20 10:20 UTC, cehali commented on packages/oracle-node/src/fetchers/twelve-data/TwelveDataFetcher.ts
> +  extractPrices(response: any): PricesObj {
Maybe update type from `any`

2023-04-21 11:07 UTC, hatskier commented on packages/oracle-node/manifests/dev/main-wide-support.json
>      "ZC=F": {
It's not one, there are 25 of them

2023-04-21 11:28 UTC, cehali approved these changes

2023-04-21 11:28 UTC, merged