feat: [cache-service] make saves to bundlr and db independent
redstone-finance/redstone-oracles-monorepo pull request #478
Opened 2023-03-23 08:48 UTC by koonopek

Close #477

2023-03-23 08:53 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +  async saveMany(
This class sound like something that should abstract storage layer, so that is why I added this function. It is used twice by bulk endpoint and streamer listener.

2023-03-23 08:55 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +      .catch(() =>
Quite verbose code, however I didn't see added value in extracting it to new function to many questions started to come up

2023-03-23 08:56 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +      .catch(() =>
However I'm open to changes

2023-03-24 00:12 UTC, hatskier requested changes

2023-03-24 00:12 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +        .catch(() =>
Let's log error details here `.catch((err) => ...`

2023-03-24 00:12 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +      .catch(() =>
Let's log error details here please `.catch((err) => ...`

2023-03-24 00:12 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +      .catch(() =>
What do you think about creating a helpful function to wrap promises with log messages, e.g. smth like this
```js
// pseudo-code
const addLogs = (promise: Promise<void>, promiseName: string): Promise<void> => {
   return promise.then(() => console.log(`${promiseName} completed}).catch(err => console.err(`${promiseName} failed. ${stringifyErr(err)}`);
}
```

2023-03-27 08:00 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +      .catch(() =>
I agree good idea, however, I think that addLogs function should rethrow the error after logging it, and handling of the error should happen where business logic happens. Also, the name doesn't signalize that function will consume error.

2023-03-27 08:01 UTC, koonopek commented on packages/cache-service/src/utils/utils.ts
> +export function withLogging<T>(
Implementation after refactor

2023-03-27 10:51 UTC, hatskier approved these changes

2023-03-27 10:51 UTC, hatskier commented on packages/cache-service/src/utils/utils.ts
> +export function withLogging<T>(
Can we call it `runPromiseWithLogging`?

2023-03-27 11:12 UTC, merged