feat: add main dry run test
redstone-finance/redstone-oracles-monorepo pull request #487
Opened 2023-03-29 07:22 UTC by cehali

2023-03-29 11:22 UTC, hatskier requested changes

2023-03-29 11:22 UTC, hatskier commented on packages/integration/main-dry-run-test-core.sh
> +installAndBuild() {
Let's create a common shell lib

2023-03-29 11:22 UTC, hatskier commented on packages/integration/main-dry-run-test-core.sh
> +export MONOREPO_INTEGRATION_TEST=true
Let's try to get rid of the shell script and implement everything in JS test script

2023-04-19 13:53 UTC, hatskier commented on .github/workflows/oracle-tests.yml
> +          STLOUISFED_API_KEY: ${{ secrets.STLOUISFED_API_KEY }}
Can we add more api keys?
- Kaiko
- Twelve-data
- Coingecko PRO
- CMC

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +const TEN_MINUTES_IN_MILLISECONDS = 1000 * 60 * 30;
Maybe set it to 20 minutes to have more time reserve?

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +      .mockImplementation(() => new Promise((resolve) => resolve()));
Can't we use Promise.resolve() here as well?

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +  const runTestNode = async () => {
Can we move these functions before `beforeAll`?

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +    for (const _index of [...Array(iterationsCount).keys()]) {
Maybe switch to `for (let i = 0; i < iterationsCount; i++) {`?

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +    await runNodeMultipleTimes(4);
Can we add a comment why 4?

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/helpers.ts
> +  overrideManifestUsingFile: mainManifest,
Let's overwrite `sourceTimeout` to 10000 instead of 50000 to speed up dry-run tests in case of any source timeout

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +    expect(mockedBroadcaster).toHaveBeenCalledWith(
Let's try another approach with getting arg of `mockedBroadcaster` and then build a map (dataFeedId -> value) and then quick checking in a loop

2023-04-19 13:53 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +    for (const token of wideSupportTokens) {
I would propose to iterate over all tokens in main manifest and:
- log always in case of missing values
- require at least 95% of tokens from main manifest to have a valid value
- require all tokens from wide-support to have valid values

2023-04-21 00:24 UTC, hatskier commented on .github/workflows/oracle-tests.yml
> +          COINGECKO_API_URL: https://pro-api.coingecko.com/api/v3/simple/price
Don't you want to also put to github secrets?

2023-04-21 00:24 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +      we need price of another tokens f.g.
f.g -> e.g.

2023-04-21 00:24 UTC, hatskier commented on packages/oracle-node/test/dry-run/main-dry-run.spec.ts
> +const REQUIRED_MAIN_MANIFEST_TOKENS_PERCENTAGE = 0.95;
REQUIRED_MAIN... -> MIN_REQUIRED_MAIN...?

2023-04-21 06:48 UTC, cehali commented on .github/workflows/oracle-tests.yml
> +          COINGECKO_API_URL: https://pro-api.coingecko.com/api/v3/simple/price
It is a publicly known URL for Coingecko API, what is the advantage of putting it in GitHub secrets?

2023-04-21 11:27 UTC, hatskier approved these changes
Great job!

2023-04-21 11:27 UTC, merged