[oracle-node] make redstone Numbers great again
redstone-finance/redstone-oracles-monorepo pull request #495
Opened 2023-03-30 13:50 UTC by koonopek

* Current implementation is using Js Native numbers under the hood, to minimize the "change step" and because they are the fastest solution
* If we want to implement decimals, we should pass numbers in JSON as a string to avoid losing precision! (this requires changes across multiple components)
* This PR doesn't incorporate "RedstoneNumber" into fetchers logic 
* Some flaws of this solution are pointed as the comments

2023-04-17 09:57 UTC, koonopek commented on packages/oracle-node/.jest/set-redstone-number-config.js
> +        1: throwErr,
Js files, so Typescript Enum doesn't work here :(

2023-04-17 09:58 UTC, koonopek commented on packages/oracle-node/jest.config.ts
> +    "<rootDir>/.jest/set-redstone-number-config.js",
Set to throw error on every invalid number

2023-04-17 09:59 UTC, koonopek commented on packages/oracle-node/src/db/local-db/index.ts
> +  value: string;
I saw that this will be stored as "text" in sqlite anyway

2023-04-17 10:00 UTC, koonopek commented on packages/oracle-node/src/db/local-db/index.ts
> +export const getLastPrice = (
Own review: change it to always return string (no lost precision) let fetchers decide how he converts string to number or maybe some decimal

2023-04-17 10:00 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  private constructor(value: number) {
private thus, we have to use from

2023-04-17 10:04 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +    return this.unsafeToNumber();
In case of decimals we would loose here precision. However in this solution it is okey and have to be like this

2023-04-17 10:06 UTC, koonopek commented on packages/oracle-node/src/numbers/RedstoneNumber.ts
> +export interface RedstoneNumber {
Any suggestion to naming earlier was `PreciseNumber` however it is not so precise

2023-04-17 10:08 UTC, koonopek commented on packages/oracle-node/src/numbers/RedstoneNumberFactory.ts
> +export const N = (numberLike: NumberArg) =>
If we wan't to change impl just change JsNativeRedstoneNumber to anything implementing RedstonNumber

2023-04-17 10:09 UTC, koonopek commented on packages/oracle-node/src/types.ts
> +export type SanitizedPriceDataBeforeAggregation =
Sanitized values are using RedstonNumber

2023-04-17 10:12 UTC, koonopek commented on packages/oracle-node/test/numbers/JsNativeRedstoneNumber.spec.ts
> +        expect(result.toString()).toBe("200.25400000000002"); // with this implementation we we
Still things like this will happen, only using  decimals can prevent this

2023-04-19 08:50 UTC, cehali commented on packages/oracle-node/.jest/set-redstone-number-config.js
> +        1: throwErr,
But why it needs to be .js file?

2023-04-19 08:53 UTC, cehali commented on packages/oracle-node/src/aggregators/lwap-aggregator/get-liquidities.ts
> +import { N } from "../../numbers/RedstoneNumberFactory";
I am not a big fan of such shortcuts, it could be hard to understand what is going on without the context. Maybe `SafeNumber`?

2023-04-19 08:59 UTC, cehali commented on packages/oracle-node/src/db/local-db/index.ts
> +  value: string;
Not yet decided 😄

2023-04-19 09:00 UTC, cehali commented on packages/oracle-node/src/db/local-db/index.ts
> +export const getLastPrice = (
Values here are the same as already broadcasted. If the precision was lost it is already lost. I think we should have here number type for values as default

2023-04-19 09:04 UTC, cehali commented on packages/oracle-node/src/numbers/RedstoneNumber.ts
> +export interface RedstoneNumber {
`SafeNumber`?

2023-04-19 09:17 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +      );
Do we need this?

2023-04-19 09:23 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  private constructor(value: number) {
Could you elaborate more?

2023-04-19 09:31 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +      Math.abs(number.unsafeToNumber() - this.unsafeToNumber()) <
Why we don't use the `sub` function?

2023-04-19 09:35 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  private produceNewNumber(result: number) {
I feel like `produceNewNumber` and `from` could be merged into one function as it similar functionality

2023-04-19 09:36 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  toJSON(): number {
Do we need this function?

2023-04-19 09:37 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  unsafeToNumber(): number {
We can assume that the value is always valid as it is checked in the constructor. Maybe remove unsafe from the name?

2023-04-19 09:38 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  isOk = 0,
`= 0` is not necessary?

2023-04-19 09:42 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  return [NumberValidationResult.isOk, ""];
Maybe return object {result, message}

2023-04-19 09:53 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  private produceNewNumber(result: number) {
I think we can use only the `from` function. In all cases, we want to run `parseToSafeNumber` which the `JsNativeRedstoneNumber` constructor doesn't do. Also in `produceNewNumber` we ran `assertValidAndRound` twice, once in the constructor and then in the function itself.

2023-04-19 11:24 UTC, cehali commented on packages/oracle-node/test/numbers/JsNativeRedstoneNumber.spec.ts
> +        expect(result.toString()).toBe("200.25400000000002"); // with this implementation we we
The only solution is to multiply by 10 to the power of the number of decimals in order to operate on integers or is there any other solution to address this issue?

2023-04-19 15:06 UTC, koonopek commented on packages/oracle-node/.jest/set-redstone-number-config.js
> +        1: throwErr,
Heh, good point (i thought that it has to be cause set-env-vars.js). But it works when writtern in TS.

2023-04-19 15:10 UTC, koonopek commented on packages/oracle-node/src/db/local-db/index.ts
> +export const getLastPrice = (
Exactly!
That is why I postulated that we should broadcast prices as string, string can't lose precision :)
In case of DB it is easy fix and it is future proof solution (if we decide to use decimals implementation)

2023-04-19 15:18 UTC, koonopek commented on packages/oracle-node/src/numbers/RedstoneNumber.ts
> +export interface RedstoneNumber {
So no change?

2023-04-19 15:21 UTC, koonopek commented on packages/oracle-node/test/numbers/JsNativeRedstoneNumber.spec.ts
> +        expect(result.toString()).toBe("200.25400000000002"); // with this implementation we we
Yes that is one of the solution then we can use BigInt to represent an integer. Another solution is to use lib like decimal.js, however then we should also: `If we want to implement decimals, we should pass numbers in JSON as a string to avoid losing precision! (this requires changes across multiple components)`. There is also pretty big cost in performance, both in memory (20x) and cpu (200x)

2023-04-19 15:23 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +      );
Yes, cause we want to clone. Thus

```js
const a = new JsNativeRedstoneNumber(5);
const b = new JsNativeRedstoneNumber(a);
a===b => false
```

2023-04-19 15:39 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  unsafeToNumber(): number {
In case of this implementation that is totally true, however in other implementations that won't be true, and this name was introduced from the perspective of interface - `RedstoneNumber` - not concrete implementation

2023-04-19 15:39 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  isOk = 0,
Yes to handle positive result

2023-04-19 15:39 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  return [NumberValidationResult.isOk, ""];
Why not

2023-04-19 15:43 UTC, koonopek commented on packages/oracle-node/src/aggregators/lwap-aggregator/get-liquidities.ts
> +import { N } from "../../numbers/RedstoneNumberFactory";
Work for me, when we establish the name I will rename

2023-04-19 19:49 UTC, hatskier commented on packages/oracle-node/src/db/local-db/index.ts
> +export const getLastPrice = (
I agree, I also think that we should move to keeping strings in cache service DB instead of values. Let's do it as a separate task

2023-04-19 19:50 UTC, hatskier commented on packages/oracle-node/src/numbers/RedstoneNumber.ts
> +export interface RedstoneNumber {
Maybe SmartNumber?

2023-04-19 19:50 UTC, hatskier commented on packages/oracle-node/src/numbers/RedstoneNumber.ts
> +export interface RedstoneNumber {
or SafeNumber

2023-04-20 10:58 UTC, cehali commented on packages/oracle-node/src/numbers/RedstoneNumber.ts
> +export interface RedstoneNumber {
xD 
I wanted to write `RedstoneSafeNumber`

2023-04-20 11:01 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  isOk = 0,
I know why `isOk` is there but `= 0` seems unnecessary 😄

2023-04-20 11:08 UTC, cehali commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +  private produceNewNumber(result: number) {
I think I know why it was like that before. When adding two numbers the first one is already parsed and checked. For the second one, we are parsing and then through `assertValidAndRound` in the constructor we were checking if the second value is correct.

2023-04-24 11:04 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeRedstoneNumber.ts
> +      );
Valid point, thanks we can use a private  constructor here

2023-05-02 02:14 UTC, hatskier requested changes

2023-05-02 02:14 UTC, hatskier commented on packages/oracle-node/src/fetchers/PricesService.ts
> +        priceAfterAggregation.value.assertNonNegative();
Can you add a task to make this assertion optional (by setting a pram in manifest)?

2023-05-02 02:14 UTC, hatskier commented on packages/oracle-node/src/fetchers/PricesService.ts
> +        const valueFromSourceNum = SafeNumber(valueFromSource);
Shouldn't we add a word `new` each time we create a new instance of `SafeNumber`?

2023-05-02 02:14 UTC, hatskier commented on packages/oracle-node/src/numbers/SafeNumberFactory.ts
> +export const SafeNumber = (numberLike: NumberArg) =>
IMHO, If this function has a capital first letter it's easy to confuse it with a class. I would propose to rename it to smth like `createSafeNumber`

2023-05-02 09:39 UTC, koonopek commented on packages/oracle-node/src/fetchers/PricesService.ts
> +        const valueFromSourceNum = SafeNumber(valueFromSource);
Nope this is fabric method, I tried to follow JS convention as with `Number => Number(10)` or `BigInt(1000) for BigInt`

2023-05-02 09:40 UTC, koonopek commented on packages/oracle-node/src/numbers/SafeNumberFactory.ts
> +export const SafeNumber = (numberLike: NumberArg) =>
I tried to follow JS convention as with Number => Number(10) or BigInt(1000) for BigInt.
However, I can rename if you don't like it @cehali  what is your opinion

2023-05-02 09:42 UTC, koonopek commented on packages/oracle-node/src/fetchers/PricesService.ts
> +        priceAfterAggregation.value.assertNonNegative();
Done

2023-05-02 09:46 UTC, koonopek commented on packages/oracle-node/src/db/local-db/index.ts
> +    value: Number(lastPrices[symbol].value),
Of course, great catch

2023-05-02 09:47 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +  isOk = 0,
We don't have to

2023-05-02 09:51 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +export let JsNativeSafeNumberConfig = {
It can be modified in `setjsNatvieSafeNumberConfig`

2023-05-02 09:55 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +const parseToSafeNumber = (value: utils.NumberLike) => {
I would leave it as is, just for the seek for readability - `from` function would grow at least twice

2023-05-02 09:56 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +  isOk = 0,
Removed

2023-05-02 09:58 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +    return this;
agree

2023-05-02 10:02 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +  private produceNewNumber(result: number) {
done

2023-05-02 10:25 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +    const result = this._value + JsNativeSafeNumber.from(numberLike)._value;
Why you think it's not a good pratice? It is always one function call less, and in my opinion it is more readable

2023-05-02 10:43 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +export const setJsNativeSafeNumberConfig = (
Good point, will do

2023-05-02 10:46 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +      this._value <=
I like this `return this.lt(numberArg) || this.eq(numberArg)` (my first impl)

2023-05-02 10:46 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +      this._value >=
same as in lite :)

2023-05-02 10:49 UTC, koonopek commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +      typeof numberLike === "number" ||
I don't have an opinion on style, but if use `["number", "string"].includes(typeof numberLike)` then typescript compiler doesn't recognize that function indeed has to be string or number and we get type error

2023-05-02 10:52 UTC, koonopek commented on packages/oracle-node/src/numbers/SafeNumberFactory.ts
> +export const SafeNumber = (numberLike: NumberArg) =>
Done, because @cehali  is on vacation :)

2023-05-07 21:24 UTC, hatskier commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +      typeof numberLike === "number" ||
Gotcha

2023-05-07 21:26 UTC, hatskier commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +    const result = this._value + JsNativeSafeNumber.from(numberLike)._value;
I think it's OK for the objects, on which the mthod is called, but you are referring to it in another (external) object here `JsNativeSafeNumber.from(numberLike)._value`

2023-05-07 21:28 UTC, hatskier commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +const parseToSafeNumber = (value: utils.NumberLike) => {
Ok

2023-05-07 21:58 UTC, hatskier commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +      return new JsNativeSafeNumber(numberLike._value);
IMO it's not very nice to use a private property of an external object

2023-05-07 21:58 UTC, hatskier commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +      this._value < JsNativeSafeNumber.from(numberArg)._value ||
Why not lt?

2023-05-07 21:58 UTC, hatskier commented on packages/oracle-node/src/numbers/JsNativeSafeNumber.ts
> +      this._value > JsNativeSafeNumber.from(numberArg)._value ||
Why not gt?

2023-05-07 21:58 UTC, hatskier commented on packages/oracle-node/src/utils/numbers.ts
> +    // TODO: make it more generic
What do you mean here? Can you do it within this PR?

2023-05-10 09:42 UTC, merged