chore: add Canto testnet deployed config
redstone-finance/redstone-oracles-monorepo pull request #497
Opened 2023-03-30 15:29 UTC by cehali

2023-04-06 15:50 UTC, hatskier requested changes

2023-04-07 07:04 UTC, cehali commented on packages/on-chain-relayer/deployed-config/canto-testnet.json
> +  "CANTO_PRICE_FEED": "0x6E27A25999B3C665E44D903B2139F5a4Be2B6C26",
Fixed

2023-04-13 23:27 UTC, hatskier approved these changes

2023-04-13 23:27 UTC, hatskier commented on packages/on-chain-relayer/deployed-config/canto-testnet.json
> +  "priceFeeds": {
Maybe `priceFeeds` -> `PRICE_FEEDS` for consistency? I know, that I proposed current version, sorry 😄

2023-04-14 07:40 UTC, merged