feat: remove hardhat from relayer code
redstone-finance/redstone-oracles-monorepo pull request #499
Opened 2023-03-30 16:21 UTC by cehali

2023-03-31 12:51 UTC, koonopek approved these changes
Overall looks good! 
I'm only wondering if we could tune typescript to work with hardhat, but you have probably tried :)

2023-04-03 08:39 UTC, koonopek commented on packages/on-chain-relayer/test/relayer/update-prices.test.ts
> +    (getProviderOrSigner as any).getProvider = () => ethers.provider;
I see I will have to add in my PR anyway

2023-04-03 19:14 UTC, hatskier reviewed
Please wait before merging this

2023-04-03 21:15 UTC, hatskier requested changes

2023-04-03 21:15 UTC, hatskier commented on packages/on-chain-relayer/scripts/mento/deploy-mock-sorted-oracles.ts
> +export const deployMockSortedOracles = async (signer?: Signer) => {
IMO this is not a script and should not be located in the scripts folder. Script should be executable, but this file just exports a function

2023-04-03 21:15 UTC, hatskier commented on packages/on-chain-relayer/src/custom-integrations/mento/mento-utils.ts
> -export const deployMockSortedOracles = async (signer?: Signer) => {
IMO this is a good location for this function

2023-04-04 06:51 UTC, cehali commented on packages/on-chain-relayer/src/custom-integrations/mento/mento-utils.ts
> -export const deployMockSortedOracles = async (signer?: Signer) => {
But it is not used anywhere in files from the src folder. It is only used in one script and tests.

2023-04-05 06:49 UTC, merged