feat: add permaswap fetcher
redstone-finance/redstone-oracles-monorepo pull request #517
Opened 2023-04-06 10:46 UTC by famouscat8

2023-04-11 12:26 UTC, cehali commented on packages/oracle-node/manifests/data-services/main.json
We don't use an automatic script for generating the main manifest as it provides too many changes. Please add new tokens manually.

2023-04-11 12:26 UTC, cehali commented on packages/oracle-node/manifests/data-services/main.json
We don't use an automatic script for generating the main manifest as it provides too many changes. Please add new tokens manually.

2023-04-12 11:10 UTC, ethever commented
thanks for reviewing. I have updated my pull request to address the requested changes.

2023-04-15 14:16 UTC, ethever commented
any person help pls

2023-04-20 13:07 UTC, cehali requested changes
Details in comments

2023-04-23 07:46 UTC, ethever commented
Thanks for reviewing. I have updated my pull request to address the requested changes.

2023-04-23 08:27 UTC, ethever commented
Thanks for reviewing. I have updated my pull request to address the requested changes.

2023-04-26 16:07 UTC, koonopek commented on packages/oracle-node/test/fetchers/permaswap.spec.ts
> +describe("permaswap fetcher", () => {
Please add also tests for failing paths like:
- missing value in db
- missing expected key in response from permaswap router
- permaswap router not answering

2023-04-26 16:07 UTC, koonopek submitted a review, later dismissed

2023-04-26 16:07 UTC, koonopek commented on packages/oracle-node/test/fetchers/permaswap.spec.ts
> +describe("permaswap fetcher", () => {
Please add also tests for failing paths like:
- missing value in db
- missing expected key in response from permaswap router
- permaswap router not answering

2023-04-27 09:05 UTC, cehali commented on packages/oracle-node/src/fetchers/permaswap/example-pool-list-response.json
> +{
I think this file is not necessary in the code base

2023-04-27 09:05 UTC, cehali commented on packages/oracle-node/test/fetchers/permaswap.spec.ts
> +    // Given
You can remove those comments, I know they are in some files but they are not very informative

2023-04-27 09:06 UTC, cehali submitted a review, later dismissed
Minor changes in comments and please add additional tests

2023-05-08 00:41 UTC, hatskier approved these changes
Approved with a minor comment, will merge after fixing

2023-05-08 00:41 UTC, hatskier commented on packages/oracle-node/src/fetchers/permaswap/PermaswapFetcher.ts
> +    console.error({ assetId, lastPriceFromCache });
Can you please remove this console.error? Or use the this.logger.error instead?

2023-05-08 00:41 UTC, hatskier commented on packages/oracle-node/src/fetchers/permaswap/PermaswapFetcher.ts
> +    console.error({ assetId, lastPriceFromCache });
I think it's better to remove :)

2023-05-08 09:36 UTC, ethever commented
Thanks for reviewing. I have updated my pull request to address the requested changes.

2023-05-12 09:06 UTC, ethever commented
any progress?

2023-05-14 13:11 UTC, hatskier approved these changes

2023-05-14 13:14 UTC, merged