feat: replace LevelDB with SQLite
redstone-finance/redstone-oracles-monorepo pull request #520
Opened 2023-04-06 14:09 UTC by cehali

2023-04-07 11:29 UTC, koonopek commented
Sorry for the interruption :) 
But maybe it would be profitable to use SQLite in WAL mode, is more efficient in this type of cases:
https://www.sqlite.org/wal.html
Code how to enable it using `knex`:
```js
  const nodeDb = knex({
    client: "better-sqlite3",
    connection: {
      filename: `sqlite/node.sqlite`,
    },
    useNullAsDefault: true,
    pool: {
      afterCreate: (conn, cb) => {
        // https://github.com/knex/knex/issues/4971#issuecomment-1030701574
        conn.pragma("journal_mode = WAL");
        cb();
      },
    },
  });
  ``

2023-04-14 00:41 UTC, hatskier requested changes

2023-04-14 00:41 UTC, hatskier commented on packages/oracle-node/src/db/local-db/index.ts
>  export const getPrices = async (
Should it be async?

2023-04-14 07:44 UTC, cehali commented on packages/oracle-node/src/db/local-db/index.ts
> +const CREATE_TABLE_STATEMENT = `CREATE TABLE IF NOT EXISTS ${PRICES_TABLE} (symbol TEXT, prices TEXT)`;
Because it is stringified array of prices from the last 15 minutes. Sqlite doesn't have an array type and if we want to go with each row as a new price we will have to add some background process to delete prices older than 15 minutes.

2023-04-14 07:50 UTC, cehali commented on packages/oracle-node/src/db/local-db/index.ts
>  export const getPrices = async (
Nope, it is not async: https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#close---this

2023-04-14 08:25 UTC, cehali commented on packages/oracle-node/src/db/local-db/index.ts
> +const getSelectBySymbolStatement = (symbols: string[]) =>
It is how SQLite works, we need a placeholder for each symbol we want to retrieve. It doesn't work with join array as a single string passed to the query, more info: https://github.com/WiseLibs/better-sqlite3/issues/125#issuecomment-1190753970.

2023-04-17 10:46 UTC, hatskier commented on packages/oracle-node/src/db/local-db/index.ts
> +  const valuesForSymbols: ReturnPricesFromDb = statement.all(symbols);
I think we need to do performance benchmarks to verify is the sync operations on sqlite (with AWS ECS + EFS) will not slow down the oracle-node

2023-06-22 08:28 UTC, closed without merging