feat: implemented ethereum contracts
redstone-finance/redstone-oracles-monorepo pull request #53
Opened 2022-09-18 17:53 UTC by hatskier

2022-10-06 09:00 UTC, cehali commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +    if (dispute.revealedForGuiltyAmount > dispute.revealedForNotGuiltyAmount) {
Maybe I am missing something but those amounts are based on `lockedTokensAmount` during voting. This could mean that someone is able to bail out the guilty provider by providing a large `lockedTokensAmount` when voting for not guilty.

2022-10-06 11:07 UTC, cehali commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +    require(dispute.verdict != DisputeVerdict.Unknown, "Dispute has not been sttled yet");
sttled -> settled

2022-10-06 11:09 UTC, cehali commented on packages/eth-contracts/test/dispute-resolution-engine.test.ts
> +import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
Can we write tests that check time constraints for disputes?

2022-10-13 13:24 UTC, jakub-wojciechowski requested changes

2022-10-13 13:24 UTC, jakub-wojciechowski commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    _stakingToken.transfer(msg.sender, amountToUnstake);
Let's also reset pendingAmountToUstake before calling external function (protect against recursive call). 
Just in case I'll add nonReetrant modifier to all external functions.

2022-10-13 13:24 UTC, jakub-wojciechowski commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    _stakingToken.transfer(msg.sender, amountToUnstake);
Let's check the results of the transfer function and revert if it's not true.

2022-10-13 13:24 UTC, jakub-wojciechowski commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +  function getStakedBalance(address addr) public view returns (uint256) {
This is important. I'm not sure if we should include pendingForUnstake tokens in staked balance. 
We're checking the balance in dispute resolution and it might be unstaked before the dispute ends.

2022-10-13 13:24 UTC, jakub-wojciechowski commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +  function slashStake(address slashedAddress, uint256 slashedAmount) public {
It's a good question if we should allow to slash as much as possible or revert if there is not enough tokens (I'm not sure which one is better)

2022-10-13 13:24 UTC, jakub-wojciechowski commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    _stakingToken.transfer(msg.sender, slashedAmount);
Let's check the results of transfer - it might fail.

2022-10-13 13:24 UTC, jakub-wojciechowski commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    require(msg.sender == _authorisedStakeSlasher, "Tx sender is not authorised to slash stakes");
It's a common practice to use modifier for this purpose

2022-10-13 13:24 UTC, jakub-wojciechowski commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    address authorisedStakeSlasher,
I'm wondering if we should keep the authorisedStakeSlasher open to change - or at least keep the whole contract upgradeable.

2022-10-13 15:40 UTC, hatskier commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +  ) external {
But we do this, since we find the vote using msg.sender

2022-10-13 15:47 UTC, hatskier commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +    Dispute storage dispute = _disputes[disputeId];
If it doesn't exist, execution will revert with "Array accessed at an out-of-bounds or negative index"

2022-10-13 16:09 UTC, hatskier commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +      _votes[disputeId][msg.sender].lockedTokensAmount == 0,
It will revert with "Array accessed at an out-of-bounds or negative index"

2022-10-13 16:09 UTC, hatskier commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    address authorisedStakeSlasher,
Good idea, I will make the contract upgradeable

2022-10-13 16:09 UTC, hatskier commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +  function stake(uint256 stakingAmount) external {
Can you please describe the case when it can be used?

2022-10-13 16:09 UTC, hatskier commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    _stakingToken.transfer(msg.sender, amountToUnstake);
Wouldn't the `transfer` function just revert in case of any problems with the transfer?

2022-10-13 16:45 UTC, hatskier commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +    bytes32 expectedCommitHash = calculateHashForVote(disputeId, salt, votedForGuilty);
Good catch! I will add another hardcoded salt to the calculateHashForVote function :)

2022-10-13 16:48 UTC, hatskier commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +      if (availableStakedBalance >= PENALTY_AMOUNT) {
Ok, we can slash min(PENALTY_AMOUNT, availableStakedBalance)

2022-10-13 16:57 UTC, hatskier commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +    require(
After the discussion we deiced to add here an additional require statement checking if the `lockedTokensAmount` is greater than 0

2022-10-13 18:01 UTC, hatskier commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +  function getStakedBalance(address addr) public view returns (uint256) {
I will rename this function to "getMaxSlashableAmount"

2022-10-13 18:03 UTC, hatskier commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    UserStakingDetails storage userStakingDetails = _stakingDetailsForUsers[slashedAddress];
I will use getMaxSlashableAmount function instead

2022-10-19 15:51 UTC, hatskier commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +  function stake(uint256 stakingAmount) external {
We decided to skip it

2022-10-19 15:59 UTC, hatskier commented on packages/eth-contracts/contracts/StakingRegistry.sol
> +    UserStakingDetails storage userStakingDetails = _stakingDetailsForUsers[slashedAddress];
Though, I won't, because userStakingDetails is used to update stakedAmount below :)

2022-10-20 21:48 UTC, hatskier commented on packages/eth-contracts/contracts/DisputeResolutionEngine.sol
> +      }
Then we will slash what we can :)

2022-10-24 10:43 UTC, jakub-wojciechowski approved these changes

2022-10-24 13:04 UTC, merged