feat: implement same timestamps feature in cache service
redstone-finance/redstone-oracles-monorepo pull request #549
Opened 2023-04-18 15:45 UTC by koonopek

2023-04-18 15:47 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +    for (let i = 0; i < dataPackagesWithSameTimestamp.count; i++) {
ugly bust fast ~5ms

2023-04-18 15:49 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +        $sort: { count: -1, timestamp: -1 },
So we take the "group" which contains the biggest number of packages if two groups contains the same value of packages we take the newer one.

It is an important piece of code. We could also take the newest pacakge if it doesnt deviate more then 2 dataFeeds or some other custom logic @hatskier  what do you think.

I would also want to test it on prod db and compare with production cache services

2023-04-19 12:13 UTC, koonopek commented
Sorry for force push, however I fucked my git locally and had to do it

2023-04-19 13:49 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +        $sort: { count: -1, timestamp: -1 },
However in the scenario where we have 18 data packages (in 3 MIN interval). And for example, the 18th packages (oldest) contain the most number of dataFeeds, we will select this one and thus serve old data. If losing data feeds between node iterations never occurs, then this is not the issue.

To solve this potential issue we could ALWAYS select the second group (second timestamp). Or the first one if dataFeedId.count is the same in the first and second (all datapacakges for given timestamp are already in the database so the is no need to wait pick the older one).

@hatskier WDYT?

2023-04-19 21:52 UTC, hatskier requested changes

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +    return this.dataPackagesService.getLatestDataPackagesWithCache(
It's not so clear how `Latest` is different from `MostRecent` 😅
Can we rename the function to smth like `getLatestDataPackagesWithSameTimestampWithCache`. I know the name is long, but IMO it will still be better and more readable than now

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  @Get("most-recent/:DATA_SERVICE_ID")
Maybe change `most-recent` to smth like `latest-not-aligned-by-time`? WDYT?

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +    return await this.dataPackagesService.queryLatestDataPackages(
Why do you change this endpoint in this PR?

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> -    // Checking if data packages for this data service are
Just curious, why have you decided to remove this comment?

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +          dataServiceId: { $first: "$dataServiceId" },
Do we really need this line `dataServiceId: { $first: "$dataServiceId" },`? I think we we already know the value we'll receive (because of the $match statement above

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +          count: { $count: {} },
Do we really need to count in on the DB level? Can't we do counting and sorting on the JS side?

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +        $sort: { count: -1, "_id.timestampMilliseconds": -1 },
Can we do sorting on the JS side to decrease load on DB?

2023-04-19 21:52 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +        $sort: { count: -1, "_id.timestampMilliseconds": -1 },
I am not sure if it's a better option actually. But would be cool to discuss it

2023-04-20 06:45 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +    return await this.dataPackagesService.queryLatestDataPackages(
This is the same endpoint as `latest` thus I wanted to be consistent, by this I mean "every GET `/latest` should work the same"

2023-04-20 06:47 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> -    // Checking if data packages for this data service are
Cause it precisely describes what 2 lines of code are doing, I don't see the added value in this comment.
Also I have introduced a similar function, and repeating this comment would have sens in my opinion so I have deleted it in two places.

2023-04-20 06:49 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +          dataServiceId: { $first: "$dataServiceId" },
Good point!

2023-04-20 07:01 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +          count: { $count: {} },
This is always an option :) But lets discuss:

The cons:
1. DBs are optimized for this kind of operation (use better runtime then node).
2. They are easier to scale than services
3. Reduce the amount of data that has to be sent over the wire by 18 times in this case
4. Increase load on service (also this is blocking operation so when server will be manipulating data he won't be able to )
The pros:
1.  Decrease load on DB.

When I have disabled counting sorting and limit, the query executes in ~380ms so is almost 2 times slower (200ms). Probably cause of the data volume send. (tested on WIFI in our biuro)

2023-04-20 07:01 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +        $sort: { count: -1, "_id.timestampMilliseconds": -1 },
Answered here: https://github.com/redstone-finance/redstone-oracles-monorepo/pull/549#discussion_r1172162664

2023-04-20 07:03 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +  @Get("most-recent/:DATA_SERVICE_ID")
Totally, I was having some hard time with this names :)

2023-04-20 07:04 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.controller.ts
> +    return this.dataPackagesService.getLatestDataPackagesWithCache(
Agree

2023-04-20 09:55 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +          count: { $count: {} },
I am convinced, didn't take into account the 3rd point before, but now noticed the limit: 1. So it makes much more sense

2023-04-20 09:57 UTC, merged

2023-04-20 10:00 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +        $sort: { count: -1, timestamp: -1 },
I think it will never be the case that 18th timestamp has the biggest number of packages