feat: make more params optional in data-service-wrapper
redstone-finance/redstone-oracles-monorepo pull request #574
Opened 2023-04-24 09:57 UTC by koonopek

2023-04-24 09:58 UTC, koonopek commented on packages/protocol/src/data-services-urls.ts
> +};
All examples, however KydService was missing in examples

2023-04-24 10:45 UTC, koonopek commented on packages/evm-connector/contracts/data-services/RedstoneDataServiceConsumer.sol
> +abstract contract RedstoneDataServiceConsumer is RedstoneConsumerNumericBase {
New abstract class for dataServices

2023-04-26 09:45 UTC, cehali commented on packages/evm-connector/contracts/data-services/RedstoneDataServiceConsumer.sol
> +abstract contract RedstoneDataServiceConsumer is RedstoneConsumerNumericBase {
We don't need to new abstract class to add one minor function. Maybe we could add it to `RedstoneConsumerBase`. We don't plan not to use data service id anywhere.

2023-04-26 09:56 UTC, cehali commented on packages/evm-connector/src/wrappers/BaseWrapper.ts
> +    this.contract = contract;
Is it used somewhere outside this function?

2023-04-26 09:58 UTC, koonopek commented on packages/evm-connector/src/wrappers/BaseWrapper.ts
> +    this.contract = contract;
yes

2023-04-26 09:58 UTC, koonopek commented on packages/evm-connector/src/wrappers/BaseWrapper.ts
> +    this.contract = contract;
To fetch dataServiceId from this.contract

2023-04-26 10:01 UTC, koonopek commented on packages/evm-connector/contracts/data-services/RedstoneDataServiceConsumer.sol
> +abstract contract RedstoneDataServiceConsumer is RedstoneConsumerNumericBase {
Hmm I think that it could make confusion to developers which will try extend `RedstoneConsumerNumericBase` because they will have to override this method and it could be problematic for them to decide which value to use.
However if you think that this is not an issue I can add it to RedstoneConsumerBase

2023-04-26 11:56 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +type Optional<T, K extends keyof T> = Omit<T, K> & {
Maybe use `Partial` type: https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype?

2023-04-26 11:57 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    >,
Why not `DataPackagesRequestInput`?

2023-04-26 11:57 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +  private readonly dataPackagesRequestParams: Optional<
Why it is different than `dataPackagesRequestParams` and `DataPackagesRequestInput`?

2023-04-26 11:58 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +  >;
Why it is different than `dataPackagesRequestParams` and `DataPackagesRequestInput`?

2023-04-26 11:58 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +  >;
Ohhh, I see

2023-04-26 11:59 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +const DEFAULT_UNIQUE_SIGNERS_COUNT = 2;
I am not sure 2 is the best choice here. In the prod env we have 3 out of 5 nodes and in dev we have only 1 node per data service.

2023-04-26 12:05 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      this.dataPackagesRequestParams.dataServiceId as string
I would leave it as the default type and add undefined as possible type to `resolveDataServiceUrls`. There you have to check to throw an error if we don't find the URL.

2023-04-26 13:15 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +type Optional<T, K extends keyof T> = Omit<T, K> & {
Partial make all Properties optional, `Optional` make only given properties Optional

2023-04-26 13:19 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      this.dataPackagesRequestParams.dataServiceId as string
I would leave it as is, it is more type safe (better to catch something in compiler error then in runtime or tests)
In this case, the developer must explicitly say that something is a string. 
And `undefined|null` is not valid input to `resolveDataServicesUrls` of course, if it is used only in this place this is not a difference, but this function can be also used somewhere else.

2023-04-26 13:24 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +type Optional<T, K extends keyof T> = Omit<T, K> & {
Ohh but you are right we are actually making all fields optional here, good point, will fix

2023-04-26 13:36 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +const DEFAULT_UNIQUE_SIGNERS_COUNT = 2;
Yeah, good point! Will do

2023-04-27 08:52 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      this.dataPackagesRequestParams.dataServiceId as string
iIf we call `urls()` before `getUnsignedMetadata()`  `dataServiceId` would be undefined. In theory it shouldn't happen but could be misleading in the future. Maybe we should store URLs as class variable and just use it in `getUnsignedMetadata` without storing it? `resolveDataServiceUrls` is just getting from the object so we could run it every time

2023-04-27 08:53 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      uniqueSignersCount: DEFAULT_UNIQUE_SIGNERS_COUNT,
I think we can remove `DEFAULT_UNIQUE_SIGNERS_COUNT` completely and handle it the same as dataServiceId, I believe it is already handled that way.

2023-04-27 08:56 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      uniqueSignersCount: DEFAULT_UNIQUE_SIGNERS_COUNT,
true

2023-04-27 08:59 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      this.dataPackagesRequestParams.dataServiceId as string
You mean `getBytesDataForAppending()` not `getUnsignedMetadata()`?

2023-04-27 09:03 UTC, cehali commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      this.dataPackagesRequestParams.dataServiceId as string
yes `getBytesDataForAppending`

2023-04-27 10:55 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    const { urls } = await this.loadDefaultParams();
Hack for typscript cause:
`When you check or assert the type of some value so as to narrow its apparent type, the compiler uses control flow analysis to keep track of where and when such a narrowing should apply. But this analysis only works inside a single function scope. It does not cross function boundaries.`
Thanks @cehali for reference

2023-04-28 13:32 UTC, hatskier requested changes

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/contracts/data-services/CustomUrlsConsumerBase.sol
> +  function getAuthorisedSignerIndex(
Please avoid doing formatting changes in contracts

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/contracts/data-services/KydServiceConsumerBase.sol
> +  function getAuthorisedSignerIndex(
Please don't modify formatting

2023-04-28 13:32 UTC, hatskier commented on packages/protocol/src/data-services-urls.ts
> +export const REDSTONE_DATA_SERVICES_URLS: Record<string, string[]> = {
IMO these URLs should be placed in sdk, not in the protocol

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/src/wrappers/BaseWrapper.ts
> +  protected contract!: Contract;
Why exclamation mark?

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    private urls?: string[]
Just an idea: WDYT about keeping urls also in DataPackagesRequestParams to have only one object with optional and non-optional params?

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    return { ...this.dataPackagesRequestParams, urls: this.urls };
Why do we return the object if we only use urls?

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      this.dataPackagesRequestParams.dataServiceId =
IMHO it's not very readable when function for loading params also produces side effects (like updating few props of `dataPackagesRequestParams`).

Maybe we can rename it so it indicates what it does (e.g. `setDefaultParamsIfNeeded`)

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    try {
I would propose to have only one `try .. catch`, e.g. in the `loadDefaultParams` and here I would implement only "unsafe" logic of fetching details from the contract

2023-04-28 13:32 UTC, hatskier commented on packages/evm-connector/contracts/core/RedstoneConsumerBase.sol
> +    return "";
I would propose to revert here with an error, as we consider "" as invalid value, so maybe we can simply throw the error here

2023-04-28 13:41 UTC, koonopek commented on packages/protocol/src/data-services-urls.ts
> +export const REDSTONE_DATA_SERVICES_URLS: Record<string, string[]> = {
<img width="742" alt="image" src="https://user-images.githubusercontent.com/24699136/235163663-af1c6b4e-fa58-48ff-ba75-784620a55325.png">
:)

2023-04-28 13:56 UTC, koonopek commented on packages/evm-connector/contracts/core/RedstoneConsumerBase.sol
> +    return "";
Good idea done

2023-04-28 13:58 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    private urls?: string[]
This is also used in differnet places where urls is not required, however I can add it to urls

2023-04-28 14:05 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    try {
Then we miss more precise error message

2023-05-02 07:12 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    try {
We don't know exactly which param we cant fetch

2023-05-02 07:12 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +      this.dataPackagesRequestParams.dataServiceId =
Valid point, refactored

2023-05-02 07:13 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    return { ...this.dataPackagesRequestParams, urls: this.urls };
I have refactored this function

2023-05-02 07:13 UTC, koonopek commented on packages/evm-connector/src/wrappers/BaseWrapper.ts
> +  protected contract!: Contract;
To tell typescript compiler that this function will be for sure initialized (but outside of constructor)

2023-05-02 07:32 UTC, koonopek commented on packages/protocol/src/data-services-urls.ts
> +export const REDSTONE_DATA_SERVICES_URLS: Record<string, string[]> = {
But I also think that it more fits in SDK :)

2023-05-02 08:32 UTC, koonopek commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    private urls?: string[]
Changed my mind and done as you suggested

2023-05-02 08:33 UTC, koonopek commented on packages/protocol/src/data-services-urls.ts
> +export const REDSTONE_DATA_SERVICES_URLS: Record<string, string[]> = {
moved

2023-05-07 21:45 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    try {
I think we can remove the case with checking if the data service id has been overriden if we revert with error if it's not. I think we can still throw an error inside these functions, but have only a single try .. catch block in the function that uses all of them. Let's discuss it in person :)

2023-05-07 22:14 UTC, hatskier commented on packages/evm-connector/contracts/core/RedstoneConsumerBase.sol
> +    revert("getDataServiceId not implemented");
Let's use custom errors to be consistent with the rest of the code

2023-05-07 22:14 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    const fetchedParams = {} as Required<DataPackagesRequestInput>;
Why do you set it as `Required<DataPackagesRequestInput>`, despite it can not have this type?

2023-05-07 22:14 UTC, hatskier commented on packages/sdk/src/data-services-urls.ts
> +export function resolveDataServiceUrls(dataServiceId: string): string[] {
Why `function` notation, not the fancy one (with arrows)?

2023-05-08 13:38 UTC, hatskier commented on packages/evm-connector/src/wrappers/DataServiceWrapper.ts
> +    try {
Okay, I see the value of more etailed error messages for end developers

2023-05-11 11:59 UTC, hatskier approved these changes

2023-05-11 12:00 UTC, merged