integration tests classic model
redstone-finance/redstone-oracles-monorepo pull request #592
Opened 2023-05-03 10:50 UTC by rpiszczatowski

2023-05-03 13:57 UTC, hatskier requested changes

2023-05-03 13:57 UTC, hatskier commented on .github/workflows/monorepo-integration-tests.yml
> +  classic:
Would the tests run in parallel? If not, I would propose to separate these 2 files

2023-05-03 13:57 UTC, hatskier commented on .github/workflows/monorepo-integration-tests.yml
> +  classic:
This looks a bit misleading

<img width="491" alt="Screenshot 2023-05-03 at 15 45 19" src="https://user-images.githubusercontent.com/48165439/235934428-d42c7720-01bb-4b3b-b919-8cbfdd2693a8.png">

2023-05-03 13:57 UTC, hatskier commented on packages/integration/integration-test-classic.sh
> +lazilyInstallNPMDeps() {
What do you think about moving duplicated functions to a separate bash file and includng it using the `source` command on top?

2023-05-03 13:57 UTC, hatskier commented on packages/on-chain-relayer/.gitignore
> +adapter_contract_address.txt
Can you rename to `adapter-contract-address` and use dashes instead of underscores to be consistent with other filenames?

2023-05-03 13:57 UTC, hatskier commented on packages/on-chain-relayer/contracts/mocks/PriceFeedsAdapterWithoutRoundsMock.sol
> +    return 1;
Let's please create a separate contract file for the integration test in the same way we do it in evm-connector and core tests

2023-05-03 13:57 UTC, hatskier commented on packages/on-chain-relayer/test/monorepo-integration-tests/deploy-adapter.ts
> +import { ethers } from "hardhat";
Let's use `scripts` folder for this file as it's a hardhat script,  not a test

2023-05-03 13:57 UTC, hatskier commented on packages/on-chain-relayer/test/monorepo-integration-tests/verify-prices.ts
> +import { expect } from "chai";
I would also make a hardhat script from this file as it's not a normal isolated test, because there is an interaction with already deployed contract. We can still use `expect` in a hardhat script

2023-05-11 09:48 UTC, rpiszczatowski commented on .github/workflows/monorepo-integration-tests.yml
> +  classic:
Separate jobs by default run in parallel, so yes.
I'll adjust the naming.

2023-05-11 10:16 UTC, koonopek commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
Sorry for the interrupt, but why we are not writing this kind of tests in Node.js.
I think that in long term it will be hard to maintain them, and oh boy we want to maintain them :)

2023-05-11 10:31 UTC, rpiszczatowski commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
This is a rather philosophical question :) The main argument is that the primary job done by the script is to start all the components in the background, schedule some 'standard' tasks they perform and then run some verifications on the state of those components and then clean up. As far as I am concerned, the best tools for such a work are scripting languages. Also, please note that for tasks strictly related to interacting with our components I used hardhat, and the code is written in typescript (deploying contract, on-chain prices verification). If we have more interactions with the system they will be written in TS and only started from this shell script.
And the other argument is that tests for the core component were already written in bash :)

Having said that, I am open to switching to Node.js even though I am less experienced with this tool compared to bash.

2023-05-11 10:51 UTC, koonopek commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
What is a script is rather a philosophical question :) java__SCRIPT__ :) (JOKING)

In my opinion, maintaining a bash code base is more difficult compared to TS. When using oracle-ci-node, we encountered problems with processes that were not being terminated, a situation that would have been easier to catch in JS. Additionally, adding new assertions would be simpler using JS. ( I think I'm repeating myself sorry)

(PS. I use JS TS interchangeably)

2023-05-12 15:01 UTC, rpiszczatowski commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
resolving as non-conclusive at the moment. We can discuss it further in a broader group.

2023-05-16 08:37 UTC, koonopek commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
@hatskier @cehali @Lukasz2891 what do you think?

2023-05-17 08:20 UTC, cehali commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
I remember that Alex had some good reasons why he didn't want to do this in node.js but I am not sure what was it 😄

2023-05-17 09:15 UTC, Lukasz2891 commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
The question #0 - why don't we use a prepared `.env` file instead of copying `.env.example` and setting then the variables in the script? 

For example `.env.on-chain-relayer` with filled values could be attached to the invocation of the node/yarn script, I think ;) Couldn't it? It sth related to `NODE_ENV` variable, but I'm not sure it completely transparent or it's needed to have a piece of code in a `.ts' file to read it.

2023-05-17 09:21 UTC, Lukasz2891 commented on packages/integration/integration-test-classic.sh
> +#!/bin/bash
Shell is nothing special for me. I use `Makefile`s :D The main advantage of using shell is that we don't need `node` installed on a machine the tests are running on. But we do it for running the tests anyway...

So for me, for now, the argument "we have sth working" is totally ok too ;)

2023-05-30 14:04 UTC, hatskier requested changes

2023-05-30 14:04 UTC, hatskier commented on packages/integration/integration-test-classic.sh
> +  sleep 10 # wait for hardhat to start blockchain instance
I would propose to implement some kind of active waiting, because it's possible that hardhat will not launch a local blockchain instance on a slower machine and the tests will fail in a non-deterministic way

2023-05-30 14:04 UTC, hatskier commented on packages/integration/integration-test-classic.sh
> +  sleep 15 # wait for relayer to put data on-chain
Same, I would propose to avoid sleep commands with hardcoded time

2023-05-30 14:04 UTC, hatskier commented on packages/on-chain-relayer/test/monorepo-integration-tests/scripts/deploy-adapter.ts
> +import fs from "fs";
Can we rename this file so it indicates that it deploys mock adapter for integration tests

2023-05-30 14:04 UTC, hatskier commented on packages/on-chain-relayer/test/monorepo-integration-tests/scripts/verify-prices.ts
> +import { ethers } from "hardhat";
Can you please rename this script so it indicates that it is used in monorepo integration tests. You can also add few details in the comments inside the file

2023-05-30 14:04 UTC, hatskier commented on packages/on-chain-relayer/test/monorepo-integration-tests/scripts/verify-prices.ts
> +  let contract: PriceFeedsAdapterWithoutRounds = ContractFactory.attach(
Can we change `let` -> `const`?

2023-06-09 08:11 UTC, rpiszczatowski commented on packages/on-chain-relayer/test/monorepo-integration-tests/scripts/deploy-adapter.ts
> +import fs from "fs";
I added word 'mock'. But 'integration test' part is already in folder structure. Do you still want to repeat it in file name?
@hatskier ?

2023-06-09 08:27 UTC, rpiszczatowski commented on packages/on-chain-relayer/test/monorepo-integration-tests/scripts/verify-prices.ts
> +import { ethers } from "hardhat";
same question as above regarding file name: isn't it enough to have it in the folder "monorepo-integration-tests"?
@hatskier ?

2023-06-09 14:02 UTC, hatskier approved these changes

2023-06-09 14:02 UTC, hatskier commented on packages/cache-service/scripts/analyze-data-packages.ts
> +  mongoose.set('strictQuery', true);
Why do you add it in few places? Can we do it in one place?

2023-06-09 14:08 UTC, rpiszczatowski commented on packages/cache-service/scripts/analyze-data-packages.ts
> +  mongoose.set('strictQuery', true);
Hmm. I see no common code where we could put it. I don't think it is worth complicating those scripts by creating some common one just yet. Especially because the explicit setting of the strictQuery parameter is rather temporary. This is to make the code compatible with the next mongoose version where the default will change to true.

2023-06-13 12:00 UTC, hatskier commented on packages/on-chain-relayer/test/monorepo-integration-tests/scripts/deploy-adapter.ts
> +import fs from "fs";
You are right

2023-06-13 12:06 UTC, hatskier approved these changes

2023-06-13 12:06 UTC, merged