refactor: switch to classes in avalanche evm fetcher
redstone-finance/redstone-oracles-monorepo pull request #609
Opened 2023-05-08 11:21 UTC by cehali

2023-05-09 11:17 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/index.ts
> +export const buildRequestHandlers = () => {
What is the pros of using here function over simple static object?

2023-05-09 11:18 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/shared/EvmRequestHandlersBase.ts
> +export interface EvmRequestHandlersBase {
Why `Base` in the name?

2023-05-09 12:34 UTC, koonopek requested changes
I really like this solution!

2023-05-09 12:34 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/request-handlers/GlpManagerRequestHandlers.ts
> +    const valueSerialized = value.mul(divider);
I think that value is some integer (contracts never returns floats). So this will be very big number if we mul it by 1e30 :P

2023-05-09 12:34 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +        const divider = new Decimal(10).toPower(10);
Again why `mul` here, if this is proper then `divder` should be renamed

2023-05-09 12:34 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +      return reservesPricesMulitplied.div(totalSupply).mul(2).toNumber();
Could we link to this formula in JsDoc of function, or if there is no link just write it in math notation?

2023-05-09 12:34 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/AvalancheEvmFetcher.ts
>      const pricesObject: PricesObj = {};
Could we use `extractPricesSafely` here?

2023-05-09 12:34 UTC, koonopek requested changes
I really like this solution! Great job!

2023-05-10 11:34 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/shared/EvmRequestHandlersBase.ts
> +export interface EvmRequestHandlersBase {
I spend too much time with Alex 😄

2023-05-10 11:35 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/request-handlers/GlpManagerRequestHandlers.ts
> +    const valueSerialized = value.mul(divider);
Yes, my bad. Tests are there for `avalanche evm-chain`. In case we will use it more on arbitrum will add them too

2023-05-10 11:36 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/ArbitrumEvmFetcher.ts
> +    const allRequestHandlers = buildRequestHandlers();
Yes, we can call it once in class, agree

2023-05-10 11:37 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +      return reservesPricesMulitplied.div(totalSupply).mul(2).toNumber();
There is comment with the method on top of the file

2023-05-10 11:39 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +import { Decimal } from "decimal.js";
I agree, but I am not sure how to call the folder with contract details and request handlers. Maybe just `sources`?

2023-05-10 17:28 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/ArbitrumEvmFetcher.ts
> +  getRequestHandlers(id: string) {
Maybe this function can be located in the request-handlers file, as it's not a part of the fetching logic. WDYT?

2023-05-10 17:28 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/ArbitrumEvmFetcher.ts
> +  getRequestHandlers(id: string) {
Or even abstracted, as we probable will have similar structure for AvalancheEvmFetcher

2023-05-10 17:28 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/request-handlers/GlpManagerRequestHandlers.ts
> +    const divider = new Decimal(10).toPower(30);
I would move 10 (maybe) and 30 (for sure) to a constant

2023-05-10 17:28 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/request-handlers/index.ts
> +export const buildRequestHandlers = () => {
Maybe we can also export a function for getting a request handler for a given data feed id here

2023-05-10 17:28 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/AvalancheEvmFetcher.ts
> +import { EvmMulticallService } from "../../shared/EvmMulticallService";
Isn't the logic of this fetcher identical with ArbitrumEvmFetcher?

2023-05-10 17:28 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/AvalancheEvmFetcher.ts
> +import { EvmMulticallService } from "../../shared/EvmMulticallService";
I see, it's not, but I don't really understand why

2023-05-10 17:28 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +export type CexLpTokensDetailsKeys = keyof typeof cexLpTokensContractsDetails;
What does the `Cex` prefix mean here?

2023-05-10 23:39 UTC, hatskier reviewed
I like the improvements a lot, both using decimals and switching to separate classes made the code much more readable

2023-05-10 23:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +    const areAllTokensFetched =
Why do we have this log here? And shouldn't we log a warning if areAllTokensFetched is not true?

2023-05-10 23:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +        const multiplier = new Decimal(10).toPower(12);
Please move numbers like 10 or 12 to constants, it will improve the code readability and it's just a good practice

2023-05-10 23:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/GlpManagerRequestHandlers.ts
> +    const divider = new Decimal(10).toPower(30);
Again, please use constants instead of just numbers

2023-05-10 23:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/OracleAdapterRequestHandlers.ts
> +    const decimalDivider = new Decimal(10).toPower(8);
Please use constants for 8 and 10

2023-05-10 23:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/index.ts
> +export const buildRequestHandlers = () => {
`+`

2023-05-10 23:39 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/shared/EvmRequestHandlersBase.ts
> +export interface EvmRequestHandlersBase {
But this is an interface, I would call it with capital `I` letter in the beginning

2023-05-11 07:21 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +    const areAllTokensFetched =
What log?

2023-05-11 07:26 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +    const areAllTokensFetched =
Ahh you mean probably check. If we don't have prices of all tokens from LP pair we don't want to calculate price of LP. I moved this check to separate function and run it a little bit later

2023-05-11 07:30 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/request-handlers/CexLpTokensRequestHandler.ts
> +export type CexLpTokensDetailsKeys = keyof typeof cexLpTokensContractsDetails;
Of course it should be Dex

2023-05-11 07:32 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/AvalancheEvmFetcher.ts
> +import { EvmMulticallService } from "../../shared/EvmMulticallService";
When we switched to `extractPricesSafely` this file was not refactored, I am not sure why

2023-05-11 08:15 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/AvalancheEvmFetcher.ts
> +import { EvmMulticallService } from "../../shared/EvmMulticallService";
I refactored it to have `EvmFetcher` class and `avalancheEvmFetcher`, `arbitrumEvmFetcher` as instances of `EvmFetcher` with different names, providers and request handlers.

2023-05-11 15:53 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/dex-lp-tokens/DexLpTokensRequestHandler.ts
> +export type CexLpTokensDetailsKeys = keyof typeof dexLpTokensContractsDetails;
CexLpTokensDetailsKeys -> DexLpTokensDetailsKeys

2023-05-11 15:53 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/sources/glp-manager/GlpManagerRequestHandlers.ts
> +const EXPONENT_OF_POWER = 30;
EXPONENT_OF_POWER is not a helpful name in my opinion

2023-05-11 15:53 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/sources/glp-manager/GlpManagerRequestHandlers.ts
> +const EXPONENT_OF_POWER = 30;
Currently it just describes how you use it, which is not really helpful when we read the code. It's easy to see that we use it as an exponent of power, but I think the name of this variable should show why we do it

2023-05-11 18:21 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/arbitrum/evm-fetcher/request-handlers/GlpManagerRequestHandlers.ts
> +    const valueSerialized = value.mul(divider);
Great! I think I saw this error in few places, could please validate if in any of this example we should actually mul?

2023-05-11 18:23 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/AvalancheEvmFetcher.ts
>      const pricesObject: PricesObj = {};
I don't know maybe I have missed this place :(

2023-05-11 18:59 UTC, hatskier approved these changes

2023-05-11 18:59 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/glp-manager/GlpManagerRequestHandlers.ts
> +const GLP_MANAGER_PRICE_PRECISION = 30;
WDYT about moving this constant to shared/constants, since it is used in few different files?

2023-05-11 19:21 UTC, hatskier approved these changes

2023-05-11 19:28 UTC, merged