feat: add GMD tokens
redstone-finance/redstone-oracles-monorepo pull request #635
Opened 2023-05-15 11:40 UTC by cehali

2023-06-06 19:42 UTC, hatskier submitted a review, later dismissed

2023-06-06 22:47 UTC, koonopek requested changes
GJ :+1 some minior comments about readbility

2023-06-06 22:47 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/extract-values-with-same-name-from-multicall-response.ts
> +  const results = multicallResult[address];
Maybe we can exit here ealier with different error?
Will be easier to troubelshoot if we know that we are missing all ids not only signle one

2023-06-06 22:47 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/GmdRequestHandlers.ts
> +        `0x${poolInfo.slice(...INDEXES_OF_TOTAL_STAKED_FROM_CONTRACT)}`
Just a question, could link or explain why are we slicing this poolInfo and extracting info in this way?

2023-06-06 22:47 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/gmdTokensContractsDetails.ts
> +    vaultAddress: "0x5517c5F22177BcF7b320A2A5daF2334344eFb38C",
Seems like we don't have to repeat vaultAddress and vaultAbi or just coincidence?

2023-06-06 22:47 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/shared/EvmMulticallService.ts
> +      parsedResponses[address] = [
I think it become pretty hard to write maybe we could simplify it using if and `push` or in any other way

2023-06-06 22:47 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/gmdTokensContractsDetails.ts
> +    vaultAddress: "0x5517c5F22177BcF7b320A2A5daF2334344eFb38C",
SOme for abi

2023-06-06 22:47 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/gmdTokensContractsDetails.ts
> +    tokenToFetch: "USDC",
Could we keep consistent with this names (like in uniswapV2 or curveFetcher) so `token1: "USDC"` for example

2023-06-07 09:26 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/gmdTokensContractsDetails.ts
> +    tokenToFetch: "USDC",
But we won't be compatible with other` avalanche-evm` fetchers where we have `tokensToFetch` or `tokenToFetch`

2023-06-07 09:33 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/GmdRequestHandlers.ts
> +        `0x${poolInfo.slice(...INDEXES_OF_TOTAL_STAKED_FROM_CONTRACT)}`
Pool info returns struct which by multicall contract is returned as a string which requires slicing. Added comment

2023-06-07 09:33 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/gmdTokensContractsDetails.ts
> +    vaultAddress: "0x5517c5F22177BcF7b320A2A5daF2334344eFb38C",
Sure, fixed

2023-06-07 09:35 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/extract-values-with-same-name-from-multicall-response.ts
> +  const results = multicallResult[address];
Yes, I will add check if result is defined

2023-06-07 12:10 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/gmdTokensContractsDetails.ts
> +      vaultAbi: GmdVaultAbi,
Whoops

2023-06-07 12:12 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/GmdRequestHandlers.ts
> +        `0x${poolInfo.slice(...INDEXES_OF_TOTAL_STAKED_FROM_CONTRACT)}`
And we can decode it to some JS structure? Using rlp.decoding or something?

2023-06-07 12:13 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/gmdTokensContractsDetails.ts
> +    tokenToFetch: "USDC",
Yeah, I think we can create seperate task to unify this (had same issue in maveric fetcher)

2023-06-07 12:15 UTC, koonopek submitted a review, later dismissed
2 small comments, I leave them up to you

2023-06-07 13:05 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/gmd/GmdRequestHandlers.ts
> +        `0x${poolInfo.slice(...INDEXES_OF_TOTAL_STAKED_FROM_CONTRACT)}`
Probably, I have never done this but it could be possible. I will create a separate task for it.

2023-06-08 12:10 UTC, hatskier approved these changes

2023-06-09 06:51 UTC, merged