feat: add crvUSDBTCETH token
redstone-finance/redstone-oracles-monorepo pull request #636
Opened 2023-05-15 12:17 UTC by cehali

2023-05-17 12:51 UTC, koonopek requested changes

2023-05-17 12:51 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    const tokenToFetchPrice = getTokensPricesFromLocalCache(tokensToFetch);
If we fail fast here we don't have to check #here1?

2023-05-17 12:51 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    if (tokenToFetchPrice) {
#here1

2023-05-17 12:51 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    if (wbtcLiquidity && wethLiquidity && wcrvLiquidity) {
I think this should be validated in `calculateLiquiditesForCurveToken` but maybe if value from #here1 will be check this won't be needed any more.

2023-05-17 12:51 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    const wbtcBalanceRequest = this.buildErc20BalanceOfRequest(
Maybe we could do this with list like
```js
[btcAddres,ethAddress,crvAdress].reduce((prev,curr) => [...prev, ...this.buildErc20BalanceOfRequest(curr)],[])
```

2023-05-17 12:51 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    const { abi, address } = curveTokensContractsDetails[id];
This is rather general thought not strcitly related to this PR:
We sometimes fetch configuration from .ts files, which can be miss configured and same values may be undefiend for example if `id` is not configured in `curverTokensContracsDetails` we wil sillently fail, I think we should `terminateWithConfgiError` in such cases, but maybe I'm overthinking WDYT?

2023-05-17 12:51 UTC, koonopek commented on packages/oracle-node/test/fetchers/avalanche-evm.spec.ts
> +      await wcrvContract.mock.balanceOf.returns("1092413975173947426287877");
Mocks should be probably parf of the test :) Cause somebody will have to remove them when adding new test

2023-05-19 08:35 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    const { abi, address } = curveTokensContractsDetails[id];
Yes, we could add validation to check if the config has the proper id. I will create a separate task for it.

2023-05-19 08:40 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    const wbtcBalanceRequest = this.buildErc20BalanceOfRequest(
Good idea 👍

2023-05-19 08:53 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/CurveRequestHandlers.ts
> +    const tokenToFetchPrice = getTokensPricesFromLocalCache(tokensToFetch);
Ok, I added check for last price in `getTokensPricesFromLocalCache`

2023-05-19 08:54 UTC, cehali commented on packages/oracle-node/test/fetchers/avalanche-evm.spec.ts
> +      await wcrvContract.mock.balanceOf.returns("1092413975173947426287877");
Those mocks are on a freshly deployed contract which won't be used in other tests

2023-06-20 15:50 UTC, koonopek commented on packages/oracle-node/manifests/dev/main-wide-support.json
> +    "ALC": {
Accident?

2023-06-20 16:04 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/curveTokensContractsDetails.ts
> +};
Maybe we could change dir name to something like `curve-stable` `curve` is reserver for exchange already

2023-06-20 16:04 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/extract-values-with-same-name-from-multicall-response.ts
>    const values = results.map((result) => result[id]);
Are we checking here or somewhere ealier if result ended with success?

2023-06-20 16:04 UTC, koonopek commented on packages/oracle-node/test/fetchers/avalanche-evm.spec.ts
> +      curveTokensContractsDetails.crvUSDBTCETH.address =
(style) Maybe use single object with just one `=`

2023-06-21 07:03 UTC, cehali commented on packages/oracle-node/manifests/dev/main-wide-support.json
> +    "ALC": {
Nope, good catch

2023-06-21 07:06 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/extract-values-with-same-name-from-multicall-response.ts
>    const values = results.map((result) => result[id]);
`performMulticall` is a call to the contract which is handled by simple try...catch. If any result of the multicall fails value from it will be undefined and check for it is a few lines below `if (values.some((value) => !value))`

2023-06-21 07:07 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/get-tokens-prices-from-local-cache.ts
>      const tokenPriceFromDb = getLastPrice(tokenName);
Sure, good idea

2023-06-21 07:10 UTC, cehali commented on packages/oracle-node/test/fetchers/avalanche-evm.spec.ts
> +      curveTokensContractsDetails.crvUSDBTCETH.address =
Good idea

2023-06-21 07:20 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/curve/curveTokensContractsDetails.ts
> +};
It is not `stable` really, it could be `curve-lp-tokens`

2023-06-22 19:05 UTC, hatskier submitted a review, later dismissed

2023-06-23 07:32 UTC, koonopek approved these changes

2023-06-23 07:33 UTC, merged