feat: add contract details config validation
redstone-finance/redstone-oracles-monorepo pull request #665
Opened 2023-05-22 12:58 UTC by cehali

2023-06-26 14:25 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/get-contract-details-from-config.ts
> +    throw new Error(`Misconfiguration for ${id}, cannot get contract details`);
`terminateWithManifestConfigError`?

2023-07-03 08:07 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/get-contract-details-from-config.ts
> +    throw new Error(`Misconfiguration for ${id}, cannot get contract details`);
It isn't manifest error

2023-07-03 10:42 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/get-contract-details-from-config.ts
> +    throw new Error(`Misconfiguration for ${id}, cannot get contract details`);
I think it is because, we configured in manifest fetcher for token which is not supported by this fetcher. We are missing some details about it. Also if we don't terminate(proccess.exit) here we still won't get information at the start of the node that some fetcher won't ever report prices for some token.

2023-07-03 10:43 UTC, koonopek requested changes
Comment for github guys

2023-07-04 07:42 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/shared/utils/get-contract-details-from-config.ts
> +    throw new Error(`Misconfiguration for ${id}, cannot get contract details`);
ok, convinced

2023-07-04 08:20 UTC, koonopek approved these changes

2023-07-04 08:21 UTC, koonopek approved these changes

2023-07-04 08:21 UTC, merged