feat: implemented an extended version of db comparison script
redstone-finance/redstone-oracles-monorepo pull request #682
Opened 2023-05-28 21:57 UTC by hatskier

2023-06-02 17:42 UTC, koonopek requested changes
Very clean script, pleasure to read ;)
Left some comments and please rename script name to something more meanigful

2023-06-02 17:42 UTC, koonopek commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  "0x3a7d971De367FE15D164CDD952F64205F2D9f10c": 1,
EXPECTED_SIGNERS_1 -> EXPECTED_SIGNERS_DEMO
EXPECTED_SIGNERS_2 -> EXPECTED_SIGNERS_PROD
?

2023-06-02 17:42 UTC, koonopek commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  intervals.reverse();
I think we could achive the same in for loop, but I don't care in case of scripts like this

2023-06-02 17:42 UTC, koonopek commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  const onlyInFirst = [...set1].filter((element) => !set2.has(element));
Why shallow copy here?

2023-06-02 17:42 UTC, koonopek commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +function extractAllTimestamps(dataPackages: DataPackagesResponse): Set<number> {
`return new Set(Object.keys(dataPackages).map(Number))`

2023-06-02 17:42 UTC, koonopek commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  return (Math.abs(value1 - value2) / Math.min(value1, value2)) * 100;
I think this is wrong way of calucating deviation it is unfair
`Math.min(value1,value2)` => `value2` 
and add before `if(value2 === 0) return Number.MAX_SAFE_INTEGER`

2023-06-02 17:42 UTC, koonopek commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  return Math.max(
I think `calcDeviation(Math.min(...values1), Math.max(...values2))` is enough, what do you think that we have to calculate `deviation` for every possible worst case.

2023-07-13 17:21 UTC, hatskier commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  "0x3a7d971De367FE15D164CDD952F64205F2D9f10c": 1,
I didn't want to make this assumption that something is always and demo and the other thins is prod

2023-07-14 14:37 UTC, hatskier commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  const onlyInFirst = [...set1].filter((element) => !set2.has(element));
It's not a shallow copy, it's converting a set to an array and then filtering
More info here: https://stackoverflow.com/questions/33234666/how-to-map-reduce-filter-a-set-in-javascript

2023-07-14 14:39 UTC, hatskier commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  return (Math.abs(value1 - value2) / Math.min(value1, value2)) * 100;
This way of calculating deviation jsut returns max value. It works like max(MikeDeviation(val1, val2), MikeDeviation(val2, val1)) and in my opinion it is not so bad in the case of this script

2023-07-14 14:41 UTC, hatskier commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +  return Math.max(
Because e.g. it may be possible that values1 have a very big value outlier

2023-07-14 14:45 UTC, hatskier commented on packages/cache-service/scripts/compare-dbs-alex.ts
> +function extractAllTimestamps(dataPackages: DataPackagesResponse): Set<number> {
Yes, it's way nicer 👍

2023-07-14 16:34 UTC, cehali approved these changes

2023-07-14 16:45 UTC, merged