feat: add test for unique signers when fetching data packages from ca…
redstone-finance/redstone-oracles-monorepo pull request #702
Opened 2023-06-06 11:49 UTC by cehali

…che service

2023-06-06 13:51 UTC, koonopek requested changes
<3 one small comment

2023-06-06 13:51 UTC, koonopek commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    Date.now = jest.fn(() => dpTimestamp);
Can we clear that mock after test, to avoid polluting global objects

2023-06-12 08:20 UTC, cehali commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    Date.now = jest.fn(() => dpTimestamp);
Done

2023-06-12 08:44 UTC, koonopek requested changes

2023-06-12 08:44 UTC, koonopek commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    jest.clearAllMocks();
I think It could work if we do something like:
`jest.spy(Date,'now').mockImplementation(() = > 1200)`
But it won't work for `Date.now = jest.fn(() => 1200)`, because we didn't use `jest` mock mechanics in first place thus jest doesn't know what is original function.

2023-06-22 10:56 UTC, koonopek commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    jest.clearAllMocks();
I think, I have hard time to explain what I mean, maybe code will be self explanatory
<img width="704" alt="image" src="https://github.com/redstone-finance/redstone-oracles-monorepo/assets/24699136/1410e873-cf63-48c9-85cc-7328479e6e09">

2023-06-22 11:21 UTC, cehali commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    jest.clearAllMocks();
New change should work 
![image](https://github.com/redstone-finance/redstone-oracles-monorepo/assets/35804520/c6480be8-bbd3-4e67-b6bf-b7214d22ca10)

2023-06-22 11:21 UTC, koonopek commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    jest.clearAllMocks();
Exactly!

2023-06-22 11:49 UTC, koonopek submitted a review, later dismissed
LGTM!

2023-06-22 14:14 UTC, cehali commented
@koonopek please reapprove 😃

2023-06-23 12:25 UTC, koonopek approved these changes

2023-06-23 12:27 UTC, koonopek approved these changes

2023-06-23 12:27 UTC, koonopek commented on packages/cache-service/test/e2e/data-packages.spec.ts
> +    jest.spyOn(Date, "now").mockImplementation(() => dpTimestamp);
I think you could write it in `performPayloadTests` then you wouldnt need to repeat so many times :)

2023-06-28 13:47 UTC, merged