feat: filter tokens with skip signing when validating big package
redstone-finance/redstone-oracles-monorepo pull request #713
Opened 2023-06-07 09:02 UTC by cehali

2023-06-09 16:12 UTC, hatskier commented on packages/oracle-node/src/validators/validate-data-feed-for-big-package.ts
> +    (count, config) => (config.skipSigning ? count : ++count),
config -> tokenConfig?

2023-06-09 16:12 UTC, hatskier commented on packages/oracle-node/src/validators/validate-data-feed-for-big-package.ts
> +    (count, config) => (config.skipSigning ? count : ++count),
I would also change `++count` to count + 1, as we don't need to increase the value of the variable here, we only need to return the new value

2023-06-12 07:43 UTC, cehali commented on packages/oracle-node/src/validators/validate-data-feed-for-big-package.ts
> +    (count, config) => (config.skipSigning ? count : ++count),
Done

2023-06-12 08:40 UTC, koonopek requested changes

2023-06-12 08:40 UTC, koonopek commented on packages/oracle-node/src/validators/validate-data-feed-for-big-package.ts
> +    throw new Error(`Cannot get token config from manifest.`);
Could we use `terminateWithManifestConfigError` here?

2023-06-12 08:40 UTC, koonopek commented on packages/oracle-node/src/validators/validate-data-feed-for-big-package.ts
> +  const tokensWithoutSkipSigningCount =
What should happen if `tokensWithoutSkipSigningCount === 0`, should we throw or return `false`?

2023-06-12 10:53 UTC, cehali commented on packages/oracle-node/src/validators/validate-data-feed-for-big-package.ts
> +  const tokensWithoutSkipSigningCount =
I think we should return `false` and not create big data package

2023-06-22 11:48 UTC, koonopek requested changes

2023-06-22 16:01 UTC, koonopek approved these changes

2023-06-23 07:28 UTC, merged