feat: slippage calculation for on-chain fetchers
redstone-finance/redstone-oracles-monorepo pull request #716
Opened 2023-06-07 10:11 UTC by rpiszczatowski

2023-06-07 13:04 UTC, hatskier commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +  createReference(slippageAmount: number, isBuy: boolean) {
What do you mean by the `reference` here?

2023-06-07 14:03 UTC, koonopek requested changes

2023-06-07 14:03 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const sqrtPriceX96BeforeSwap = this.decimal(
Should we check here if this call ended with `success` like with filter on line 194?

2023-06-07 14:03 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +      slippage[callReturnContext.reference] = priceAfterSwap
I think return `new Decimal(bigNumberLike.toString());` should be enough.
Also can we use some better type then `any`?

2023-06-07 14:48 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +  calculateSlippage(assetId: string, response: T): number {
I have a problem here. This is conceptually an abstract method. I added implementation only because I don't think it should be necessary to implement it everywhere. For the same reason `calculateLiquidity` could have throwing implementation. It had to be implemented to throw in the Uniswap v3 fetcher. @koonopek what do you think?

2023-06-07 14:53 UTC, rpiszczatowski commented on packages/oracle-node/manifests/single-source/uniswap-v3-on-chain-weth-500.json
> +    "SWETH_uniswap-v3-on-chain-weth-500_SELL_100K_slippage": {
@koonopek This is only an example. In your own manifest, you can add whatever you want, except for the following...

@hatskier this discussion is contradicting your request above to limit possible slippage amounts to 10K and 100K only. Now when I am thinking of it I think that I added this configuration to allow any number of $. Values used here only need to be consistent with those in a fetcher config file.

2023-06-07 14:55 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +  dollars2Tokens(
of course.

2023-06-07 14:55 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +  tokenConfig(
sure.

2023-06-07 14:58 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +  createReference(slippageAmount: number, isBuy: boolean) {
I've changed it to `createSlippageLabel`. The name 'reference' was taken from multicall library lingo. If you have a couple of requests in multicall you can assign a 'reference' to each of them to be able to distinguish the calls while parsing the response.

2023-06-07 17:34 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +        multicallResult.results.quoterContract.originalContractCallContext.calls.filter(
This is related to how ethereum-multicall returns results. But this particular piece of code was leftover from my other approach to calculating price after swap. The value calculated is not used so I'll simply delete that.

2023-06-07 17:45 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +  decimal(bigNumberLike: any): Decimal {
`bigNumberLike` is the result of parsing JSON values like `{ "hex": 0xabc, "type": "BigNumber" }`. I've checked and your suggestion doesn't work. Decimal throws exception regarding wrong input format.

2023-06-07 17:54 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const sqrtPriceX96BeforeSwap = this.decimal(
Under normal circumstances, I see no way for the whole multicall to return the value and this particular call to fail. This is a pure getter. I'd treat the failure of this call similarly to one treat Error being thrown in java. We just don't try to recover from those.

If you have different opinion, I'll apply your suggestion.

2023-06-07 18:01 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +      slippage[callReturnContext.reference] = priceAfterSwap
I consider this part of the preprocessing. But I agree that it could be moved to calculateSlippage :)

2023-06-09 16:04 UTC, hatskier commented on packages/oracle-node/manifests/single-source/uniswap-v3-on-chain-weth-500.json
> +    "SWETH_uniswap-v3-on-chain-weth-500_SELL_100K_slippage": {
I think limiting only to 10K or 100K is not crucial at all

2023-06-12 08:25 UTC, koonopek commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +  calculateSlippage(assetId: string, response: T): number {
Generally I don't like default implementation which throws error, I would rather override it explicit in the deriving class, thus developer would have to think is it okey throw here or maybe he should write some sensible impl. But this is my personal opinion, I want insist

2023-06-12 08:28 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +        (amountInDollars / tokenPrice).toFixed(tokenDecimals),
yeah I think then end game is using decimals everywhere, at least to make code more consistent, and then we could switch from JsNativeSafeNumber to Decimals too and ensure highest possible precision in whole node

2023-06-12 08:28 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +      for (const slippageAmount of poolConfig.slippage || []) {
ping

2023-06-12 11:38 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +  calculateSlippage(assetId: string, response: T): number {
Even before my code was added we had the `convertIdToSymbol` method that was a customization point with the default implementation.

2023-06-12 11:42 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +  calculateSlippage(assetId: string, response: T): number {
or `validateResponse` customization point with default implementation of `respone !== undefined`

2023-06-12 12:52 UTC, koonopek commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +  calculateSlippage(assetId: string, response: T): number {
Yeah, but this default implementation were doing something not just throwing error
But okey lets go with it

2023-06-12 13:04 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    return `${slippageAmount}_${isBuy ? "buy" : "sell"}`;
technically elvis operator (a ?: b) and equivalent ternary operator (a ? a : b) are different things :)

2023-06-12 14:02 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +    const multicallParams = this.prepareMulticallParams(assetId, poolConfig);
ok

2023-06-12 14:08 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/uniswap-v3-on-chain/UniswapV3FetcherOnChain.ts
> +        (amountInDollars / tokenPrice).toFixed(tokenDecimals),
leaving as is as discussed

2023-06-12 15:52 UTC, koonopek submitted a review, later dismissed
GJ 👍 
I'm okey with merging if dry-run passes :)

2023-06-13 12:08 UTC, hatskier commented
> GJ 👍 I'm okey with merging if dry-run passes :)

@koonopek can you please approve if you are okey with merging ;)

2023-06-13 13:56 UTC, koonopek approved these changes

2023-06-13 14:28 UTC, merged