chore: add EUROC token
redstone-finance/redstone-oracles-monorepo pull request #728
Opened 2023-06-13 12:29 UTC by cehali

2023-06-20 16:20 UTC, koonopek requested changes

2023-06-20 16:20 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/steak-hut/SteakHutTokensRequestHandler.ts
> +      if (["USDC", "USDT", "USDT.e", "EUROC"].includes(tokenName)) {
I think it can refactored to some Map, but it is okey for me

2023-06-20 16:20 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +import { avalancheProvider } from "../../../../../utils/blockchain-providers";
unused import ;)

2023-06-20 16:20 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +      this.pairConfig[dataFeedId].address,
I think we could add assert that `this.pairConfig[dataFeedId]` is indeed defined to avoid hard to debug errors

2023-06-20 16:20 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    const binIdSerialized = binId.minus(BIN_ID_DEFAULT_SUBTRACTION);
Should we somehow use here `decimals` params passed in `pairConfig`?

2023-06-21 08:32 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    const binIdSerialized = binId.minus(BIN_ID_DEFAULT_SUBTRACTION);
Values in bin are already serialized

2023-06-21 08:32 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/steak-hut/SteakHutTokensRequestHandler.ts
> +      if (["USDC", "USDT", "USDT.e", "EUROC"].includes(tokenName)) {
Refactored a little bit 😃

2023-06-22 10:46 UTC, koonopek approved these changes

2023-06-22 14:01 UTC, merged