feat: improve mock fetcher and add USDf token
redstone-finance/redstone-oracles-monorepo pull request #754
Opened 2023-06-21 11:11 UTC by cehali

2023-06-22 10:34 UTC, koonopek commented on packages/oracle-node/manifests/data-services/main.json
> +      "fixedValue": 1
I don't get this dualism that we don't have single source of truth github or manifest but rather both of them

2023-06-22 10:37 UTC, koonopek requested changes

2023-06-22 10:37 UTC, koonopek commented on packages/oracle-node/src/fetchers/mock-fetcher/mock-fetcher.ts
> +    if (this.isAnyTokenWithFixedValue(opts.manifest.tokens)) {
1. This can be done before `axios.get` I think.
2. Also why we check `if any` and then execute for every. What if one of tokens doesnt have set `fixedValue`

2023-06-22 10:41 UTC, cehali commented on packages/oracle-node/manifests/data-services/main.json
> +      "fixedValue": 1
It is a different situation, previously we used a mock fetcher for some tests which require frequent changes. Now we want to constantly have `USDf` as 1. I can easily imagine a situation where someone deletes a repo or file with mocked values. Here it will be hard to remove this value as it needs to pass PR and redeploy the node.

2023-06-22 10:42 UTC, cehali commented on packages/oracle-node/src/fetchers/mock-fetcher/mock-fetcher.ts
> +    if (this.isAnyTokenWithFixedValue(opts.manifest.tokens)) {
1. Explained in the previous comment, overengineering in this scenario and prone to human error. 
2. It means that we have misconfiguration in manifest, we want all of the to be from URL or with `fixedValue`

2023-06-23 08:23 UTC, koonopek commented on packages/oracle-node/src/fetchers/mock-fetcher/mock-fetcher.ts
> +    if (this.isAnyTokenWithFixedValue(opts.manifest.tokens)) {
Still don't get it because now we can one feature "mock-url" or second "fixed value in manifest", we can use two feature in the same node at the same time. And as you said earlier this are two distinct things, so why are we trying to fit them in one fetcher?
(Maybe i don't understand something)

2023-06-23 08:29 UTC, koonopek commented on packages/oracle-node/src/fetchers/mock-fetcher/mock-fetcher.ts
> +    if (this.isAnyTokenWithFixedValue(opts.manifest.tokens)) {
1. If I setup in env `mockPricesUrlOrPath` to some URL I will never used value from `manfiest[token].fixedValue`.
2. And if I setup `mockPricesUrlOrPath` to fs path I will return prices only for tokens which have setup `fixedValue`.
3. And last case if I don't set in any token `fixedValue` and set `mockPricesUrlOrPath` to fs path I will return prices from json file.

Pretty complicated stuff, do you think we can simplify it? Or It has to be like that?

A.D 2. So maybe we should throw error if this is misconfiguration :)

2023-06-26 14:23 UTC, koonopek approved these changes

2023-06-26 14:23 UTC, koonopek commented on packages/oracle-node/src/fetchers/fixed-value-fetcher/fixed-value-fetcher.ts
> +      result[id] = response[id] ?? response.__DEFAULT__;
What is this `__DEFAULT` thing

2023-06-27 07:18 UTC, cehali commented on packages/oracle-node/src/fetchers/fixed-value-fetcher/fixed-value-fetcher.ts
> +      result[id] = response[id] ?? response.__DEFAULT__;
Leftover from mock fetcher, removed

2023-06-27 12:49 UTC, koonopek approved these changes
GJ!

2023-06-27 12:49 UTC, merged