feat: use relayer manifests in relayers
redstone-finance/redstone-oracles-monorepo pull request #790
Opened 2023-07-03 08:18 UTC by rpiszczatowski

2023-07-03 11:16 UTC, cehali commented on packages/integration/.gitignore
> +relayerManifest.json
Please add new line

2023-07-03 11:17 UTC, cehali commented on packages/on-chain-relayer/.env.example
> +MANIFEST_FILE=../integration/relayerManifest.json
Please add new line

2023-07-03 12:42 UTC, koonopek requested changes

2023-07-03 12:43 UTC, koonopek commented on packages/on-chain-relayer/src/core/contract-interactions/update-prices.ts
> +  deliveryMan = deliveryMan ?? new TransactionDeliveryMan({
I think it only have sens if you create new file for that

2023-07-03 13:39 UTC, rpiszczatowski commented on packages/on-chain-relayer/relayer-manifests/vestatestnet.json
> +    "timeSinceLastUpdateInMilliseconds": 3600000
This is the plan. However, we need to introduce the changes to main first, to have a stable git sha to point to in monitoring.

2023-07-03 13:43 UTC, rpiszczatowski commented on packages/on-chain-relayer/src/config.ts
> +    const errMsg = `Adapter contract type not supported: ${relayerConfig.adapterContractType}`;
because it has always been. I'll inline it.

2023-07-03 13:50 UTC, rpiszczatowski commented on packages/on-chain-relayer/src/core/update-conditions/value-deviation-condition.ts
>    const { minDeviationPercentage } = config;
It doesn't need to be defined in general. But once we run this code we are sure that it is defined, because the value-deviation-condition is only triggered when 'minDeviationPercentage' is included in RelayerConfig object.

2023-07-03 14:09 UTC, koonopek commented on packages/rpc-providers/src/TransactionDeliveryMan.ts
> +    console.log(`1deliver transaction: gas limit ${gasLimit}`);
Please remove this comments

2023-07-04 08:17 UTC, koonopek commented on packages/on-chain-relayer/src/core/contract-interactions/update-prices.ts
> +  console.error(`adapter type: ${config().adapterContractType}`);
I think we still have console.error here

2023-07-04 08:17 UTC, koonopek commented on packages/on-chain-relayer/src/core/contract-interactions/update-prices.ts
> +  console.error("mento adapter");
still console.error here

2023-07-04 09:27 UTC, cehali commented on packages/on-chain-relayer/relayer-manifests/canto.json
> +  "priceFeeds": {
CANTO - https://testnet.tuber.build/address/0xaCf97fb2f2c336c45b799DAB925ad10ADC70fCAC
ETH - https://testnet.tuber.build/address/0xd75F4B5AA9480E6956f2570Dd258ca716784f6E1
ATOM - https://testnet.tuber.build/address/0x1cd0AB40549BA6812a6ec602e8897f8e28566AbE 
USDC - https://testnet.tuber.build/address/0x1a6bbc6Ff8BEeE20B4177Ac87580F4e2aF3Abf71
USDT - https://testnet.tuber.build/address/0x31714B74fbf6ca78eC60C07f10eef061b20E192E

2023-07-04 09:29 UTC, cehali commented on packages/on-chain-relayer/relayer-manifests/goerli.json
> +{
By the way maybe we could remove unused relayers and leave only manifests which will be used?

2023-07-04 10:05 UTC, koonopek submitted a review, later dismissed

2023-07-04 10:09 UTC, cehali commented on packages/on-chain-relayer/src/FilesystemConfigProvider.ts
> +  if (manifest.updateTriggers.timeSinceLastUpdateInMilliseconds) {
you could destructure manifest and manifest.updateTriggers, it could be easier to read e.g.:
`const { deviationPercentage, timeSinceLastUpdateInMilliseconds } = manifest.updateTriggers;`

2023-07-05 09:36 UTC, rpiszczatowski commented on packages/on-chain-relayer/relayer-manifests/goerli.json
> +{
I've created separate issue for this.

2023-07-06 10:52 UTC, cehali commented on packages/on-chain-relayer/relayer-manifests/canto.json
> +    "CANTO": "0xaCf97fb2f2c336c45b799DAB925ad10ADC70fCAC",
Sorry, yesterday I found out that those are no up to date, here are new ones

CANTO - https://testnet.tuber.build/address/0x6E27A25999B3C665E44D903B2139F5a4Be2B6C26

ETH - https://testnet.tuber.build/address/0xa64f6836336dad187f9CfAEA77069Ce88F53863E

ATOM - https://testnet.tuber.build/address/0x1eE28c30C2B4cA240502AB9D665C167e7e72289c

USDC - https://testnet.tuber.build/address/0x9C3f3c7856A68f7957631AeBF497D80f82c18eF8

USDT - https://testnet.tuber.build/address/0xD716c3C7Da17Da37fE3D3BAc91b36bb68D29D3B4

2023-07-06 10:56 UTC, cehali commented on packages/on-chain-relayer/src/FilesystemConfigProvider.ts
> +export const fileSystemConfigProvider: ConfigProvider = () => {
I like the idea but would like to know if adding another layer of abstraction is necessary when we won't have a different type of passing the config

2023-07-06 13:31 UTC, koonopek approved these changes

2023-07-06 16:47 UTC, koonopek approved these changes

2023-07-06 16:47 UTC, koonopek commented on packages/on-chain-relayer/src/core/contract-interactions/update-prices.ts
> +const getDeliveryManager = () => {
He is the man not some manager 😠

2023-07-07 06:23 UTC, rpiszczatowski commented on packages/on-chain-relayer/src/core/contract-interactions/update-prices.ts
> +const getDeliveryManager = () => {
I am very sorry for misnaming the Man ...

2023-07-07 09:52 UTC, koonopek submitted a review, later dismissed

2023-07-07 13:28 UTC, koonopek approved these changes

2023-07-07 13:44 UTC, hatskier approved these changes

2023-07-07 13:44 UTC, merged