chore: update STETH sources
redstone-finance/redstone-oracles-monorepo pull request #798
Opened 2023-07-04 13:53 UTC by cehali

2023-07-04 13:56 UTC, cehali commented on packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts
> +  async handleRequestsForBybit(ids: string[]) {
This is required because "old" and "new" tokens are treated differently and handled by different versions of bybit API. Without it, we will only get tokens with `symbol-to-id` values with `USDT:USDT` in the end. If we try to use `STETH/USDT:USDT` we will receive error than this symbol doesn't exist

2023-07-04 22:24 UTC, hatskier requested changes

2023-07-04 22:24 UTC, hatskier commented on packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts
> +  async handleRequestsForBybit(ids: string[]) {
I would like to solve it differently. First of all, I believe our mechanism with symbol to id custom mapping should solve all potential cases and shouldn't require functions like this. But even if for some reason it is not sufficient, I don't think it's a good idea to make async calls for fetching tickers, since we can do it once and save in files (like we do with symbol-to-id)

2023-07-05 07:28 UTC, cehali commented on packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts
> +  async handleRequestsForBybit(ids: string[]) {
I don't understand tbh. We always make async call to fetch tickers https://github.com/redstone-finance/redstone-oracles-monorepo/blob/6aaf5fa5c761449e41b20075d16f5e97e4af62ae/packages/oracle-node/src/fetchers/ccxt/CcxtFetcher.ts#L52. 

Maybe you misunderstand what `fetchTickers` do here, it fetches price for ids. 

It is a second attempt to integrate a new version of bybit and the previous solution with a separate fetcher name `bybit-v5` was rejected. Then it wasn't important but now we need to integrate it. 
If you have any idea how to solve this case with custom symbol to id mapping I am gladly to hear that I am buying you a beer if you find it 🍺  😄

2023-07-05 11:35 UTC, hatskier approved these changes

2023-07-05 12:14 UTC, merged