feat: add score by address route
redstone-finance/redstone-oracles-monorepo pull request #85
Opened 2022-10-18 15:51 UTC by cehali

2022-10-19 13:52 UTC, hatskier requested changes

2022-10-19 13:52 UTC, hatskier commented on packages/oracle-node/src/routes/score-by-address.ts
> +  const scoreData = { symbol: address, value: score };
Do we really need the `scoreData` variable? Can't we just pass address and score directly?

2022-10-19 13:52 UTC, hatskier commented on packages/oracle-node/src/routes/score-by-address.ts
> +const fetchData = async (address: string): Promise<number> => {
Let's change the `fetchData` function name to something more describing, e.g. `fetchScoreForAddress`

2022-10-19 13:52 UTC, hatskier commented on packages/oracle-node/src/routes/score-by-address.ts
> +  const { timestamp, signature } = params;
Let's move this line to the top to replace `params.timestamp && params.signature` with `timestamp && signature`

2022-10-19 13:52 UTC, hatskier commented on packages/oracle-node/src/routes/score-by-address.ts
> +  const isAddressInLimited = checkIfAddressIsLimited(
Do we also want to add some kind of address activity check? E.g. if it had any transactions on some blockchain

2022-10-19 13:52 UTC, hatskier commented on packages/oracle-node/src/routes/services/LimitedAddressService.ts
> +  let limitedAddresses: LimitedAddress[] = [];
What do you think about changing this array to an object `{ [address: string]: {numberOfRequests: number, lastRequestTimestamp: number} }`, so that we can allow few requests (e.g. 10) for the same address during one hour? I am a bit afraid of rate limiting to 1 request per hour, as it can make quite poor UX for some cases

2022-10-20 08:43 UTC, cehali commented on packages/oracle-node/src/routes/score-by-address.ts
> +  const isAddressInLimited = checkIfAddressIsLimited(
Here we only want a rate limit. I would place checking address activity as fetching score. I think this is only a boilerplate which can be extended for the score/binary score of the activity or a mix of both.

2022-10-20 09:22 UTC, cehali commented on packages/oracle-node/src/routes/services/LimitedAddressService.ts
> +  let limitedAddresses: LimitedAddress[] = [];
Good idea 👍

2022-10-24 22:13 UTC, hatskier requested changes

2022-10-24 22:13 UTC, hatskier commented on packages/oracle-node/src/routes/services/LimitedAddressesService.ts
> +export const pushToLimitedAddresses = (
Can we change the naming a bit to make the code more readable? I would propose the following changes:
- LimitedAddressService -> RateLimitingService
- checkIsAddressWithoutAccess -> hasAddressReachedRateLimit
- pushToLimitedAddresses -> recordRequestSentByAddress

2022-10-24 22:13 UTC, hatskier commented on packages/oracle-node/src/routes/services/LimitedAddressesService.ts
> +const MAX_NUMBER_OF_REQUESTS = 1;
Can we please set it to a number bigger than one and cover it with tests. I am a bit afraid of a poor UX with 1 request alloowed per hour. I would rather set 5 or 10

2022-10-24 22:13 UTC, hatskier commented on packages/oracle-node/src/routes/services/LimitedAddressesService.ts
> +    const filteredLimitedAddressesArray = Object.entries(
Wouldn't it be more efficient to just iterate over the object keys and using `delete` operation when needed?

2022-10-24 22:13 UTC, hatskier commented on packages/oracle-node/src/routes/services/LimitedAddressesService.ts
> +  [address: string]: { numberOfRequests: number; lastRequestTimestamp: number };
Sorry for changing the idea again, but what do you think about storing a list of timestamps (`number[]`) instead of `{ numberOfRequests: number; lastRequestTimestamp: number }`? Otherwise our rate limiter will work incorrectly, e.g. if you make 4 requests from 00:00 till 01:00 and then one request at 3:00, then you'll be rate limited till 4:00

2022-10-25 16:04 UTC, hatskier requested changes

2022-10-25 16:04 UTC, hatskier commented on packages/oracle-node/src/routes/score-by-address.ts
> +        dataPoints: signedDataPackage.dataPackage.dataPoints.map((dataPoint) =>
What do you think about using the following code instead?
```js
return res.json(signedDataPackage.toObj());
```

2022-10-26 08:09 UTC, cehali commented on packages/oracle-node/src/routes/score-by-address.ts
> +  recordRequestSentByAddress(address, timestamp);
Now when I am thinking about it could provide to the situation when someone has no access at all if constantly requesting after requesting more than max times

2022-10-26 08:10 UTC, cehali commented on packages/oracle-node/src/routes/score-by-address.ts
> +  recordRequestSentByAddress(address, timestamp);
Now when I am thinking about it could provide to the situation when someone has no access at all if constantly requesting after requesting more than max times

2022-10-26 14:13 UTC, hatskier commented on packages/oracle-node/src/routes/services/RateLimitingService.ts
> +  const addressTimestamps = recordedAddresses[address]?.timestamps ?? [];
What do you think about replacing this code 
```js
const addressTimestamps = recordedAddresses[address]?.timestamps ?? [];
recordedAddresses[address] = {
  timestamps: [...addressTimestamps, timestamp],
};
```
with this code?
```js
if (!recordedAddresses[address]?.timestamps) {
  recordedAddresses[address] = {timestamps: []};
}
recordedAddresses[address]!.timestamps.push(timestamp);
```

to improve the complexity (O(1) instead of O(N))

2022-10-26 14:13 UTC, hatskier commented on packages/oracle-node/src/routes/score-by-address.ts
> +    throw new Error(`Address ${address} checked its score in the last hour`);
Can we please change the error message to a more generic one as we can use the rate limiting service later for other use cases? e.g.: "Address ${address} reached rate limit. Please try in an hour"

2022-10-26 14:13 UTC, hatskier commented on packages/oracle-node/src/routes/score-by-address.ts
> +    throw new Error(`Address ${address} checked its score in the last hour`);
Can we please change the error message to a more generic one as we can use the rate limiting service later for other use cases? e.g.: "Address ${address} reached rate limit. Please try in an hour"

2022-10-26 14:13 UTC, hatskier approved these changes

2022-10-27 07:40 UTC, merged