feat: integration tests in typescript
redstone-finance/redstone-oracles-monorepo pull request #854
Opened 2023-07-13 16:16 UTC by rpiszczatowski

2023-07-14 14:32 UTC, hatskier requested changes
Great job! Clean, nice, and easily extendable code 💪

2023-07-14 14:32 UTC, hatskier commented on packages/integration/integration-test-core.ts
> +main()
Missing semicolon

2023-07-14 14:32 UTC, hatskier commented on packages/integration/integration-test-common.ts
> +const configureLogging = (childProcess: ChildProcess, logPrefix: string) => {
I would propose to rename this function to `addPrefixToProcessOutput` or `addPrefixToProcessLogs`

2023-07-14 14:32 UTC, hatskier commented on packages/integration/integration-test-common.ts
> +    configureLogging(result, "yarn install");
I would call this vairable `childProcess` instead of `result`, as the name `result` can be confused with the process result

2023-07-14 14:32 UTC, hatskier commented on packages/integration/integration-test-common.ts
> +    await sleep(5000);
Can we please move 5000 to a constant here and in the `waitForUrl` function?

2023-07-14 14:32 UTC, hatskier commented on packages/integration/integration-test-common.ts
> +  ).substring(0, 25);
Can we move 25 to a constant?

2023-07-14 14:32 UTC, hatskier commented on packages/integration/integration-test-classic.ts
> +  while (
Won't it freeze instead of failing tests sometimes?

2023-07-14 14:54 UTC, rpiszczatowski commented on packages/integration/integration-test-classic.ts
> +  while (
I'll change it to 5 loop revolutions and then fail.

2023-07-17 10:27 UTC, hatskier commented on packages/integration/integration-test-classic.ts
> +  while (
Why do we need to have a loop here at all?

2023-07-18 14:26 UTC, hatskier approved these changes

2023-07-18 14:26 UTC, merged