chore: simplify fallback deviationtime update conditions
redstone-finance/redstone-oracles-monorepo pull request #856
Opened 2023-07-14 09:50 UTC by Lukasz2891

2023-07-14 16:59 UTC, hatskier requested changes

2023-07-14 16:59 UTC, hatskier commented on packages/on-chain-relayer/src/args/get-iteration-args.ts
> +  const olderDataPackagesPromise =
Why can't we wait just add await here instead of passing the promise?

2023-07-14 16:59 UTC, hatskier commented on packages/on-chain-relayer/src/core/fetch-data-packages.ts
> +const olderPackagesTimestamp = (deviationCheckOffsetInMinutes: number) => {
Please rename to `calculateOlderPackagesTimestamp`

2023-07-14 16:59 UTC, hatskier commented on packages/on-chain-relayer/src/core/update-conditions/value-deviation-condition.ts
> +    const olderDataPackages = await olderDataPackagesPromise;
AFAIU, you try to fetch older data packages only if it's needed. But the following code doesn't work this way. IN the moment you've created the `olderDataPackagesPromise` it starts fetching the data. Here we only add waiting for it

2023-07-15 07:55 UTC, Lukasz2891 commented on packages/on-chain-relayer/src/args/get-iteration-args.ts
> +  const olderDataPackagesPromise =
The intention was to have lazy fetching, but it failed to do it :( 

I'll change it to a callback.

2023-07-17 16:45 UTC, hatskier approved these changes

2023-07-17 16:45 UTC, hatskier commented on packages/on-chain-relayer/src/core/update-conditions/value-deviation-condition.ts
> +  olderDataPackagesFetchCallback: () => Promise<DataPackagesResponse>
Can't we just use this function directly without passing it as an argument?
Also, I would rename it to `getOlderDataPackages` or `fetchOlderDataPackages`

2023-07-17 16:48 UTC, merged