feat: add long dry runs for avalanche and primary
redstone-finance/redstone-oracles-monorepo pull request #884
Opened 2023-07-26 11:58 UTC by cehali

2023-07-26 15:58 UTC, cehali commented on .github/workflows/long-avalanche-dry-run-test.yml
> +  group: ${{ github.workflow }}-${{ github.ref }}
This will cancel previous jobs in the new one is coming

2023-07-27 06:43 UTC, koonopek commented on .github/workflows/long-avalanche-dry-run-test.yml
> +  group: ${{ github.workflow }}-${{ github.ref }}
What do you think about running all these tests in a single workflow file (sequentially)?
I think that it is the worse solution, however, it has one advantage of minimising API usage (cause of rate limits problem)

2023-07-27 06:52 UTC, koonopek reviewed
GJ! Left some questions / ideas

2023-07-27 06:52 UTC, koonopek commented on packages/integration/src/framework/compare-data-packages.ts
> +const omittedDataFeeds = ["___ALL_FEEDS___", "crvUSDBTCETH"];
Why do we omit `crvUSDBTCETH`

2023-07-27 06:52 UTC, koonopek commented on packages/integration/src/framework/compare-data-packages.ts
> +export const compareDataPackagesFromLocalAndProd = (
Are we reusing the script written by you or Alex, for comparing responses from DB?
If not, maybe we could do this WDYT?

2023-07-27 06:52 UTC, koonopek commented on packages/integration/src/framework/compare-data-packages.ts
> +export const compareDataPackagesFromLocalAndProd = (
If so, it would be best to separate it to some common function used both here and in scripts

2023-07-27 06:52 UTC, koonopek commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    for (const timestampDiffNumber of timestampsCountToAnalyze) {
What do you think about optimising it with Promise.all (maybe no need, if it is pretty fast already)

2023-07-27 07:06 UTC, cehali commented on packages/integration/src/framework/compare-data-packages.ts
> +export const compareDataPackagesFromLocalAndProd = (
It is a little bit different, in db we aggregate them by the signer and also check if there is the same number of data packages. Here is the simplified version and I think it is so simple that adjusting code from db would be more complex than this code

2023-07-27 07:06 UTC, cehali commented on packages/integration/src/framework/compare-data-packages.ts
> +const omittedDataFeeds = ["___ALL_FEEDS___", "crvUSDBTCETH"];
We changed calculation method and currently there is big difference between prod and dev nodes, it could be removed after updating pro nodes

2023-07-27 07:07 UTC, cehali commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    for (const timestampDiffNumber of timestampsCountToAnalyze) {
Agree, I will change it

2023-07-27 07:10 UTC, cehali commented on .github/workflows/long-avalanche-dry-run-test.yml
> +  group: ${{ github.workflow }}-${{ github.ref }}
Good idea

2023-07-27 08:27 UTC, cehali commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    for (const timestampDiffNumber of timestampsCountToAnalyze) {
Done

2023-07-27 08:28 UTC, cehali commented on .github/workflows/long-avalanche-dry-run-test.yml
> +  group: ${{ github.workflow }}-${{ github.ref }}
As discussed in person, we should leave it as it is. If we hit rate limits with one additional node we should probably consider increasing APIs plans

2023-07-27 12:14 UTC, rpiszczatowski commented on packages/integration/.eslintrc.js
> +    tsconfigRootDir: __dirname,
instead of this change you should add the following to your vscode workspace configuration file:
```
    "eslint.workingDirectories": [
      "./packages/gelato-relayer",
      "./packages/integration",
      "./packages/cache-service",
    ]
```

2023-07-27 13:19 UTC, rpiszczatowski approved these changes

2023-07-27 14:39 UTC, merged

2023-07-27 14:51 UTC, hatskier requested changes

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/compare-data-packages.ts
> +const omittedDataFeeds = ["___ALL_FEEDS___", "crvUSDBTCETH"];
I would see a big value in comparing data from ____ALL_FEEDS___ along with all other feeds

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/compare-data-packages.ts
> +const omittedDataFeeds = ["___ALL_FEEDS___", "crvUSDBTCETH"];
I believe we should not ignore any feeds and we can use local manifest for checking if all required feeds are available in the local node, we can also use the manifest from the URL specified in the remote config for monitoring, as we specify it there. OFC, we should not hardocde the url to remote-config, we should pass it as a secret

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/compare-data-packages.ts
> +      throw new Error(
I think we should not throw the error right away. We should collect the final report, print it and if it has any errors then throw an error (in the end of the github action)

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/fetch-data-packages-from-local-and-prod-cache.ts
> +      `https://oracle-gateway-2.a.redstone.finance/data-packages/historical/redstone-${manifestFileName}-prod/${timestamp}`
Can we move the URL prefix to a constant?

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/fetch-latest-timestamp-from-local-cache.ts
> +import axios from "axios";
I would rename the folder integration to e2e (end to end tests), maybe in a separate PR

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/compare-data-packages.ts
> +const omittedDataFeeds = ["___ALL_FEEDS___", "crvUSDBTCETH"];
But we can do it in a separate PR

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/compare-data-packages.ts
> +const omittedDataFeeds = ["___ALL_FEEDS___", "crvUSDBTCETH"];
We can do it in a separate PR

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +  updateManifestFile("interval", String(nodeInterval), newManifestPath);
Can't we just call
```js
updateManifestFile("interval", String(nodeInterval), `../oracle-node/manifests/data-services/${manifestFileName}.json`);
```
?

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    const timestampsRange = [...Array(iterationsCount).keys()];
Let's add a simple check if `timestampsRange.length` is not too small (e.g. at least 12)

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +      iterationsCount - coldStartIterationsCount
Since we need to do a cold start to calculate dependent values, our change of the interval (from 10s to 60s) can influence the result values. Maybe we can run first `coldStartIterationsCount` iterations with 10s and then switch to `60s`. Let's discuss it and maybe implement in a separate PR

2023-07-27 14:51 UTC, hatskier commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    const iterationsCount =
WDYT about requesting the latest timestamp and then just deducting `nodeIntervalInMilliseconds`?

2023-07-27 15:18 UTC, cehali commented on packages/integration/src/framework/compare-data-packages.ts
> +      throw new Error(
After discussion, print all deviations also

2023-07-27 15:28 UTC, cehali commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +      iterationsCount - coldStartIterationsCount
Change to default 10 sec, delete overwrite manifest function