fix: manifest path in long dry runs
redstone-finance/redstone-oracles-monorepo pull request #891
Opened 2023-07-27 15:03 UTC by cehali

2023-07-28 05:36 UTC, rpiszczatowski commented on .github/workflows/long-avalanche-dry-run-test.yml
> +    branches: "*"
Are you sure about this? All the code review branches?

2023-07-28 05:38 UTC, rpiszczatowski commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
The correct way is to use the `unknown` as a type for the `error` variable instead of disabling linter.

2023-07-28 05:39 UTC, rpiszczatowski requested changes
.

2023-07-28 06:59 UTC, cehali commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
<img width="558" alt="image" src="https://github.com/redstone-finance/redstone-oracles-monorepo/assets/35804520/332a49d7-3b2e-4c70-924c-843f012856fe">
I am not sure, I cannot use `error` then

2023-07-29 11:22 UTC, rpiszczatowski commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
This is unfortunate but technically any type of object can be thrown from JS and this is why typescript does not allow arbitrary types for catch variables but only `any` and `unknown` are allowed. If you want to make use of the object as a particular type you have to add proper type assertion: (error as Error).stack will do.

To summarize IMO the 'proper' way would be to use `unknown` as a type and then explicitly cast in the catch statement body.

2023-07-29 11:24 UTC, rpiszczatowski approved these changes

2023-07-29 11:29 UTC, rpiszczatowski commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
BTW if you looked at the `configureCleanup` method you would see that it adds handling of unhandled exceptions, so this whole try catch is probably not very valuable. If you think it is good to have some better handling maybe you could add it in `configureCleanup` so all the suits make use of it.

2023-07-31 07:05 UTC, cehali commented on packages/integration/src/framework/run-long-price-propagation-core-test.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
Ok, will remove it in next PR which will improve long time tests

2023-07-31 07:05 UTC, merged