feat: add obfuscation to node code
redstone-finance/redstone-oracles-monorepo pull request #893
Opened 2023-07-28 07:55 UTC by cehali

2023-07-28 12:15 UTC, koonopek submitted a review, later dismissed

2023-07-28 12:15 UTC, koonopek commented on packages/oracle-node/Dockerfile
> +RUN cp Dockerfile ../oracle-node-obfuscated
Why do we need Dockerfile in Docker already :)

2023-07-28 12:15 UTC, koonopek commented on packages/oracle-node/Dockerfile
> +RUN apt-get update && apt-get install cpio
I think this should be run on line 10 for better caching

2023-07-31 08:50 UTC, rpiszczatowski commented on packages/oracle-node/Dockerfile
> +RUN cp -R oracle-node-obfuscated ..
Wouldn't it be cleaner to output the obfuscated code directly to `../oracle-node-obfuscated`? You wouldn't need to copy around the result.

2023-07-31 09:12 UTC, cehali commented on packages/oracle-node/Dockerfile
> +RUN cp -R oracle-node-obfuscated ..
It is obfuscated to `../oracle-node-obfuscated` but we want to have it in the main folder so it could replace the original code

2023-07-31 10:03 UTC, rpiszczatowski requested changes
Assuming the goal of this PR is to hide oracle-node code from the public, it doesn't do it as oracle-node code can be still seen:
- in other images: relayer, cache service
- in the intermediate layers

I recommend switching to multistage builds and being explicit about what we have in our images.

2023-07-31 11:19 UTC, rpiszczatowski commented on packages/oracle-node/Dockerfile
> +RUN cp -R oracle-node-obfuscated ..
It is obfuscated to `./oracle-node-obfuscated` from what I see. I think the better way would be to do as you wrote to obfuscate it to `../oracle-node-obfuscated` and then just rename the directory, exactly as you are doing now. This would allow for getting rid of `cp -R ...`

2023-07-31 11:24 UTC, cehali commented on packages/oracle-node/Dockerfile
> +RUN cp -R oracle-node-obfuscated ..
It won't be as then it will rename each obfuscated file to e.g. `index-obfuscated.js` and all things depending on filenames would stop working

2023-07-31 12:18 UTC, cehali commented on packages/oracle-node/Dockerfile
> +RUN cp -R oracle-node-obfuscated ..
It will change in new version and I will remove `cp -R ...`

2023-08-02 11:30 UTC, rpiszczatowski commented on Dockerfile
> +COPY packages/protocol/package.json ./
What about top-level package.json and what about yarn.lock? Shouldn't those be present to use the same packages versions as those used for testing?

2023-08-02 11:47 UTC, rpiszczatowski commented on packages/cache-service/test/common/mock-values.ts
> +import { utils } from "redstone-protocol";
Why those changes are required? Test code shouldn't be even touched during docker image build so it should be irrelevant to changes done in Dockerfiles.

2023-08-02 11:48 UTC, cehali commented on packages/cache-service/test/common/mock-values.ts
> +import { utils } from "redstone-protocol";
It is much relevant for build stage and importing from local dependencies

2023-08-02 11:52 UTC, rpiszczatowski reviewed
What about cache-service and relayer Dockerfiles. The are not changed by this PR (yet)

2023-08-02 19:12 UTC, rpiszczatowski commented on packages/rpc-providers/package.json
> +    "@nomicfoundation/hardhat-toolbox": "2.0.2",
Why this change?

2023-08-02 19:23 UTC, rpiszczatowski commented on packages/cache-service/Dockerfile
> +RUN yarn install --frozen-lockfile --non-interactive --production=false
What is the idea here? Why do we first run `yarn install --production=false` here and then we run the same command with `--production=true`?

2023-08-02 19:58 UTC, rpiszczatowski commented on packages/cache-service/Dockerfile
> +RUN yarn workspaces run build
Wouldn't it be enough to simply run `yarn build` in the cache-service directory. This should build all the dependencies automatically.

2023-08-03 07:26 UTC, cehali commented on packages/oracle-node/Dockerfile
> +FROM build AS oracle-node
It is better to have more stages as they can be calculated parallelly

2023-08-03 07:31 UTC, cehali commented on packages/cache-service/package.json
> +    "redstone-protocol": "*",
I don't think I understand the question, you want to get rid of the version or get rid of the whole `redstone-protocol` etc? The empty string is equivalent to `"*"`. After reading about how dependencies work I think we should have all dependencies defined in the `package.json`, also local ones.

2023-08-03 07:54 UTC, rpiszczatowski commented on packages/oracle-node/Dockerfile
> +FROM build AS oracle-node
But they aren't if one stage uses another as a base.

2023-08-03 08:07 UTC, rpiszczatowski commented on packages/cache-service/package.json
> +    "redstone-protocol": "*",
The fact that we use workspaces does the job of making each workspace available to all the others (via symlinks in top-level node_modules directory created during `yarn install` command run).

2023-08-03 12:17 UTC, cehali commented on packages/cache-service/Dockerfile
> +RUN yarn install --frozen-lockfile --non-interactive --production=false
Discussed during call

2023-08-03 12:17 UTC, cehali commented on packages/cache-service/package.json
> +    "redstone-protocol": "*",
Discussed during call

2023-08-03 12:17 UTC, cehali commented on packages/cache-service/Dockerfile
> +RUN yarn workspaces run build
Agree, implemented

2023-08-03 15:23 UTC, rpiszczatowski commented on packages/cache-service/Dockerfile
> +RUN yarn install --frozen-lockfile --non-interactive --production=false
Basically there is no way to compile the code without dev dependencies.

2023-08-03 15:45 UTC, rpiszczatowski commented on packages/on-chain-relayer/tsconfig.json
> +    "baseUrl": "."
Do we need `baseUrl`. It looks like a leftover of something. Similarly in other places.

2023-08-03 16:17 UTC, rpiszczatowski commented on packages/cache-service/Dockerfile
> +COPY packages/cache-service/package.json ./packages/cache-service/
Now, with explicitly defined workspaces, we end up having workspaces for which we don't copy package.json before performing the build. I am not sure what implications this have.

2023-08-03 16:18 UTC, rpiszczatowski approved these changes

2023-08-04 09:33 UTC, cehali commented on packages/cache-service/Dockerfile
> +COPY packages/cache-service/package.json ./packages/cache-service/
We don't use the command `yarn workspaces` which will iterate through all defined workspaces, I tested it locally and we are able to build image and then run container from it

2023-08-04 09:35 UTC, cehali commented on packages/on-chain-relayer/tsconfig.json
> +    "baseUrl": "."
yes, I will remove it

2023-08-04 10:06 UTC, rpiszczatowski approved these changes

2023-08-04 12:05 UTC, koonopek commented on packages/cache-service/Dockerfile
>  ENV ENABLE_JSON_LOGS=true
We don't create own user as on OWASP suggetion

2023-08-04 12:05 UTC, koonopek commented on packages/cache-service/Dockerfile
>  ENV ENABLE_JSON_LOGS=true
Our recent report highlighted that 58% of images are running the container entrypoint as root (UID 0). However, it is a Dockerfile best practice to avoid doing that. There are very few use cases where the container needs to execute as root, so don’t forget to include the USER instruction to change the default effective UID to a non-root user.

2023-08-04 12:05 UTC, koonopek commented on packages/on-chain-relayer/Dockerfile
> +COPY packages/on-chain-relayer/package.json ./packages/on-chain-relayer/
Same suggestion as with cache-service DockerFile. Also as I see we could extract common image from all docker files because first stage of multibuild is the same

2023-08-04 12:05 UTC, koonopek commented on packages/oracle-node/Dockerfile
Same as with other Dockerfiles

2023-08-04 13:02 UTC, cehali commented on packages/cache-service/Dockerfile
> +COPY --from=build /app/packages/cache-service/dist ./packages/cache-service
Because we don't want to copy all `package.json` files, we just want part of it. Yes, and this is correct that you add new packages and you consciously add it docker. It increase security as only things you know should be in container are here and not whole monorepo

2023-08-04 13:03 UTC, cehali commented on package.json
> -      "packages/*"
Because not all things should be in workspaces, especially packages which are completely separate and not connected with others. It simplifies dependencies and add well defined structure

2023-08-04 13:04 UTC, cehali commented on packages/cache-service/Dockerfile
> +RUN yarn install --frozen-lockfile --non-interactive --production=true
Because previous `node_modules` won't be the same as this one as we use production mode. Also, I don't think copying `node_modules` in good practice.

2023-08-04 13:07 UTC, cehali commented on packages/cache-service/Dockerfile
> +COPY packages/protocol/package.json ./packages/protocol/
Do you know the command which copies well-defined part of the monorepo to the docker? Also, it is better to define what packages and not copy the whole monorepo as it was before. It reduces docker image size, increases security and makes it really straightforward what it is used. If you want to add a new package used by another it would require additional 4 lines of change.

2023-08-04 13:09 UTC, cehali commented on packages/on-chain-relayer/Dockerfile
> +COPY packages/on-chain-relayer/package.json ./packages/on-chain-relayer/
It is not the same as we don't want to copy the whole monorepo. On-chain relayer or cache service don't need oracle-node or evm-connector. This could provide additional problems and additional work like obfuscating node code. In this way, we have well-defined structure what is needed to make the package work.

2023-08-04 13:10 UTC, cehali commented on packages/oracle-node/Dockerfile
Same anserw

2023-08-04 13:26 UTC, cehali commented on packages/oracle-node/Dockerfile
I think the best is to explain it on Monday during the call

2023-08-07 08:16 UTC, koonopek commented on packages/cache-service/Dockerfile
> +COPY --from=build /app/packages/cache-service/dist ./packages/cache-service
Can't we use docker-ignore for that?

2023-08-07 08:17 UTC, koonopek commented on packages/cache-service/Dockerfile
> +RUN yarn install --frozen-lockfile --non-interactive --production=true
Why? It is a common pattern I think in docker files. You don't have yarn installed on the final image which is an advantage.

2023-08-07 08:18 UTC, koonopek commented on packages/cache-service/Dockerfile
> +COPY packages/protocol/package.json ./packages/protocol/
Per Dockerfile, in my opinion it matters as long as it is more then 1 line.

2023-08-07 08:20 UTC, koonopek commented on packages/cache-service/Dockerfile
> +COPY packages/protocol/package.json ./packages/protocol/
`.dockerignore` + `COPY src_dir dst_dir`

2023-08-07 08:23 UTC, koonopek commented on packages/on-chain-relayer/Dockerfile
> +COPY packages/on-chain-relayer/package.json ./packages/on-chain-relayer/
Okey, I got your point now, I think we can discuss it after daily WDYT.
I see the advantages and disadvantages of both solutions now, thanks.

2023-08-07 10:16 UTC, rpiszczatowski commented on packages/cache-service/Dockerfile
> +RUN yarn install --frozen-lockfile --non-interactive --production=true
The main point is that we don't want devDependencies in the final image. The approach with calling yarn install twice is described e.g. here: https://sachithsiriwardana.medium.com/dockerizing-nodejs-application-with-multi-stage-build-e30477ca572

2023-08-07 10:19 UTC, rpiszczatowski commented on packages/cache-service/Dockerfile
>  ENV ENABLE_JSON_LOGS=true
Let's create a ticket for this.

2023-08-07 10:30 UTC, rpiszczatowski commented on packages/cache-service/Dockerfile
> +COPY --from=build /app/packages/cache-service/dist ./packages/cache-service
We build multiple docker images from the top directory of our monorepo. Having common .dockerignore maybe problematic. We may only put there things that are not required by any of images.

2023-08-07 10:40 UTC, rpiszczatowski commented on .github/workflows/oracle-node-deploy-to-ecr-public.yml
Why changing the file name. Now it is not adequate as it builds also cache-service.

BTW do we have any particular reason to have two workflows for three images? Maybe we could have a single workflow?

2023-08-07 12:43 UTC, cehali commented on .github/workflows/oracle-node-deploy-to-ecr-public.yml
You are right, this name shouldn't be changed. Two workflows for three images is pointless, either three workflows or one 😄 I would opt for three

2023-08-07 12:46 UTC, cehali commented on packages/cache-service/Dockerfile
> +COPY --from=build /app/packages/cache-service/dist ./packages/cache-service
I thought about docker-ignore also but I belive it wouldn't be simpler. The biggest issue I think would be with readability, you had to remember that most of configuration how would docker container would look like is in docker-ignore

2023-08-08 06:11 UTC, cehali commented on .github/workflows/oracle-node-deploy-to-ecr-public.yml
Updated

2023-08-08 08:15 UTC, rpiszczatowski approved these changes

2023-08-08 11:06 UTC, merged