feat: add manifest for Delta on arbitrum
redstone-finance/redstone-oracles-monorepo pull request #932
Opened 2023-08-07 10:53 UTC by cehali

2023-08-08 23:36 UTC, hatskier requested changes

2023-08-08 23:36 UTC, hatskier commented on packages/oracle-node/manifests/data-services/arbitrum.json
> +    "SOFRAI_EFFECTIVE_DATE": {
We don't need SOFR feeds in this manifest. Can you please take a look into our discord with Delta to check what tokens they want to have in the arbitrum manifest? https://discord.com/channels/889510301421166643/931225562628890667/1134813050231337050

2023-08-09 10:29 UTC, cehali commented on packages/oracle-node/manifests/data-services/arbitrum.json
> +    "SOFRAI_EFFECTIVE_DATE": {
Done

2023-08-09 11:48 UTC, hatskier approved these changes

2023-08-09 11:53 UTC, merged