feat: add slippage calculation to TraderJoeV2OnChainFetcher
redstone-finance/redstone-oracles-monorepo pull request #944
Opened 2023-08-09 13:50 UTC by rpiszczatowski

2023-08-10 09:17 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +            swapAmountBase!,
Why you use here `!` when you `swapAmountBase` can be undefined based on:
```js
const swapAmountBase = basePrice
      ? this.convertDollarsToSubTokens(
          SLIPPAGE_SIMULATION_AMOUT,
          basePrice,
          baseTokenConfig.decimals
        )
      : undefined;
```
I feel like we are losing typing here, we are responsible for calculating this so we can decide what to do with an undefined value but now we just assume that it won't be undefined.

2023-08-10 09:18 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +            pairedPriceInBase!
The same situation as with `swapAmountBase` from https://github.com/redstone-finance/redstone-oracles-monorepo/pull/944/files#r1289821323

2023-08-10 09:18 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +            basePriceInPaired!
The same situation as with swapAmountBase from https://github.com/redstone-finance/redstone-oracles-monorepo/pull/944/files#r1289821323

2023-08-10 09:18 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
>      return {
Can we move calculations from the return statement?

2023-08-10 09:20 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +      baseInPairedPrice *
Maybe calculate it outside the return statement and use `decimal.js` function `.mul`

2023-08-10 09:22 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return actualPrice.minus(spotPrice).abs().dividedBy(actualPrice).times(100);
Please move `100` to a separate variable, preferred to the top of the file with capital letters name

2023-08-10 10:07 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    const basePriceInPaired = basePrice ? basePrice / pairedPrice : undefined;
What do you think about using abstraction like https://github.com/redstone-finance/redstone-oracles-monorepo/blob/80f8540b234247c237e396dd10dc684c61d97472/packages/oracle-node/src/fetchers/curve/CurveFetcher.ts#L152
Iny my opinion it simplify core logic. Allow to avoid this constant ifs => `?:``

2023-08-10 10:09 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +      sellSlippage: basePrice
Yeah I think we should create some helper class here, it is beacming a little bit unreadable

2023-08-10 10:17 UTC, koonopek requested changes

2023-08-10 10:17 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +      getLastPrice(this.getPairedTokenConfig(assetId).symbol)!.value
It will return some weird shit if getLastPrice returns undefined. Use getRawPriceOrFail to have better error message in node. Then just "couldn't cast undefined to number" or smth like this.
Also to keep precision, you could do: `binStepPlusOne.pow(binIdSerialized).mul(getRawPriceOrfail(this.getPairedTokenConfig(assetId).symbol))`

2023-08-10 10:17 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return undefined!;
Why you just don't change signature of calcualteLiquidity. This way we are avoiding typescript checks. Thus making our software less secure.

2023-08-10 10:17 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return amount.dividedBy(this.decimal(10).toPower(decimals));
I have create little helper class for this in RedstoneUtils: https://github.com/redstone-finance/redstone-oracles-monorepo/blob/3bb852eb33d7a60a6468d5dae48751827862a1f5/packages/utils/src/math/index.ts#L37 
(still not merged)

2023-08-10 10:17 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return actualPrice.minus(spotPrice).abs().dividedBy(actualPrice).times(100);
Can we be consistent with this Decimal names sometimes I see `mul` and `div` sometimes `dividedBy` and `times`

2023-08-10 10:17 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return new Decimal(BigNumber.from(bigNumberLike).toString());
We have a lot of function like that maybe we could export it to common packages

2023-08-10 10:17 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return this.decimal(
I think I create already helper for that, could you re use it:
 https://github.com/redstone-finance/redstone-oracles-monorepo/blob/3bb852eb33d7a60a6468d5dae48751827862a1f5/packages/oracle-node/src/fetchers/SlippageAndLiquidityCommons.ts#L6

2023-08-10 11:37 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +            swapAmountBase!,
Because it won't. This condition can be deduced by static code analysis, TS compiler simply doesn't see this. It requires help. BTW. this is one of the reasons why ! exists, i.e. helping the compiler.

So why it CANNOT be `undefined` here:
As you can see `swapAmountBase` is undefined iff (if and only if) `basePrice` is undefined and I use `swapAmountBase!` only in code paths where `basePrice !== undefined`.

2023-08-10 11:39 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
>      return {
Sure, they were a little simpler when I put them directly in the return statement :)

2023-08-10 11:46 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return actualPrice.minus(spotPrice).abs().dividedBy(actualPrice).times(100);
We could, but it would require remembering what we agreed to and even before that to agree on something. @koonopek feel free to impose a convention and I'll stick to it.

2023-08-10 11:58 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    const basePriceInPaired = basePrice ? basePrice / pairedPrice : undefined;
I wanted to have all the variables const, but I can change those couple of ternary operators to a single if statement that will initialize everything that should be initialized when the `basePrice` is available and then use another if statement while handling response. This would make the code more similar to the one you pointed. I'll do that.
The !s will disappear as a consequence. @cehali :)

2023-08-10 12:10 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +      getLastPrice(this.getPairedTokenConfig(assetId).symbol)!.value
`getLastPrice` cannot return `undefined` as we called it above and it returned something that is not undefined. But you are right, I'll reuse the originally fetched value to avoid confusion. Also, I've changed already this code to return string and so it makes sense to use Decimals all to the very end of calculations.

2023-08-10 12:10 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return amount.dividedBy(this.decimal(10).toPower(decimals));
Because when this code was written it was not allowed. Will change now. Thanks.

2023-08-10 12:11 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return undefined!;
Because when this code was written it was not allowed. Will change now. Thanks.

2023-08-10 12:26 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return this.decimal(
This code is not merged yet.

2023-08-10 12:39 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return amount.dividedBy(this.decimal(10).toPower(decimals));
I now. Once your code is merged, we can change this.

2023-08-10 12:42 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return new Decimal(BigNumber.from(bigNumberLike).toString());
I thought about it, but on the other hand, this is an obvious oneliner. Maybe next time? :)

2023-08-11 11:57 UTC, koonopek reviewed
Some minior style comments, you have to resolve conflicts anyway

2023-08-11 11:57 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return amount.dividedBy(this.decimal(10).toPower(decimals));
It merged

2023-08-11 11:57 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return new Decimal(BigNumber.from(bigNumberLike).toString());
Please add it to common like all other functions, there will be no next time probably

2023-08-11 11:57 UTC, koonopek commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    return this.decimal(
Merged

2023-08-11 13:12 UTC, cehali commented on packages/oracle-node/src/fetchers/dex-on-chain/DexOnChainFetcher.ts
> +      }
WDYT 
```js
      const liquidity = this.calculateLiquidity(
        dataFeedId,
        response
      );
      if (liquidity) {
        metadata.liquidity = liquidity.toString();
      }
```
?

2023-08-11 13:20 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    let sellSlippage;
Maybe add `Decimal | undefined` as type?

2023-08-11 13:21 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +          routerResults.find((x) => x.reference === "slippage_buy")!
Maybe change `x` to `result`?

2023-08-11 13:25 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +      ];
Could we extract a function called something like `buildContractCalls` which will return this array?

2023-08-11 13:25 UTC, cehali commented on packages/oracle-node/src/fetchers/evm-chain/avalanche/trader-joe-on-chain/trader-joe-v2/TraderJoeV2OnChainFetcher.ts
> +    ];
Could we extract a function called something like `buildContractCalls` which will return this array?

2023-08-14 09:06 UTC, cehali approved these changes
LGTM

2023-08-14 11:57 UTC, merged