feat: slippage calculation in balancer multi fetcher
redstone-finance/redstone-oracles-monorepo pull request #965
Opened 2023-08-14 15:42 UTC by rpiszczatowski

2023-08-17 12:58 UTC, cehali commented on packages/oracle-node/test/fetchers/balancer-multi.spec.ts
> +  };
I think I have seen it already, maybe move it to some common file?

2023-08-17 13:39 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +    const baseTokenPrice = getLastPrice(assetId)?.value;
Don't we want to use here `getRawPriceOrFail` also and not have `if (baseTokenPrice)` below?

2023-08-17 13:41 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +    const multicallResult = await this.createMulticallInstance().call(
I think extracting should be in `calculate...` function not in `makeRequest`. In most of the fetchers we use `makeRequest` function only to fetch data and extraction is done in separate functions

2023-08-17 13:48 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private decimal(bigNumberLike: {}): Decimal {
If returned value from the multicall is big number in hex we can directly pass it to `new Decimal`

2023-08-21 06:49 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private decimal(bigNumberLike: {}): Decimal {
Also can we use some better type then `{}`?

2023-08-21 06:50 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +    return this.decimal(
We already have common function like this, is there specific reason you don't want to reause it?

2023-08-21 06:59 UTC, koonopek requested changes

2023-08-21 06:59 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private reverseTokensOrder(swap: SwapConfig): SwapConfig {
Shouldnt be static?

2023-08-21 06:59 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +        contractAddress: BALANCER_VAULT_ADDRESS,
Why you don't want to use https://github.com/redstone-finance/redstone-oracles-monorepo/blob/3c52e558d51345c4bacaed343ee4f25d47fb8d9e/packages/utils/src/common/multicall.ts#L10?
You could then remove this `labels` logic and resolving output. There would be less => less bugs :P

2023-08-21 06:59 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private convertSubTokensToTokens(amount: Decimal, decimals: number): Decimal {
Again you could use `PriceScaler` here it is doing exactly the same thing. However, has one advaantage that you could rember what is is doing and don't have to read code like this every time.

2023-08-21 06:59 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private convertSubTokensToTokens(amount: Decimal, decimals: number): Decimal {
Then if you would have to touch many fetcher and the would use common Classes as helper it will be easier to introduce changes.

2023-08-21 06:59 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +    return actualPrice
We already have common function for this: https://github.com/redstone-finance/redstone-oracles-monorepo/blob/3c52e558d51345c4bacaed343ee4f25d47fb8d9e/packages/oracle-node/src/fetchers/SlippageAndLiquidityCommons.ts#L18.
Some advantages as in next comment.

2023-08-21 06:59 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +const SLIPPAGE_SIMULATION_AMOUT = 10_000;
We already have const for this, lets use it. It will be easier then to change :)
https://github.com/redstone-finance/redstone-oracles-monorepo/blob/3c52e558d51345c4bacaed343ee4f25d47fb8d9e/packages/oracle-node/src/fetchers/SlippageAndLiquidityCommons.ts#L4

2023-08-28 09:46 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +    const multicallResult = await this.createMulticallInstance().call(
Honestly, I don't understand the idea here. Let's look at some code that is not mine, MaverickFetcher. This code parses protocol response to 5 values, namely:

- price
- smallSellAmountOutScaled
- smallBuyAmountOutScaled
- bigSellAmountOutScaled
- bigBuyAmountOutScaled

All of them are already parsed and adjusted somehow, e.g. Scaled suffix means that the value is already converted from subtokens to tokens and price is the value returned from protocol squared and multiplied by constant to reflect base to paired ratio.
In the calculateXXX methods, only the 'final' transformations are done like multiplying price by paired token price to get the price in dollars or calculation of slippage from spot price and parsed values from swap simulations. Could you explain to me what is the reasoning behind such a division of responsibilities? Also, what exactly should be done with the response from protocol in makeRequest and what in calculateXXX methods?

2023-08-28 09:58 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private decimal(bigNumberLike: {}): Decimal {
It is rather a BigNumber object, not a string. This function is supposed to work also with strings and numbers. As I have it defined in a couple of places now, I can extract it or maybe get rid of it once I adjust the code according to other comments in this PR.

2023-08-28 10:41 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private reverseTokensOrder(swap: SwapConfig): SwapConfig {
Honestly, I see not much value in making methods static if they are not part of the class interface. Also, we do not have this After marking all of the methods in Uniswap fetcher as static the annoying thing was that each time I needed to call the static method I had to prefix it with class name. The latest refactor of this class (change of the class name) generated lots of changes (in terms of diff size). I just today spent quite a lot of time resolving those conflicts on my branch with changing slippage implementation for Uniswap...

2023-08-28 11:13 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +        contractAddress: BALANCER_VAULT_ADDRESS,
Because multicall.ts:
- does not support returning multiple values from a single call
- shifts labels logic to indexing logic. Imagine what happens if you change calls order in multicall. Just from reading the code it is not obvious that such a change requires change in parsing values from response. The interface where I label the call first and then get the response by that label cannot be confused that way.

2023-08-28 13:47 UTC, cehali commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +    const multicallResult = await this.createMulticallInstance().call(
Yes, I see. Previously we used `fetchData` in non-DEX fetchers as a function which only calls e.g. `axios.get()`. Then we introduce DEXes fetchers with `makeRequest` and in my understanding, they should only fetch on-chain and all extractions, and calculations should be done in separate functions like `calculateSpotPrice` and `calculateLiquidity`. I don't know when it was mixed and I remember I wrote a similar thing in some other PR but probably it wasn't taken under consideration. I assume it is all right then

2023-08-30 06:49 UTC, koonopek commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private reverseTokensOrder(swap: SwapConfig): SwapConfig {
Maybe, I'm not a fun of static too. But this is a rule that we established some time ago, that if we don't touch class fields, the method should be static, something like a `pure` modifier in solidity. I wouldn't change this rule based on a single PR. Let's follow conventions and if we want to change them let's discuss it separately from PR to avoid being biased.

2023-08-30 08:02 UTC, koonopek submitted a review, later dismissed

2023-08-30 16:03 UTC, rpiszczatowski commented on packages/oracle-node/src/fetchers/balancer-multi/BalancerMultiFetcher.ts
> +  private reverseTokensOrder(swap: SwapConfig): SwapConfig {
fixed

2023-09-01 08:34 UTC, koonopek approved these changes
LGTM

2023-09-01 08:58 UTC, merged