feat: use redstone memoize instead of nestjs Cache
redstone-finance/redstone-oracles-monorepo pull request #984
Opened 2023-08-21 11:42 UTC by koonopek

2023-08-22 06:47 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +    (dataServiceId: string) =>
It has to be  wrapped with arrow function, otherwise jest.spy doesnt work.
`bind(this)` also doesnt work

2023-08-23 12:10 UTC, cehali commented on packages/utils/src/common/memoize.ts
> +export function memoize<T, A extends unknown[]>(
I think maybe we could add more tests for the `memoize` function. It seems that currently we don't have any and we could check e.g. if it works correctly with hundreds of requests per minute as it could case in gateway

2023-08-23 12:21 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +export function memoize<T, A extends unknown[]>(
Yeah, that is good point we should properly reset cache after TTL, I will add this and tests

2023-08-24 15:15 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +export function memoize<T, A extends unknown[]>(
@cehali  done

2023-08-25 09:43 UTC, hatskier commented
Newer version has been published

2023-08-25 12:12 UTC, hatskier requested changes

2023-08-25 12:12 UTC, hatskier commented on packages/utils/test/common/memoize.spec.ts
> +  afterEach(() => {
Can you please add a test case with "more real" promise (e.g. sleep 500ms then resolve)?
Can you please also create a test case with different memoized functions `(e.g. const memoized1 = memoize(mockFn1, 1000); const memoize(mockFn2, 1000)` and test if they return different and correct results?

2023-08-25 12:13 UTC, hatskier commented on packages/utils/src/common/memoize.ts
> +  const cache: Record<string, MemoizeCache<T>> = {};
Nice!

2023-08-25 13:05 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +  setInterval(() => cleanStaleCacheEntries(cache, ttl), cleanCacheInterval);
I was thinking about it, however it has one big drawback, that if we will call like in cache service memoized function very many times in the short period of time. We will have to iterate over whole cache and check for stale ttls, this is O(cache_size) thus  is some kind of overhead. Running it every 10 seconds removes that overhead, and we are using native mechanics of nodeJS, so we are not moving anything new :)

2023-08-25 13:07 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +    const cacheKey = args.map((arg) => arg!.toString()).join();
It will handle better but still not perfectly cause it won't handle sorting keys in Object, which can lead to hard to catch bugs. I would rather treat it explicit and if we need support for Object just add it. Serializing every object to json can be quite inefficient especially for large objects :)

2023-08-25 13:09 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +          cache[cacheKey].lastSet = -1;
I like delete :)
1 or -1 doesnt have difference

2023-08-25 13:13 UTC, koonopek commented on packages/utils/test/common/memoize.spec.ts
> +  afterEach(() => {
Good idea

2023-08-25 15:43 UTC, hatskier commented on packages/utils/src/common/memoize.ts
> +    const cacheKey = args.map((arg) => arg!.toString()).join();
Agreed to use JSON.stringify by defualt with assertion to strings be shorter than 10K symbols. We also want to have an option to set a custom cacheKeyBuilder, e.g.
```js
const memoized = memoize({
	fn: (args: any) => Promise<any>;
	cacheKeyBuilder?: (args: any) => string;
});

```

2023-08-28 07:15 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +    const cacheKey = args.map((arg) => arg!.toString()).join();
Done

2023-08-28 07:34 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +  setInterval(() => cleanStaleCacheEntries(cache, ttl), cleanCacheInterval);
Done :)

2023-08-28 17:16 UTC, hatskier submitted a review, later dismissed

2023-08-28 17:16 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +    functionToMemoize: (dataServiceId: string) =>
Mabe call it asyncFunctionToMemoize? Just an idea, we can also do it later

2023-08-28 17:16 UTC, hatskier commented on packages/utils/src/common/memoize.ts
> +  assertWithLog(
Shouldn't we assert it after creating a new cache key? under the line `const cacheKey = cacheKeyBuilder(args);`?

2023-08-28 17:24 UTC, koonopek commented on packages/utils/src/common/memoize.ts
> +  assertWithLog(
What is a difference?

2023-08-29 08:46 UTC, koonopek commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +    functionToMemoize: (dataServiceId: string) =>
I dont see any pros of adding async this is encoded in signature anyway, what is your view on that?

2023-08-29 13:58 UTC, hatskier commented on packages/cache-service/src/data-packages/data-packages.service.ts
> +    functionToMemoize: (dataServiceId: string) =>
I though about adding async just to make it more clear that memoization works only with functions that return promises. But you are right that it will also be suggested by typescript

2023-08-29 13:59 UTC, hatskier commented on packages/utils/src/common/memoize.ts
> +  assertWithLog(
The difference is in the potential number is errors in logs. It would work esp. in a different way if we throw an error. If we assert it only after creating the cache key we will run the assertion one time per each cache key, but if we assert it here, it can be called several times for the same cache key

2023-08-29 14:35 UTC, hatskier approved these changes

2023-08-29 15:47 UTC, merged